// SEO topic plan — cluster set C for SunMetricLab (sunmetriclab.com)
// Clusters: Roof & Shading (20), Batteries & Storage (30), Inverters & Components (20)
// First entry of each cluster is the pillar article; remaining entries are ordered
// roughly foundational -> advanced. Topic plan only — no article content here.

export const clusters = [
  {
    cluster: 'Roof suitability and shading',
    category: 'Roof & Shading',
    entries: [
      {
        title: 'Is Your Roof a Good Fit for Solar? The Complete Suitability Guide',
        slug: 'is-your-roof-good-for-solar',
        primaryKeyword: 'is my roof good for solar',
        secondaryKeywords: ['roof suitability for solar panels', 'solar roof assessment', 'can my roof support solar panels'],
        searchIntent: 'A homeowner wants a full framework for judging whether their roof can host a productive solar array before calling installers.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
        pillar: true,
      },
      {
        title: 'South-Facing vs East-West Solar Panels: Which Layout Wins?',
        slug: 'south-facing-vs-east-west-solar-panels',
        primaryKeyword: 'south facing vs east west solar panels',
        secondaryKeywords: ['best roof orientation for solar', 'east west solar panel production'],
        searchIntent: 'A homeowner is comparing how much energy a south-facing layout produces versus an east-west split on their roof.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Solar on a North-Facing Roof: What US Homeowners Should Expect',
        slug: 'solar-panels-north-facing-roof',
        primaryKeyword: 'solar panels on north facing roof',
        secondaryKeywords: ['north facing roof solar production', 'is a north roof bad for solar'],
        searchIntent: 'Someone whose only open roof plane faces north wants to know if solar can still make sense and how much output they lose.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Roof Pitch and Solar Output: Does Your Angle Really Matter?',
        slug: 'roof-pitch-solar-panels',
        primaryKeyword: 'roof pitch for solar panels',
        secondaryKeywords: ['best roof angle for solar', 'solar panel tilt on sloped roof'],
        searchIntent: 'A homeowner wants to understand how their roof slope affects solar production and whether tilt correction is worth it.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Reading the Shadows: How a Solar Shading Analysis Works',
        slug: 'solar-shading-analysis',
        primaryKeyword: 'solar shading analysis',
        secondaryKeywords: ['solar shade report', 'sun path analysis for solar'],
        searchIntent: 'A shopper wants to know how installers measure shade on a roof and how to interpret the shading numbers in a quote.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Trees vs Solar Panels: Trim, Remove, or Design Around Them?',
        slug: 'trees-and-solar-panels',
        primaryKeyword: 'trees shading solar panels',
        secondaryKeywords: ['cut down trees for solar', 'tree trimming for solar panels'],
        searchIntent: 'A homeowner with mature trees wants to weigh trimming, removal, or an array layout that works around the shade.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Should You Replace Your Roof Before Going Solar?',
        slug: 'replace-roof-before-solar',
        primaryKeyword: 'replace roof before solar',
        secondaryKeywords: ['how old can a roof be for solar', 'new roof and solar at the same time'],
        searchIntent: 'A homeowner with an aging roof wants a clear rule of thumb for whether to re-roof before panels go up.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar on Asphalt Shingles: The Most Common Install in America',
        slug: 'solar-panels-asphalt-shingle-roof',
        primaryKeyword: 'solar panels on asphalt shingle roof',
        secondaryKeywords: ['solar on composition shingles', 'shingle roof solar mounting'],
        searchIntent: 'An owner of a standard shingle roof wants to know how panels attach and what to watch for during installation.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Metal Roofs and Solar: A Better Match Than You Might Think',
        slug: 'solar-panels-metal-roof',
        primaryKeyword: 'solar panels on metal roof',
        secondaryKeywords: ['standing seam metal roof solar', 'solar on corrugated metal roof'],
        searchIntent: 'A metal-roof owner wants to know whether panels can mount without penetrations and how metal compares to shingles for solar.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Installing Solar on Clay and Concrete Tile Roofs',
        slug: 'solar-panels-tile-roof',
        primaryKeyword: 'solar panels on tile roof',
        secondaryKeywords: ['clay tile roof solar installation', 'concrete tile solar mounting'],
        searchIntent: 'A homeowner with a tile roof wants to understand the special mounting methods, breakage risk, and added labor involved.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Ballasted Solar on Flat Roofs: How Panels Stay Put Without Holes',
        slug: 'flat-roof-ballasted-solar',
        primaryKeyword: 'flat roof solar panels',
        secondaryKeywords: ['ballasted solar mounting', 'solar on flat roof house'],
        searchIntent: 'An owner of a flat or low-slope roof wants to know how ballasted racking works and whether their roof can carry the weight.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Complex Rooflines: Fitting Solar Around Dormers, Hips, and Valleys',
        slug: 'solar-complex-roof-dormers',
        primaryKeyword: 'solar panels on complex roof',
        secondaryKeywords: ['solar around dormers', 'multi plane roof solar design'],
        searchIntent: 'A homeowner with a cut-up roofline wants to know how designers piece an array across small planes and what it costs in output.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'HOA Rules and Solar Panels: Your Rights and Aesthetic Options',
        slug: 'hoa-rules-solar-panels',
        primaryKeyword: 'hoa solar panel rules',
        secondaryKeywords: ['solar access laws hoa', 'all black solar panels for hoa'],
        searchIntent: 'A homeowner in an HOA community wants to know what the association can legally restrict and how to keep the array low-profile.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Solar in Snow Country: Roof Design Choices That Pay Off',
        slug: 'solar-panels-snow-roof-considerations',
        primaryKeyword: 'solar panels snow roof',
        secondaryKeywords: ['snow load solar panels', 'solar panel snow shedding'],
        searchIntent: 'A homeowner in a snowy region wants to know how snow load, shedding, and panel placement should shape their roof design.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Hurricane and High-Wind Ratings for Rooftop Solar',
        slug: 'solar-panel-wind-hurricane-ratings',
        primaryKeyword: 'solar panel wind rating',
        secondaryKeywords: ['hurricane rated solar panels', 'solar panel wind uplift'],
        searchIntent: 'A coastal or high-wind-zone homeowner wants to understand wind uplift ratings and what keeps panels attached in a storm.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Will Solar Void Your Roof Warranty? Penetrations, Flashing, and Fixes',
        slug: 'solar-roof-warranty-penetrations',
        primaryKeyword: 'does solar void roof warranty',
        secondaryKeywords: ['solar roof penetration leaks', 'roof warranty after solar installation'],
        searchIntent: 'A cautious homeowner wants to know how mounting penetrations affect their roof warranty and what proper flashing looks like.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Skylights, Vents, and Chimneys: Planning Panels Around Roof Obstacles',
        slug: 'roof-obstructions-solar-layout',
        primaryKeyword: 'roof obstructions solar panel layout',
        secondaryKeywords: ['solar panels around skylights', 'roof vents and solar design'],
        searchIntent: 'A homeowner wants to know how skylights, vents, and setback rules shrink usable roof space and how designers work around them.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Ground-Mounted Solar: When Skipping the Roof Makes Sense',
        slug: 'ground-mount-vs-roof-solar',
        primaryKeyword: 'ground mount vs roof mount solar',
        secondaryKeywords: ['ground mounted solar for home', 'is ground mount solar better'],
        searchIntent: 'A homeowner with land and a problematic roof wants to compare ground-mount trade-offs in cost, output, and permitting.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Measure Your Usable Roof Area for Solar Without Climbing a Ladder',
        slug: 'measure-roof-area-for-solar',
        primaryKeyword: 'how to measure roof for solar panels',
        secondaryKeywords: ['usable roof area for solar', 'diy roof measurement solar'],
        searchIntent: 'A DIY-minded homeowner wants a safe, step-by-step way to estimate usable roof square footage before requesting quotes.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'How Accurate Are Satellite Solar Estimates for Your Roof?',
        slug: 'satellite-solar-estimate-accuracy',
        primaryKeyword: 'satellite solar estimate accuracy',
        secondaryKeywords: ['project sunroof accuracy', 'online solar estimate vs site visit'],
        searchIntent: 'A shopper who used an online mapping tool wants to know how much to trust satellite-based production estimates versus a site survey.',
        relatedCalculators: ['solar-panel-calculator'],
      },
    ],
  },
  {
    cluster: 'Solar batteries and storage',
    category: 'Batteries & Storage',
    entries: [
      {
        title: 'How Home Solar Batteries Work, From Sunlight to Backup Power',
        slug: 'how-home-solar-batteries-work',
        primaryKeyword: 'how do solar batteries work',
        secondaryKeywords: ['home battery storage explained', 'solar energy storage basics'],
        searchIntent: 'A curious homeowner wants a plain-English explanation of how a home battery charges, discharges, and keeps the lights on.',
        relatedCalculators: ['solar-battery-calculator'],
        pillar: true,
      },
      {
        title: 'kWh vs kW: Decoding Home Battery Specs',
        slug: 'battery-kwh-vs-kw',
        primaryKeyword: 'battery kwh vs kw',
        secondaryKeywords: ['battery capacity vs power output', 'home battery specs explained'],
        searchIntent: 'A shopper confused by spec sheets wants to understand the difference between energy capacity and power output in a battery.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'How Long Can a Home Battery Actually Power Your House?',
        slug: 'how-long-can-battery-power-house',
        primaryKeyword: 'how long can a solar battery power a house',
        secondaryKeywords: ['home battery backup duration', 'battery runtime during outage'],
        searchIntent: 'A homeowner wants realistic runtime estimates for a battery under typical household loads during an outage.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'What Size Solar Battery Do You Need? A Sizing Walkthrough',
        slug: 'solar-battery-sizing-guide',
        primaryKeyword: 'what size solar battery do i need',
        secondaryKeywords: ['solar battery sizing', 'how many kwh battery for home'],
        searchIntent: 'A buyer wants a step-by-step method to translate their usage and goals into a battery capacity in kWh.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Sizing a Battery for Essential Loads Only',
        slug: 'battery-sizing-essential-loads',
        primaryKeyword: 'battery backup for essential loads',
        secondaryKeywords: ['essential load battery sizing', 'backup fridge and wifi battery size'],
        searchIntent: 'A budget-conscious homeowner wants to size a smaller battery that covers only the fridge, lights, internet, and other must-run circuits.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Whole-Home vs Partial Backup: Choosing What Stays On',
        slug: 'whole-home-vs-partial-backup',
        primaryKeyword: 'whole home vs partial battery backup',
        secondaryKeywords: ['whole house battery backup', 'partial home backup solar'],
        searchIntent: 'A homeowner deciding on a backup scope wants the cost, hardware, and lifestyle trade-offs between backing up everything and just key circuits.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'What Actually Happens When the Grid Goes Down and You Have a Battery',
        slug: 'solar-battery-during-power-outage',
        primaryKeyword: 'solar battery during power outage',
        secondaryKeywords: ['does solar battery work in blackout', 'battery backup switchover time'],
        searchIntent: 'A homeowner wants to know the moment-by-moment behavior of a solar-plus-battery system when the utility power cuts out.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Can a Home Battery Run Your Air Conditioner?',
        slug: 'can-battery-run-air-conditioner',
        primaryKeyword: 'can a solar battery run an air conditioner',
        secondaryKeywords: ['battery backup for ac unit', 'running large loads on home battery'],
        searchIntent: 'A homeowner in a hot climate wants to know whether a battery can start and sustain central air and other heavy loads.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Home Batteries Without Solar Panels: Who They Make Sense For',
        slug: 'home-battery-without-solar',
        primaryKeyword: 'home battery without solar',
        secondaryKeywords: ['standalone battery storage', 'grid charged home battery'],
        searchIntent: 'A homeowner without panels wants to know if a grid-charged battery is useful for outages or time-of-use rates on its own.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Standby Generator or Home Battery? A Backup Power Showdown',
        slug: 'generator-vs-home-battery',
        primaryKeyword: 'generator vs battery backup',
        secondaryKeywords: ['whole house generator vs battery', 'standby generator vs solar battery'],
        searchIntent: 'A homeowner planning for outages wants a side-by-side comparison of generators and batteries on fuel, noise, runtime, and upkeep.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Home Battery vs Portable Power Station for Outage Protection',
        slug: 'home-battery-vs-portable-power-station',
        primaryKeyword: 'home battery vs portable power station',
        secondaryKeywords: ['portable power station for home backup', 'installed battery vs portable battery'],
        searchIntent: 'A renter or light user wants to know when a portable power station is enough and when an installed home battery is the better tool.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'LFP vs NMC Home Batteries: The Chemistry Choice That Matters',
        slug: 'lfp-vs-nmc-home-batteries',
        primaryKeyword: 'lfp vs nmc battery',
        secondaryKeywords: ['lithium iron phosphate vs nmc', 'best battery chemistry for home storage'],
        searchIntent: 'A technically minded buyer wants to compare LFP and NMC chemistries on safety, lifespan, density, and temperature behavior.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Solar Battery Lifespan: Cycles, Years, and What Wears Them Out',
        slug: 'solar-battery-lifespan-cycles',
        primaryKeyword: 'solar battery lifespan',
        secondaryKeywords: ['how long do solar batteries last', 'battery cycle life explained'],
        searchIntent: 'An owner or shopper wants to know how many years and cycles a home battery realistically lasts and what accelerates degradation.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Depth of Discharge, Explained for Home Battery Owners',
        slug: 'battery-depth-of-discharge',
        primaryKeyword: 'battery depth of discharge',
        secondaryKeywords: ['what is dod battery', 'usable capacity solar battery'],
        searchIntent: 'A reader wants to understand what depth of discharge means, how it relates to usable capacity, and why spec sheets quote it.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Round-Trip Efficiency: The Hidden Number in Battery Specs',
        slug: 'battery-round-trip-efficiency',
        primaryKeyword: 'battery round trip efficiency',
        secondaryKeywords: ['solar battery efficiency losses', 'how much energy do batteries lose'],
        searchIntent: 'A detail-oriented shopper wants to know how much energy is lost charging and discharging a battery and why the number varies.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'AC-Coupled vs DC-Coupled Batteries: Which Architecture Fits Your Home?',
        slug: 'ac-vs-dc-coupled-battery',
        primaryKeyword: 'ac coupled vs dc coupled battery',
        secondaryKeywords: ['ac coupling solar battery', 'dc coupled storage explained'],
        searchIntent: 'A buyer comparing quotes wants to understand the efficiency, cost, and retrofit implications of AC versus DC coupling.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Adding a Battery to Existing Solar vs Installing Both Together',
        slug: 'battery-retrofit-vs-new-install',
        primaryKeyword: 'add battery to existing solar',
        secondaryKeywords: ['battery retrofit solar system', 'install solar and battery together'],
        searchIntent: 'An existing solar owner wants to know how retrofitting a battery differs in hardware and hassle from bundling storage into a new install.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Stacking Multiple Home Batteries: How Expansion Really Works',
        slug: 'stacking-multiple-home-batteries',
        primaryKeyword: 'stacking solar batteries',
        secondaryKeywords: ['multiple home batteries', 'expandable battery storage'],
        searchIntent: 'A homeowner wants to know whether they can add battery units over time and what limits stacking capacity and power.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Garage, Basement, or Outside? Where Your Battery Should Live',
        slug: 'solar-battery-placement-temperature',
        primaryKeyword: 'solar battery placement',
        secondaryKeywords: ['can solar batteries be installed outside', 'battery temperature range home'],
        searchIntent: 'A homeowner wants guidance on where to mount a battery, considering temperature, code clearances, and convenience.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Home Battery Safety: UL 9540, Fire Codes, and Setback Rules',
        slug: 'home-battery-safety-codes',
        primaryKeyword: 'home battery safety standards',
        secondaryKeywords: ['ul 9540 explained', 'solar battery fire safety'],
        searchIntent: 'A safety-conscious homeowner wants to understand the certifications and code rules that govern residential battery installations.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Backup-Only, Self-Consumption, or Time-of-Use: Battery Modes Decoded',
        slug: 'solar-battery-operating-modes',
        primaryKeyword: 'solar battery modes',
        secondaryKeywords: ['self consumption mode battery', 'backup reserve setting solar'],
        searchIntent: 'A new battery owner wants to understand the operating modes in their app and which setting matches their goals.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Charging Cheap, Discharging Smart: Off-Peak Battery Arbitrage',
        slug: 'battery-time-of-use-arbitrage',
        primaryKeyword: 'battery time of use arbitrage',
        secondaryKeywords: ['charge battery off peak rates', 'tou rate battery strategy'],
        searchIntent: 'A homeowner on time-of-use rates wants to learn how a battery can shift cheap off-peak power into expensive evening hours.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'How Batteries Change the Net Metering Math',
        slug: 'solar-battery-net-metering',
        primaryKeyword: 'solar battery and net metering',
        secondaryKeywords: ['net metering with battery storage', 'self consumption vs net metering'],
        searchIntent: 'A solar owner wants to understand when storing energy beats exporting it under different net metering compensation structures.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Virtual Power Plants: Sharing Your Battery With the Grid',
        slug: 'virtual-power-plant-home-battery',
        primaryKeyword: 'virtual power plant home battery',
        secondaryKeywords: ['what is a vpp program', 'battery grid services for homeowners'],
        searchIntent: 'A battery owner wants to understand how virtual power plant programs work and what enrolling means for control and compensation.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Grid-Tied With Battery vs Off-Grid: How Far Can Storage Take You?',
        slug: 'grid-tied-battery-vs-off-grid',
        primaryKeyword: 'grid tied with battery vs off grid',
        secondaryKeywords: ['can a battery take you off grid', 'off grid solar battery requirements'],
        searchIntent: 'An independence-minded homeowner wants to know the real gap between a battery-backed grid-tied home and a true off-grid setup.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Reading a Solar Battery Warranty: Cycles, Throughput, and Fine Print',
        slug: 'solar-battery-warranty-terms',
        primaryKeyword: 'solar battery warranty',
        secondaryKeywords: ['battery throughput warranty explained', 'end of warranty capacity battery'],
        searchIntent: 'A buyer comparing products wants to decode warranty terms like cycle limits, throughput caps, and guaranteed end capacity.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Do Solar Batteries Need Maintenance? A Realistic Owner Checklist',
        slug: 'solar-battery-maintenance-basics',
        primaryKeyword: 'solar battery maintenance',
        secondaryKeywords: ['home battery upkeep', 'battery firmware updates and checkups'],
        searchIntent: 'An owner wants to know what routine care a modern lithium home battery actually needs over its life.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Your EV as a Home Backup Battery: Vehicle-to-Home Basics',
        slug: 'ev-vehicle-to-home-backup',
        primaryKeyword: 'vehicle to home backup power',
        secondaryKeywords: ['v2h explained', 'ev powering your house'],
        searchIntent: 'An EV owner wants to understand what hardware and wiring it takes to use a car battery as backup power for the house.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'What Drives Home Battery Prices? Cells, Capacity, and Installation',
        slug: 'what-drives-home-battery-prices',
        primaryKeyword: 'home battery price factors',
        secondaryKeywords: ['why are solar batteries expensive', 'battery storage cost breakdown'],
        searchIntent: 'A shopper wants to understand the components and labor behind a battery quote rather than a verdict on whether to buy.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'When a Solar Battery Dies: End of Life, Recycling, and Second Uses',
        slug: 'solar-battery-recycling-end-of-life',
        primaryKeyword: 'solar battery recycling',
        secondaryKeywords: ['what happens to old home batteries', 'battery second life uses'],
        searchIntent: 'A sustainability-minded owner wants to know what happens to a home battery after it degrades and how recycling works.',
        relatedCalculators: ['solar-battery-calculator'],
      },
    ],
  },
  {
    cluster: 'Inverters and system components',
    category: 'Inverters & Components',
    entries: [
      {
        title: "The Solar Inverter, Explained: Your System's Hardest-Working Box",
        slug: 'what-does-a-solar-inverter-do',
        primaryKeyword: 'what does a solar inverter do',
        secondaryKeywords: ['solar inverter basics', 'how inverters convert dc to ac'],
        searchIntent: 'A new solar shopper wants a foundational explanation of what an inverter does and why every system needs one.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
        pillar: true,
      },
      {
        title: 'String Inverters vs Microinverters: The Real Trade-Offs',
        slug: 'string-vs-microinverters',
        primaryKeyword: 'string inverter vs microinverter',
        secondaryKeywords: ['microinverters pros and cons', 'which inverter type is best'],
        searchIntent: 'A buyer comparing quotes wants an honest breakdown of string and microinverter architectures for shade, cost, and reliability.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Power Optimizers: The Middle Path Between String and Micro',
        slug: 'solar-power-optimizers',
        primaryKeyword: 'solar power optimizers',
        secondaryKeywords: ['dc optimizers explained', 'optimizer vs microinverter'],
        searchIntent: 'A shopper who has heard of optimizers wants to know how they work and when they beat plain string or microinverter setups.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Hybrid Inverters: One Box for Solar and Storage',
        slug: 'hybrid-solar-inverters',
        primaryKeyword: 'hybrid solar inverter',
        secondaryKeywords: ['battery ready inverter', 'hybrid vs standard inverter'],
        searchIntent: 'A homeowner planning for future batteries wants to know what a hybrid inverter does and whether to pay for one up front.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Why Grid-Tied Solar Shuts Off in a Blackout: Anti-Islanding 101',
        slug: 'anti-islanding-solar-shutoff',
        primaryKeyword: 'why does solar shut off during a power outage',
        secondaryKeywords: ['anti islanding explained', 'grid tied inverter blackout behavior'],
        searchIntent: 'A surprised solar owner wants to understand why panels stop powering the house in an outage and what hardware changes that.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'MPPT: How Inverters Squeeze Every Watt From Your Panels',
        slug: 'mppt-explained',
        primaryKeyword: 'what is mppt solar',
        secondaryKeywords: ['maximum power point tracking explained', 'mppt channels inverter'],
        searchIntent: 'A technically curious reader wants to understand maximum power point tracking and why MPPT channel count matters for roof layouts.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Inverter Sizing and the DC-to-AC Ratio Sweet Spot',
        slug: 'inverter-sizing-dc-ac-ratio',
        primaryKeyword: 'dc to ac ratio solar',
        secondaryKeywords: ['inverter sizing guide', 'oversizing solar array vs inverter'],
        searchIntent: 'A quote-comparing homeowner wants to know why arrays are sized larger than inverters and what ratio is reasonable.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
      {
        title: "Inverter Clipping: When Lost Solar Power Is Actually Fine",
        slug: 'inverter-clipping',
        primaryKeyword: 'inverter clipping',
        secondaryKeywords: ['solar clipping losses', 'flat top solar production curve'],
        searchIntent: 'A solar owner who noticed a flat-topped production curve wants to know what clipping is and how much energy it really costs.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'CEC vs Peak Efficiency: Reading Inverter Ratings Honestly',
        slug: 'inverter-cec-vs-peak-efficiency',
        primaryKeyword: 'cec weighted efficiency inverter',
        secondaryKeywords: ['inverter efficiency curve', 'peak vs weighted inverter efficiency'],
        searchIntent: 'A spec-sheet reader wants to know the difference between peak and CEC-weighted efficiency and which number predicts real output.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'How to Read an Inverter Datasheet Like an Installer',
        slug: 'how-to-read-inverter-datasheet',
        primaryKeyword: 'inverter datasheet explained',
        secondaryKeywords: ['inverter spec sheet terms', 'understanding inverter specifications'],
        searchIntent: 'A diligent buyer wants a guided tour of the key fields on an inverter datasheet so they can compare models confidently.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: "Inverter Lifespan: The Component You'll Likely Replace First",
        slug: 'solar-inverter-lifespan-replacement',
        primaryKeyword: 'solar inverter lifespan',
        secondaryKeywords: ['how long do inverters last', 'inverter replacement planning'],
        searchIntent: 'A long-term planner wants to know how many years each inverter type lasts and how to budget for a mid-life replacement.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Inverter Warranties Compared: 10, 12, or 25 Years?',
        slug: 'solar-inverter-warranties',
        primaryKeyword: 'solar inverter warranty',
        secondaryKeywords: ['inverter warranty extension', 'microinverter vs string warranty length'],
        searchIntent: 'A buyer wants to understand why inverter warranty lengths vary so much by type and what the coverage actually includes.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar Monitoring Systems: What Your App Is Really Telling You',
        slug: 'solar-monitoring-systems',
        primaryKeyword: 'solar monitoring system',
        secondaryKeywords: ['solar production monitoring app', 'consumption monitoring solar'],
        searchIntent: 'A new system owner wants to learn what the monitoring app measures and which numbers signal a healthy or ailing array.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Panel-Level vs System-Level Monitoring: Do You Need the Detail?',
        slug: 'panel-level-vs-system-monitoring',
        primaryKeyword: 'panel level monitoring solar',
        secondaryKeywords: ['module level monitoring worth it', 'system level solar monitoring'],
        searchIntent: 'A shopper wants to decide whether per-panel visibility justifies the hardware that provides it or if whole-system data is enough.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Rapid Shutdown Rules: Why Your Solar Needs a Kill Switch',
        slug: 'solar-rapid-shutdown',
        primaryKeyword: 'solar rapid shutdown requirements',
        secondaryKeywords: ['nec rapid shutdown explained', 'module level shutdown devices'],
        searchIntent: 'A homeowner who saw rapid shutdown gear on a quote wants to know what the code requires and how the equipment works.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'From Roof to Breaker: Solar Wiring and Conduit Basics',
        slug: 'solar-wiring-conduit-basics',
        primaryKeyword: 'solar panel wiring basics',
        secondaryKeywords: ['solar conduit runs explained', 'how solar connects to electrical panel'],
        searchIntent: 'A homeowner wants a simple map of how power travels from panels through conduit to the main breaker panel.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Critical Load Panels: Wiring Your Home for Backup Priorities',
        slug: 'critical-load-panel',
        primaryKeyword: 'critical load panel',
        secondaryKeywords: ['backup subpanel solar', 'protected loads panel explained'],
        searchIntent: 'A battery-curious homeowner wants to understand what a critical load subpanel is and which circuits belong on it.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Smart Electrical Panels: Circuit-Level Control for Solar Homes',
        slug: 'smart-electrical-panels-solar',
        primaryKeyword: 'smart electrical panel',
        secondaryKeywords: ['smart panel vs critical load panel', 'circuit level energy management'],
        searchIntent: 'A tech-forward homeowner wants to know how smart panels manage circuits dynamically and when they replace a traditional subpanel.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Surge Protection for Solar: SPDs, Lightning, and Grid Spikes',
        slug: 'solar-surge-protection',
        primaryKeyword: 'solar surge protection',
        secondaryKeywords: ['spd for solar system', 'lightning protection solar panels'],
        searchIntent: 'A homeowner in a storm-prone area wants to know how surge protective devices shield inverters and panels from voltage spikes.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Inverter Noise and Placement: Garage, Exterior Wall, or Utility Room?',
        slug: 'inverter-noise-placement',
        primaryKeyword: 'solar inverter noise',
        secondaryKeywords: ['where to install solar inverter', 'inverter humming sound normal'],
        searchIntent: 'A homeowner planning an install wants to know how loud inverters get and where to mount one to avoid heat and annoyance.',
        relatedCalculators: ['solar-panel-calculator'],
      },
    ],
  },
];
