// SEO topic plan — batch I (expansion 300 -> 500)
// SunMetricLab (sunmetriclab.com) — US-focused solar calculators + blog.
// Plan only: no articles are written here. Each entry defines a future post.
//
// Rules honored:
// - Five expansion clusters, 8 entries each = 40 total.
// - Every slug, primaryKeyword, and searchIntent is new (no case-insensitive
//   overlap with the 300 existing content-plan.json entries).
// - New long-tail angles only: fresh kWh tiers and kW outputs, future-load
//   sizing, partial-shade sizing, per-appliance usage, all-electric homes,
//   base vs peak load, specific roof materials/shapes, warranty coordination,
//   remove-and-reinstall, DIY shade measurement, install-day logistics,
//   inspection/interconnection specifics, and lifecycle maintenance angles.
// - relatedCalculators only from the approved calculator ids.
// - Angles are structural/technical so articles stay time-stable (no claims
//   tied to specific current program dollar values or rates).

export const clusters = [
  {
    cluster: 'Sizing (expansion)',
    category: 'System Sizing',
    entries: [
      {
        title: 'How Many Solar Panels Do You Need for 800 kWh a Month?',
        slug: 'solar-panels-800-kwh-per-month',
        primaryKeyword: 'solar panels for 800 kwh per month',
        secondaryKeywords: ['800 kwh solar system size', 'how many panels for 800 kwh'],
        searchIntent: 'A modest-usage household wants the panel count and kW size that offsets 800 kWh of monthly consumption.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
      },
      {
        title: 'Sizing Solar for a 1,200 kWh Monthly Electric Bill',
        slug: 'solar-panels-1200-kwh-per-month',
        primaryKeyword: 'solar panels for 1200 kwh per month',
        secondaryKeywords: ['1200 kwh solar system', 'how big a system for 1200 kwh'],
        searchIntent: 'An average-to-higher-usage home wants to translate a 1,200 kWh monthly bill into a target array size.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Panels for 2,500 kWh a Month: How Big Should You Go?',
        slug: 'solar-panels-2500-kwh-per-month',
        primaryKeyword: 'solar panels for 2500 kwh per month',
        secondaryKeywords: ['2500 kwh solar system size', 'large home solar sizing'],
        searchIntent: 'A high-consumption household wants the array size and panel count needed to cover a heavy 2,500 kWh monthly load.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
      },
      {
        title: 'What a 9kW Solar System Produces and Who It Fits',
        slug: '9kw-solar-system',
        primaryKeyword: '9kw solar system output',
        secondaryKeywords: ['9kw solar system panels', '9 kw solar production per year'],
        searchIntent: 'Shoppers quoted a 9 kW array want its yearly generation and the household usage profile it comfortably serves.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
      {
        title: '11kW Solar Systems: Panel Count, Output, and Ideal Homes',
        slug: '11kw-solar-system',
        primaryKeyword: '11kw solar system how many panels',
        secondaryKeywords: ['11kw solar system output', '11 kw solar system size'],
        searchIntent: 'Buyers comparing larger quotes want the panel count and annual production behind an 11 kW system.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'How Much Power Does a 12kW Solar System Really Make?',
        slug: '12kw-solar-system',
        primaryKeyword: '12kw solar system production',
        secondaryKeywords: ['12kw solar system output', '12 kw solar how many panels'],
        searchIntent: 'Owners of large or all-electric homes want a realistic annual output figure for a 12 kW array before committing.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
      {
        title: "Sizing Your Solar Array for an EV You Haven't Bought Yet",
        slug: 'sizing-solar-for-future-ev',
        primaryKeyword: 'sizing solar for a future ev',
        secondaryKeywords: ['future-proof solar for ev', 'add headroom for electric car'],
        searchIntent: 'A homeowner planning to buy an electric car later wants to build charging headroom into the system they install today.',
        relatedCalculators: ['ev-charging-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Sizing Solar When Shade Takes Part of Your Roof Off the Table',
        slug: 'sizing-solar-with-partial-shade',
        primaryKeyword: 'sizing solar system with partial shade',
        secondaryKeywords: ['solar sizing limited roof space', 'partial shade panel count'],
        searchIntent: 'A homeowner whose usable roof is reduced by shade wants to size a system around the panels that will actually perform.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
    ],
  },
  {
    cluster: 'Electricity usage (expansion)',
    category: 'Electricity Usage',
    entries: [
      {
        title: 'How Much Electricity Does a Clothes Dryer Actually Use?',
        slug: 'clothes-dryer-electricity-usage',
        primaryKeyword: 'how much electricity does a dryer use',
        secondaryKeywords: ['electric dryer kwh per load', 'clothes dryer energy usage'],
        searchIntent: 'A homeowner wants per-load and monthly kWh figures for an electric clothes dryer to see its share of the bill.',
        relatedCalculators: ['electricity-bill-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Electric Oven and Stove Energy Use, Broken Down by the kWh',
        slug: 'electric-oven-stove-electricity-usage',
        primaryKeyword: 'how much electricity does an electric oven use',
        secondaryKeywords: ['electric stove kwh per hour', 'cooking electricity usage'],
        searchIntent: 'A cook wants realistic kWh figures for an electric oven and stovetop so they can gauge how much cooking adds to usage.',
        relatedCalculators: ['electricity-bill-calculator'],
      },
      {
        title: 'How Much Electricity Does a Dishwasher Use per Cycle?',
        slug: 'dishwasher-electricity-usage',
        primaryKeyword: 'how much electricity does a dishwasher use',
        secondaryKeywords: ['dishwasher kwh per cycle', 'dishwasher energy consumption'],
        searchIntent: 'A homeowner wants per-cycle and monthly consumption for a dishwasher, including the hidden cost of heated drying.',
        relatedCalculators: ['electricity-bill-calculator'],
      },
      {
        title: 'Hot Tubs and Your Power Bill: What They Really Cost to Run',
        slug: 'hot-tub-electricity-usage',
        primaryKeyword: 'how much electricity does a hot tub use',
        secondaryKeywords: ['hot tub kwh per month', 'spa electricity consumption'],
        searchIntent: 'A spa owner wants to quantify how much a hot tub adds to monthly usage and how climate and settings swing that figure.',
        relatedCalculators: ['electricity-bill-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'How Much Electricity a Well Pump Uses and Why It Spikes',
        slug: 'well-pump-electricity-usage',
        primaryKeyword: 'how much electricity does a well pump use',
        secondaryKeywords: ['well pump kwh usage', 'submersible pump energy cost'],
        searchIntent: 'A rural homeowner wants to understand a well pump’s intermittent but heavy draw and its impact on monthly kWh.',
        relatedCalculators: ['electricity-bill-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Space Heaters and Electricity: The True Cost of Plug-In Heat',
        slug: 'space-heater-electricity-usage',
        primaryKeyword: 'space heater electricity usage',
        secondaryKeywords: ['space heater kwh per hour', 'portable heater energy cost'],
        searchIntent: 'A homeowner leaning on portable plug-in heaters wants to measure how much those 1,500-watt units inflate winter usage.',
        relatedCalculators: ['electricity-bill-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'What Powers an All-Electric Home and How Many kWh It Takes',
        slug: 'all-electric-home-electricity-usage',
        primaryKeyword: 'all electric home electricity usage',
        secondaryKeywords: ['all electric house kwh per month', 'no gas home energy use'],
        searchIntent: 'A homeowner going gas-free wants a realistic total-kWh picture once heating, hot water, and cooking are all electric.',
        relatedCalculators: ['electricity-bill-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Base Load vs Peak Load: Reading the Shape of Your Power Use',
        slug: 'base-load-vs-peak-load-home',
        primaryKeyword: 'base load vs peak load home electricity',
        secondaryKeywords: ['household base load explained', 'peak demand home energy'],
        searchIntent: 'A data-minded homeowner wants to separate their always-on base load from short peak spikes and why the distinction matters for solar and storage.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-battery-calculator'],
      },
    ],
  },
  {
    cluster: 'Roof & shading (expansion)',
    category: 'Roof & Shading',
    entries: [
      {
        title: 'Can You Put Solar Panels on a Wood Shake Roof?',
        slug: 'solar-panels-wood-shake-roof',
        primaryKeyword: 'solar panels on wood shake roof',
        secondaryKeywords: ['cedar shake roof solar', 'wood shingle roof solar mounting'],
        searchIntent: 'An owner of a wood shake or cedar roof wants to know whether panels can mount safely and what fire and durability issues apply.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Panels on a Slate Roof: What Makes It Tricky',
        slug: 'solar-panels-slate-roof',
        primaryKeyword: 'solar panels on slate roof',
        secondaryKeywords: ['slate roof solar mounting', 'solar on slate tiles'],
        searchIntent: 'A slate-roof owner wants to understand the specialized hooks, breakage risk, and added labor that mounting on brittle slate demands.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Who Pays if Solar Panels Cause a Roof Leak?',
        slug: 'solar-and-roof-warranty-coordination',
        primaryKeyword: 'solar roof leak responsibility',
        secondaryKeywords: ['who fixes solar roof leak', 'roofer vs installer warranty'],
        searchIntent: 'A homeowner wants to know how to coordinate roofer and solar-installer warranties so a future leak does not fall through the cracks.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Removing and Reinstalling Solar Panels for a New Roof',
        slug: 'remove-reinstall-solar-for-roof-replacement',
        primaryKeyword: 'remove and reinstall solar panels for roof',
        secondaryKeywords: ['solar removal for reroofing', 'detach and reset solar cost'],
        searchIntent: 'An owner who needs to re-roof under an existing array wants to know how detach-and-reset works and what it typically costs.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How to Measure Shade on Your Own Roof Before Going Solar',
        slug: 'measure-shade-on-your-roof',
        primaryKeyword: 'how to measure shade for solar',
        secondaryKeywords: ['diy solar shade assessment', 'check roof shading yourself'],
        searchIntent: 'A DIY-minded homeowner wants simple methods and apps for gauging how much shade their roof gets across the day and seasons.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Chimney Shadows and Solar Panels: Planning Around the Problem',
        slug: 'chimney-shade-solar-panels',
        primaryKeyword: 'chimney shading solar panels',
        secondaryKeywords: ['chimney shadow on solar array', 'panel layout around chimney'],
        searchIntent: 'A homeowner with a chimney near the array wants to understand its moving shadow and how designers lay panels out to dodge it.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Flat vs Pitched Roofs for Solar: The Real Trade-Offs',
        slug: 'flat-vs-pitched-roof-solar',
        primaryKeyword: 'flat vs pitched roof solar',
        secondaryKeywords: ['flat versus sloped roof solar', 'tilt racking vs flush mount'],
        searchIntent: 'A homeowner comparing roof types wants an honest look at how flat and pitched roofs differ in output, cost, and layout for solar.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Which Roof Shapes Work Best for Solar Panels?',
        slug: 'roof-shape-solar-suitability',
        primaryKeyword: 'best roof shape for solar',
        secondaryKeywords: ['gable vs hip roof solar', 'roof geometry for solar panels'],
        searchIntent: 'A homeowner wants to know how gable, hip, gambrel, and other roof shapes affect how many panels fit and how well they produce.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
    ],
  },
  {
    cluster: 'Installation (expansion)',
    category: 'Installation',
    entries: [
      {
        title: 'Do You Need to Be Home When Solar Panels Are Installed?',
        slug: 'do-i-need-to-be-home-solar-install',
        primaryKeyword: 'do i need to be home for solar installation',
        secondaryKeywords: ['solar install homeowner presence', 'be present for solar install'],
        searchIntent: 'A homeowner with a booked install date wants to know whether they must be present and how to prepare pets, parking, and access.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Will Your Power Be Off During a Solar Installation?',
        slug: 'power-shutoff-during-solar-install',
        primaryKeyword: 'will power be off during solar installation',
        secondaryKeywords: ['electricity shut off solar install', 'power interruption solar day'],
        searchIntent: 'A homeowner wants to know when and for how long the crew must cut power during the install so they can plan around the outage.',
        relatedCalculators: ['solar-panel-cost-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Can Solar Panels Be Installed in Winter? What to Expect',
        slug: 'installing-solar-in-winter',
        primaryKeyword: 'can solar panels be installed in winter',
        secondaryKeywords: ['winter solar installation', 'installing solar in cold weather'],
        searchIntent: 'A homeowner considering a cold-season install wants to know how snow, frozen roofs, and short days affect scheduling and safety.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'How Weather Delays a Solar Installation and What to Do',
        slug: 'solar-install-weather-delays',
        primaryKeyword: 'solar installation weather delays',
        secondaryKeywords: ['rain delay solar install', 'weather postpone solar installation'],
        searchIntent: 'A homeowner whose install date is threatened by weather wants to know which conditions force a reschedule and how crews handle it.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'What Happens When Your Solar Install Fails Inspection',
        slug: 'failed-solar-inspection',
        primaryKeyword: 'solar failed inspection',
        secondaryKeywords: ['solar install failed inspection reasons', 'reinspection after solar failure'],
        searchIntent: 'A homeowner whose system did not pass the city or utility inspection wants to know common failure reasons and how re-inspection works.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Where Installers Run Conduit and Wiring for Your Solar',
        slug: 'solar-conduit-wiring-routing',
        primaryKeyword: 'solar panel conduit routing',
        secondaryKeywords: ['solar wiring run options', 'interior vs exterior solar conduit'],
        searchIntent: 'A homeowner concerned about appearance wants to know where conduit and wiring get routed and whether interior runs are possible.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "The Net Meter Swap: The Utility's Part of Going Solar",
        slug: 'net-meter-installation',
        primaryKeyword: 'net meter installation for solar',
        secondaryKeywords: ['bidirectional meter swap solar', 'utility meter change for solar'],
        searchIntent: 'A new solar owner wants to understand the utility’s bidirectional meter swap, when it happens, and why it gates permission to operate.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Setting Up Your Solar Monitoring App After Installation',
        slug: 'solar-monitoring-setup',
        primaryKeyword: 'how to set up solar monitoring',
        secondaryKeywords: ['register solar monitoring app', 'connect inverter to wifi'],
        searchIntent: 'A brand-new solar owner wants a walkthrough for registering the monitoring app and confirming every panel reports correctly.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-cost-calculator'],
      },
    ],
  },
  {
    cluster: 'Maintenance & lifespan (expansion)',
    category: 'Maintenance & Lifespan',
    entries: [
      {
        title: 'How Often Should You Really Clean Solar Panels?',
        slug: 'solar-cleaning-frequency',
        primaryKeyword: 'how often to clean solar panels',
        secondaryKeywords: ['solar cleaning schedule by climate', 'how frequently clean solar'],
        searchIntent: 'An owner wants a cleaning frequency guide that adapts to their climate, dust, pollen, and rainfall rather than a one-size rule.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Critter Guards for Solar Panels: Options and Costs',
        slug: 'solar-panel-critter-guards',
        primaryKeyword: 'solar panel critter guard cost',
        secondaryKeywords: ['bird netting for solar panels', 'squirrel guard solar installation'],
        searchIntent: 'A homeowner wants to compare mesh critter guards and bird netting, their installed cost, and how well each keeps animals out.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How to File a Homeowners Insurance Claim for Solar Damage',
        slug: 'filing-solar-insurance-claim',
        primaryKeyword: 'how to file a solar insurance claim',
        secondaryKeywords: ['solar damage insurance claim steps', 'claim for storm-damaged panels'],
        searchIntent: 'An owner with storm or impact damage wants a step-by-step process for documenting and filing a homeowners claim on their array.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Filing a Solar Panel Warranty Claim Without the Runaround',
        slug: 'filing-solar-warranty-claim',
        primaryKeyword: 'how to file a solar panel warranty claim',
        secondaryKeywords: ['solar warranty claim process', 'manufacturer solar claim steps'],
        searchIntent: 'An owner with a failing panel or inverter wants to know how to invoke the manufacturer or workmanship warranty and what proof they need.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'When to Budget for a Solar Inverter Replacement',
        slug: 'inverter-replacement-cost-timing',
        primaryKeyword: 'when to replace solar inverter',
        secondaryKeywords: ['solar inverter replacement cost', 'inverter lifespan budgeting'],
        searchIntent: 'A long-term owner wants to know when inverters typically need replacing and how to set money aside for that mid-life expense.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: "How to Track Your Solar Panels' Real Degradation Over Time",
        slug: 'track-solar-degradation',
        primaryKeyword: 'how to track solar panel degradation',
        secondaryKeywords: ['measure solar output decline', 'compare solar production year over year'],
        searchIntent: 'A data-driven owner wants a method for measuring their own array’s year-over-year output loss and spotting abnormal decline early.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'What Happens to Solar Panels at the End of Their Life?',
        slug: 'solar-system-end-of-life',
        primaryKeyword: 'solar system end of life',
        secondaryKeywords: ['decommissioning solar panels', 'removing an old solar system'],
        searchIntent: 'An owner nearing the end of their system’s service life wants to understand decommissioning, removal, and the choices at end of life.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'What Solar Panel Maintenance Actually Costs Each Year',
        slug: 'solar-maintenance-cost-per-year',
        primaryKeyword: 'solar maintenance cost per year',
        secondaryKeywords: ['annual solar upkeep cost', 'lifetime solar operating cost'],
        searchIntent: 'A prospective or current owner wants a realistic annual operating-and-maintenance budget to fold into their long-term solar math.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
    ],
  },
];
