// SEO topic plan — SunMetricLab (sunmetriclab.com)
// Clusters B: Payback (20), System Sizing (25), Electricity Usage (20) = 65 entries.
// First entry of each cluster is the pillar. Entries ordered foundational -> advanced.
// relatedCalculators ids are restricted to:
//   solar-panel-calculator, solar-panel-cost-calculator, solar-roi-calculator,
//   solar-battery-calculator, how-many-solar-panels-do-i-need, solar-panel-size-calculator

export const clusters = [
  {
    cluster: 'Solar payback period',
    category: 'Payback',
    entries: [
      {
        title: 'Solar Payback, Explained: Every Factor That Moves the Number',
        slug: 'solar-payback-factors',
        primaryKeyword: 'what affects solar payback period',
        secondaryKeywords: ['solar payback period factors', 'factors that shorten solar payback', 'variables in solar payback'],
        searchIntent: 'Homeowners want a complete map of the variables that lengthen or shorten a solar payback period before they run their own numbers.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: true,
      },
      {
        title: 'Does a Bigger Solar System Pay Back Faster?',
        slug: 'solar-payback-by-system-size',
        primaryKeyword: 'solar payback by system size',
        secondaryKeywords: ['10kw solar system payback period', 'small vs large solar system payback'],
        searchIntent: 'Shoppers comparing quotes want to know whether choosing a larger or smaller system changes how quickly the investment breaks even.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Practical Ways to Shorten Your Solar Payback Period',
        slug: 'shorten-solar-payback-period',
        primaryKeyword: 'how to shorten solar payback period',
        secondaryKeywords: ['speed up solar payback', 'reduce solar break even time'],
        searchIntent: 'Homeowners already leaning toward solar want concrete levers they can pull to make the system pay for itself sooner.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Cash or Loan? How You Pay Changes When Solar Pays Back',
        slug: 'cash-vs-loan-solar-payback',
        primaryKeyword: 'solar loan vs cash payback',
        secondaryKeywords: ['financing solar payback period', 'solar loan break even'],
        searchIntent: 'Buyers deciding between paying upfront and financing want to see how interest and loan terms reshape the payback timeline.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'High Bills vs. Low Usage: Who Wins the Solar Payback Race?',
        slug: 'high-bill-vs-low-usage-payback',
        primaryKeyword: 'solar payback high electric bill',
        secondaryKeywords: ['is solar worth it with low electric bill', 'solar break even large electric bill'],
        searchIntent: 'Readers want to understand why the same system pays back much faster for a high-bill household than for a light electricity user.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Solar Payback Without the Tax Credit: Running the Numbers',
        slug: 'solar-payback-without-tax-credit',
        primaryKeyword: 'solar payback without tax credit',
        secondaryKeywords: ['solar break even no incentives', 'solar payback if not eligible for tax credit'],
        searchIntent: 'Homeowners who cannot claim the federal credit want an honest picture of how long payback takes without incentive help.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'Adding a Battery: What It Does to Your Solar Payback',
        slug: 'solar-battery-payback-impact',
        primaryKeyword: 'solar payback with battery',
        secondaryKeywords: ['battery storage payback period', 'does a battery extend solar break even'],
        searchIntent: 'Buyers considering storage want to quantify how much a battery stretches the combined system payback compared with panels alone.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Selling Before Break-Even: What Happens to Your Solar Payback If You Move',
        slug: 'solar-payback-if-you-move',
        primaryKeyword: 'solar payback if you sell your house',
        secondaryKeywords: ['moving before solar pays off', 'solar panels and home sale payback'],
        searchIntent: 'Owners who may relocate want to know whether resale value recovers the unrecouped cost of a system that has not yet paid back.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Rising Electricity Rates Are Quietly Shortening Solar Payback',
        slug: 'electricity-rate-increases-solar-payback',
        primaryKeyword: 'electricity rate increases solar payback',
        secondaryKeywords: ['utility rate inflation solar savings', 'solar payback with rising energy prices'],
        searchIntent: 'Readers want to see how assumed annual utility rate escalation changes payback math and why static-rate estimates run long.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Panel Degradation and Payback: Does Fading Output Matter?',
        slug: 'panel-degradation-solar-payback',
        primaryKeyword: 'solar panel degradation payback',
        secondaryKeywords: ['solar output decline over time', 'degradation rate effect on solar roi'],
        searchIntent: 'Detail-oriented buyers want to know whether the slow yearly loss of panel output meaningfully delays the break-even point.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'The Hidden Line Items: Maintenance and Inverter Costs in Payback Math',
        slug: 'maintenance-costs-solar-payback',
        primaryKeyword: 'solar maintenance costs payback',
        secondaryKeywords: ['inverter replacement payback impact', 'lifetime solar operating costs'],
        searchIntent: 'Homeowners want payback estimates that include realistic maintenance and mid-life inverter replacement rather than best-case math.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'Premium Panels vs. Budget Panels: Which Pays Back First?',
        slug: 'premium-vs-budget-panels-payback',
        primaryKeyword: 'premium vs budget solar panels payback',
        secondaryKeywords: ['cheap solar panels break even', 'high efficiency panels worth the cost'],
        searchIntent: 'Shoppers weighing tiered quotes want to know whether pricier equipment earns back its premium or just delays break-even.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'The Oversizing Penalty: When Extra Panels Slow Your Payback',
        slug: 'oversized-solar-system-payback',
        primaryKeyword: 'oversized solar system payback',
        secondaryKeywords: ['too many solar panels payback', 'diminishing returns large solar system'],
        searchIntent: 'Buyers pushed toward bigger quotes want to understand why capacity beyond their usage can stretch payback instead of improving it.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Why Leased Solar Has No Payback Period (and Why That Matters)',
        slug: 'solar-lease-payback',
        primaryKeyword: 'solar lease payback period',
        secondaryKeywords: ['ppa vs owning solar payback', 'do leased solar panels pay for themselves'],
        searchIntent: 'Readers offered a lease or PPA want to grasp why ownership-style payback math does not apply and how to evaluate those deals instead.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'DIY Solar Payback: Faster Break-Even, Bigger Risks',
        slug: 'diy-solar-payback',
        primaryKeyword: 'diy solar payback',
        secondaryKeywords: ['self install solar break even', 'diy vs professional solar payback'],
        searchIntent: 'Hands-on homeowners want to see how much a self-install shortens payback and which risks can erase that advantage.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'When Solar Doesn’t Pay Off: Honest Scenarios to Check First',
        slug: 'when-solar-doesnt-pay-off',
        primaryKeyword: 'when solar doesn’t pay off',
        secondaryKeywords: ['situations where solar is a bad investment', 'solar never breaks even'],
        searchIntent: 'Skeptical readers want a candid list of circumstances where the numbers genuinely fail so they can test their own situation.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'The Payback Math Mistakes Almost Every Solar Shopper Makes',
        slug: 'solar-payback-math-mistakes',
        primaryKeyword: 'solar payback calculation mistakes',
        secondaryKeywords: ['common errors solar break even math', 'why solar payback estimates are wrong'],
        searchIntent: 'Readers who have tried DIY spreadsheets want to spot the calculation errors that make payback look better or worse than reality.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'Three Homes, Three Payback Timelines: Worked Examples With Real Assumptions',
        slug: 'solar-payback-examples',
        primaryKeyword: 'solar payback examples',
        secondaryKeywords: ['solar break even scenarios', 'sample solar payback calculation'],
        searchIntent: 'Readers want fully worked payback scenarios with every assumption labeled so they can substitute their own inputs.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Simple vs. Discounted Payback: Which Number Should You Trust?',
        slug: 'simple-vs-discounted-payback',
        primaryKeyword: 'simple payback vs discounted payback solar',
        secondaryKeywords: ['discounted payback period solar', 'time value of money solar payback'],
        searchIntent: 'Analytical readers want to know how discounting future savings changes the payback figure and when the simple version misleads.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Beyond Payback: The NPV and IRR View of a Solar Investment',
        slug: 'solar-npv-irr',
        primaryKeyword: 'solar npv and irr',
        secondaryKeywords: ['net present value solar panels', 'internal rate of return solar investment'],
        searchIntent: 'Finance-minded homeowners want to evaluate solar the way they would any investment, using NPV and IRR instead of payback alone.',
        relatedCalculators: ['solar-roi-calculator'],
        pillar: false,
      },
    ],
  },
  {
    cluster: 'Solar panel sizing',
    category: 'System Sizing',
    entries: [
      {
        title: 'What Size Solar System Do You Actually Need?',
        slug: 'what-size-solar-system-do-i-need',
        primaryKeyword: 'what size solar system do i need',
        secondaryKeywords: ['solar system sizing guide', 'how to size a solar system', 'residential solar system size'],
        searchIntent: 'Homeowners starting research want a step-by-step framework for translating their electricity needs into a system size in kW.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
        pillar: true,
      },
      {
        title: 'kW vs. kWh: The Difference That Trips Up Every Solar Shopper',
        slug: 'kw-vs-kwh-solar',
        primaryKeyword: 'kw vs kwh difference',
        secondaryKeywords: ['kilowatt vs kilowatt hour explained', 'solar system kw vs kwh'],
        searchIntent: 'Beginners confused by quotes want a plain-English explanation of power versus energy and how each shows up in solar sizing.',
        relatedCalculators: ['solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'How Many Solar Panels Does the Average American Home Need?',
        slug: 'solar-panels-average-home',
        primaryKeyword: 'how many solar panels for average home',
        secondaryKeywords: ['typical home solar panel count', 'average residential solar array size'],
        searchIntent: 'Curious homeowners want a national benchmark panel count as a starting point before personalizing the estimate.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'What One Solar Panel Really Produces in a Day',
        slug: 'solar-panel-output-per-day',
        primaryKeyword: 'how much power does a solar panel produce per day',
        secondaryKeywords: ['solar panel daily kwh output', 'energy from one solar panel'],
        searchIntent: 'Readers want realistic per-panel daily production figures so they can sanity-check installer claims and their own math.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Solar Panel Dimensions: How Big Is a Panel, Really?',
        slug: 'solar-panel-dimensions',
        primaryKeyword: 'solar panel dimensions',
        secondaryKeywords: ['standard solar panel size and weight', 'residential vs commercial panel dimensions'],
        searchIntent: 'Homeowners visualizing an installation want the physical length, width, and weight of typical residential panels.',
        relatedCalculators: ['solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Is a 4 kW Solar System Enough for a Small Home?',
        slug: '4kw-solar-system',
        primaryKeyword: 'is a 4kw solar system enough',
        secondaryKeywords: ['4kw solar system production', '4kw solar panel count'],
        searchIntent: 'Owners of smaller or efficient homes want to know what a 4 kW array generates and whether it covers modest usage.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'The 5 kW Solar System: Production, Panel Count, and Who It Fits',
        slug: '5kw-solar-system',
        primaryKeyword: '5kw solar system output',
        secondaryKeywords: ['how many panels in a 5kw system', '5kw solar system kwh per day'],
        searchIntent: 'Shoppers quoted a 5 kW system want to know its typical output and which household usage profile it realistically serves.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: '7 kW of Solar: How Many Panels and What It Runs',
        slug: '7kw-solar-system',
        primaryKeyword: '7kw solar system how many panels',
        secondaryKeywords: ['7kw solar system daily production', 'what can a 7kw system power'],
        searchIntent: 'Buyers comparing mid-size quotes want the panel count, expected generation, and household fit of a 7 kW array.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'What an 8 kW Solar System Produces Month by Month',
        slug: '8kw-solar-system',
        primaryKeyword: '8kw solar system production',
        secondaryKeywords: ['8kw solar monthly output', '8kw system panel count'],
        searchIntent: 'Readers want a month-by-month production profile for an 8 kW system so they can compare it against their bill history.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Is 10 kW the Sweet Spot for Larger Homes?',
        slug: '10kw-solar-system',
        primaryKeyword: 'how much power does a 10kw solar system produce',
        secondaryKeywords: ['10kw solar system panel count', 'is a 10kw system too big'],
        searchIntent: 'Owners of larger houses want to know what 10 kW generates annually and whether that capacity matches heavy household usage.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Going Big: When a 15 kW Solar System Makes Sense',
        slug: '15kw-solar-system',
        primaryKeyword: '15kw solar system',
        secondaryKeywords: ['15kw solar production per year', 'who needs a 15kw solar system'],
        searchIntent: 'High-usage households want to know what a 15 kW array delivers and which situations genuinely justify that much capacity.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'Solar for a 2,000 Sq Ft House — and Why Square Footage Misleads',
        slug: 'solar-panels-2000-square-foot-house',
        primaryKeyword: 'solar panels for 2000 sq ft home',
        secondaryKeywords: ['solar system size by square footage', 'house size vs solar system size'],
        searchIntent: 'Readers searching by home size want a ballpark for a 2,000 sq ft house plus an explanation of why usage beats square footage for sizing.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'How Many Panels Cover 500 kWh a Month?',
        slug: 'solar-panels-500-kwh-per-month',
        primaryKeyword: 'solar panels for 500 kwh per month',
        secondaryKeywords: ['500 kwh solar system size', 'small usage solar panel count'],
        searchIntent: 'Light electricity users want the panel count and system size that offsets a 500 kWh monthly consumption.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Powering a Refrigerator With Solar: The Real Panel Math',
        slug: 'solar-panels-to-run-refrigerator',
        primaryKeyword: 'how many solar panels to run a refrigerator',
        secondaryKeywords: ['refrigerator solar power requirements', 'fridge kwh solar panels'],
        searchIntent: 'Readers want the appliance-level math for how much panel capacity a refrigerator demands around the clock.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'What It Takes to Run a Pool Pump on Solar',
        slug: 'solar-panels-for-pool-pump',
        primaryKeyword: 'solar panels to run a pool pump',
        secondaryKeywords: ['pool pump solar sizing', 'pool pump kwh solar panels'],
        searchIntent: 'Pool owners want to know how many panels a pump’s heavy seasonal load requires and how it changes system sizing.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'Sizing Solar for Central Air Conditioning',
        slug: 'solar-panels-for-air-conditioner',
        primaryKeyword: 'how many solar panels to run an air conditioner',
        secondaryKeywords: ['solar sizing for central ac', 'air conditioner solar power needs'],
        searchIntent: 'Homeowners in hot climates want to size an array around the summer AC load that dominates their usage.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Adding a Heat Pump? Resize Your Solar Array First',
        slug: 'solar-sizing-for-heat-pump',
        primaryKeyword: 'solar panels for heat pump',
        secondaryKeywords: ['heat pump solar system sizing', 'extra solar capacity for heat pump'],
        searchIntent: 'Households electrifying their heating want to know how much additional solar capacity a heat pump conversion demands.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'How Many Extra Panels Does an EV Really Require?',
        slug: 'solar-panels-for-ev-charging',
        primaryKeyword: 'how many solar panels to charge an ev',
        secondaryKeywords: ['solar sizing for electric car', 'ev charging solar system size'],
        searchIntent: 'Current and future EV owners want to translate annual driving miles into added panel count when sizing a system.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Turn 12 Months of Bills Into the Right System Size',
        slug: 'size-solar-from-annual-kwh',
        primaryKeyword: 'size solar system from annual kwh',
        secondaryKeywords: ['convert kwh usage to solar system size', 'solar sizing from electric bills'],
        searchIntent: 'Homeowners with a year of usage data want the exact arithmetic for converting annual kWh into a target system size.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'kWh per kW: The Production Yardstick Installers Use',
        slug: 'solar-production-per-kw',
        primaryKeyword: 'solar kwh per kw per year',
        secondaryKeywords: ['specific yield solar', 'solar production per kilowatt installed'],
        searchIntent: 'Readers comparing regions or quotes want to understand specific yield and how production per installed kW varies across the US.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Should You Aim for 100% Solar Offset?',
        slug: '100-percent-solar-offset',
        primaryKeyword: '100 percent solar offset',
        secondaryKeywords: ['full offset vs partial solar', 'what solar offset percentage is best'],
        searchIntent: 'Buyers want to weigh sizing for complete usage offset against the economics of a deliberately partial system.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-roi-calculator'],
        pillar: false,
      },
      {
        title: 'Oversizing vs. Undersizing: The Goldilocks Problem in Solar',
        slug: 'oversizing-vs-undersizing-solar',
        primaryKeyword: 'oversizing vs undersizing solar system',
        secondaryKeywords: ['right sizing a solar array', 'consequences of undersized solar'],
        searchIntent: 'Readers torn between quote sizes want the practical downsides of going too big or too small laid out side by side.',
        relatedCalculators: ['solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Planning to Add Panels Later? Size for Expansion Now',
        slug: 'adding-solar-panels-later',
        primaryKeyword: 'adding solar panels to existing system',
        secondaryKeywords: ['expandable solar system design', 'can i add more panels later'],
        searchIntent: 'Budget-conscious buyers want to know what to decide up front so a smaller starter system can grow without expensive rework.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-cost-calculator'],
        pillar: false,
      },
      {
        title: 'The Smallest Solar System Worth Installing',
        slug: 'smallest-solar-system-worth-installing',
        primaryKeyword: 'minimum solar system size',
        secondaryKeywords: ['is a small solar system worth it', 'smallest practical solar array'],
        searchIntent: 'Homeowners with limited budgets want to know the size floor below which fixed costs make an installation hard to justify.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Why Your 8 kW System Never Actually Produces 8 kW',
        slug: 'solar-system-losses',
        primaryKeyword: 'solar system losses explained',
        secondaryKeywords: ['solar derate factors', 'nameplate vs real solar output'],
        searchIntent: 'Advanced readers want to understand the stack of real-world losses separating nameplate capacity from delivered output.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
        pillar: false,
      },
    ],
  },
  {
    cluster: 'Electricity usage and bills',
    category: 'Electricity Usage',
    entries: [
      {
        title: 'How Much Electricity Does the Average American Home Use?',
        slug: 'average-home-electricity-usage',
        primaryKeyword: 'average home electricity usage',
        secondaryKeywords: ['average kwh per month us home', 'typical household electricity consumption', 'us home energy usage statistics'],
        searchIntent: 'Homeowners want national and regional usage benchmarks to judge whether their own consumption is high, low, or typical.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-calculator'],
        pillar: true,
      },
      {
        title: 'What a Kilowatt-Hour Actually Is (and Why It Rules Your Bill)',
        slug: 'what-is-a-kilowatt-hour',
        primaryKeyword: 'what is a kilowatt hour',
        secondaryKeywords: ['kwh meaning electric bill', 'kilowatt hour examples'],
        searchIntent: 'Beginners want an intuitive explanation of the kWh unit with everyday examples that make bill numbers meaningful.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Reading Your Electric Bill Line by Line',
        slug: 'how-to-read-electric-bill',
        primaryKeyword: 'how to read your electric bill',
        secondaryKeywords: ['electric bill charges explained', 'understanding utility bill line items'],
        searchIntent: 'Ratepayers want every section of a typical US electric bill decoded so they can find their usage and true rate.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Why Is My Electric Bill So High? A Diagnostic Checklist',
        slug: 'why-is-my-electric-bill-so-high',
        primaryKeyword: 'why is my electric bill so high',
        secondaryKeywords: ['sudden increase in electric bill', 'high electricity usage causes'],
        searchIntent: 'Frustrated ratepayers want a systematic way to trace an unexpectedly high bill back to specific loads or billing changes.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'The Appliances Quietly Eating Most of Your Electricity',
        slug: 'what-uses-most-electricity-home',
        primaryKeyword: 'what uses the most electricity in a home',
        secondaryKeywords: ['biggest household electricity consumers', 'appliance energy usage ranking'],
        searchIntent: 'Readers want a ranked breakdown of which home systems and appliances dominate a typical household’s kWh consumption.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Phantom Loads: The Power You Pay for While You Sleep',
        slug: 'phantom-loads-electricity',
        primaryKeyword: 'phantom load electricity',
        secondaryKeywords: ['standby power consumption', 'vampire energy drain devices'],
        searchIntent: 'Readers want to identify always-on standby devices, measure their draw, and estimate the kWh they silently add each month.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Air Conditioning and Your kWh: What Summer Really Does to Usage',
        slug: 'air-conditioner-electricity-usage',
        primaryKeyword: 'how much electricity does an air conditioner use',
        secondaryKeywords: ['central ac kwh per month', 'air conditioning energy consumption'],
        searchIntent: 'Homeowners want realistic AC consumption figures by unit type and climate to explain their summer usage spike.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'Electric Heat and the Winter Usage Spike',
        slug: 'electric-heating-usage',
        primaryKeyword: 'electric heating kwh usage',
        secondaryKeywords: ['how much electricity does electric heat use', 'baseboard vs heat pump energy use'],
        searchIntent: 'Households with electric heat want to understand how resistance and heat-pump heating drive winter kWh totals.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'Water Heaters: The Second-Biggest Load in Most Homes',
        slug: 'water-heater-electricity-usage',
        primaryKeyword: 'water heater electricity usage',
        secondaryKeywords: ['electric water heater kwh per month', 'tank vs heat pump water heater energy'],
        searchIntent: 'Readers want to quantify their water heater’s share of monthly usage and compare consumption across heater types.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'How Home Size Shapes Electricity Usage',
        slug: 'electricity-usage-by-home-size',
        primaryKeyword: 'electricity usage by home size',
        secondaryKeywords: ['kwh usage by square footage', 'electricity consumption small vs large house'],
        searchIntent: 'Movers and shoppers want typical kWh figures by square footage and bedroom count to anticipate a home’s energy demand.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
        pillar: false,
      },
      {
        title: 'Why Your Usage Swings With the Seasons',
        slug: 'seasonal-electricity-usage',
        primaryKeyword: 'seasonal electricity usage patterns',
        secondaryKeywords: ['summer vs winter electricity use', 'monthly kwh variation'],
        searchIntent: 'Readers want to understand the seasonal shape of household consumption and why annual averages hide big monthly swings.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'What Your Smart Meter Knows About You',
        slug: 'smart-meter-electricity-data',
        primaryKeyword: 'what does a smart meter track',
        secondaryKeywords: ['smart meter usage data explained', 'reading smart meter interval data'],
        searchIntent: 'Curious ratepayers want to know what interval data their smart meter records and how to access it to study their own usage.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Estimating Your Annual kWh Without a Year of Bills',
        slug: 'estimate-annual-kwh-usage',
        primaryKeyword: 'estimate annual electricity usage',
        secondaryKeywords: ['calculate yearly kwh from one bill', 'annual kwh estimation methods'],
        searchIntent: 'New homeowners and recent movers want methods for projecting a full year of usage from limited billing history.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'The DIY Home Energy Audit: Find Your Waste in an Afternoon',
        slug: 'diy-home-energy-audit',
        primaryKeyword: 'diy home energy audit',
        secondaryKeywords: ['home energy audit checklist', 'self energy assessment steps'],
        searchIntent: 'Motivated homeowners want a room-by-room walkthrough for auditing their own consumption without hiring a professional.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Home Energy Monitors: Watching Your Usage in Real Time',
        slug: 'home-energy-monitor-guide',
        primaryKeyword: 'home energy monitor',
        secondaryKeywords: ['whole house electricity monitor', 'real time energy tracking devices'],
        searchIntent: 'Data-minded readers want to know how circuit-level monitors work and what usage insights justify installing one.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Cut Usage First: Efficiency Moves That Shrink the System You Need',
        slug: 'reduce-electricity-usage-before-solar',
        primaryKeyword: 'reduce electricity usage before solar',
        secondaryKeywords: ['efficiency upgrades before going solar', 'lower kwh to buy fewer panels'],
        searchIntent: 'Pre-solar homeowners want the efficiency improvements worth doing first because they directly reduce required system size.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
        pillar: false,
      },
      {
        title: 'Tiered Rates: Why Your 900th kWh Costs More Than Your First',
        slug: 'tiered-electricity-rates',
        primaryKeyword: 'tiered electricity rates explained',
        secondaryKeywords: ['tiered rate structure utility', 'electricity price tiers by usage'],
        searchIntent: 'Ratepayers on tiered plans want to understand how usage blocks are priced and why heavy months cost disproportionately more.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Baseline Allowances: The Fine Print That Sets Your Rate Tier',
        slug: 'baseline-electricity-allowance',
        primaryKeyword: 'baseline allowance electric bill',
        secondaryKeywords: ['baseline quantity utility rates', 'how baseline allocation is calculated'],
        searchIntent: 'Readers who see a baseline line item want to know how utilities set the allowance and how it determines their tier pricing.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: false,
      },
      {
        title: 'Load Shifting Basics: Moving Usage Instead of Cutting It',
        slug: 'load-shifting-home-electricity',
        primaryKeyword: 'load shifting electricity',
        secondaryKeywords: ['shifting appliance run times', 'when to run appliances energy'],
        searchIntent: 'Households want practical routines for rescheduling flexible loads like laundry and dishwashing across the day.',
        relatedCalculators: ['solar-battery-calculator'],
        pillar: false,
      },
      {
        title: 'What an EV Does to Your Household kWh',
        slug: 'ev-charging-home-electricity-usage',
        primaryKeyword: 'ev charging electricity usage at home',
        secondaryKeywords: ['how many kwh does an ev add', 'electric car home charging consumption'],
        searchIntent: 'Prospective EV buyers want to project how home charging will raise their monthly kWh before the car arrives.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
        pillar: false,
      },
    ],
  },
];
