// SEO topic plan — batch H (expansion 300 -> 500)
// SunMetricLab (sunmetriclab.com) — US-focused solar calculators + blog.
// Plan only: no articles are written here. Each entry defines a future post.
//
// Scope of this batch (EXACTLY 40 entries):
// - Batteries & Storage: 22 (long-tail sizing/economics angles)
// - Inverters & Components: 18 (long-tail design/hardware angles)
//
// Rules honored:
// - Every slug, primaryKeyword, and searchIntent is new — no reuse of any of the
//   300 existing plan entries (checked case-insensitively).
// - New long-tail angles only; no rehash of the existing generic battery/inverter
//   explainers (essential-loads sizing, TOU arbitrage concept, round-trip
//   efficiency, placement/temperature, AC vs DC coupling, warranty-term decoding,
//   dc:ac ratio basics, clipping explainer, CEC efficiency, rapid-shutdown
//   requirements, monitoring basics, etc.).
// - relatedCalculators only from the approved calculator ids.
// - Angles are structural/climatic/decision-based so articles stay time-stable
//   (no specific current program dollar values or brand claims).

export const clusters = [
  {
    cluster: 'Batteries (expansion)',
    category: 'Batteries & Storage',
    entries: [
      {
        title: 'How Big a Battery Keeps a Fridge and Freezer Cold in an Outage?',
        slug: 'battery-to-run-fridge-and-freezer',
        primaryKeyword: 'solar battery to run a refrigerator and freezer',
        secondaryKeywords: ['battery backup for fridge and freezer', 'keep food cold during outage', 'battery for two refrigerators'],
        searchIntent: 'A homeowner focused on saving food wants to size a battery that keeps both a refrigerator and a chest freezer cold through a typical outage.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Sizing a Home Battery for CPAP, Oxygen, and Other Medical Gear',
        slug: 'battery-backup-for-medical-devices',
        primaryKeyword: 'home battery backup for medical devices',
        secondaryKeywords: ['battery for cpap during outage', 'oxygen concentrator backup power', 'medical device power backup'],
        searchIntent: 'A household that depends on medical equipment wants to size a battery that guarantees runtime for devices like a CPAP or oxygen concentrator during an outage.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Can a Home Battery Run a Well Pump? Sizing for a Big Surge Load',
        slug: 'battery-to-run-a-well-pump',
        primaryKeyword: 'solar battery to run a well pump',
        secondaryKeywords: ['battery backup for well pump', 'well pump surge power', 'run well pump during outage'],
        searchIntent: 'A rural homeowner on a private well wants to know whether a battery can handle the high startup surge of a well pump and how much capacity keeps water flowing.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Battery Backup for a Sump Pump: Keeping the Basement Dry',
        slug: 'battery-backup-for-a-sump-pump',
        primaryKeyword: 'battery backup for a sump pump',
        secondaryKeywords: ['sump pump battery during storm', 'basement flooding power outage', 'sump pump backup power'],
        searchIntent: 'A homeowner in a flood-prone area wants to size a battery that keeps a sump pump cycling through the storm outages that threaten to flood the basement.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Sizing a Battery to Carry a Whole Home Through a Multi-Day Outage',
        slug: 'battery-sizing-multi-day-outage',
        primaryKeyword: 'sizing a battery for a multi-day power outage',
        secondaryKeywords: ['whole home battery for long outage', 'multi day backup power', 'battery and solar recharge during outage'],
        searchIntent: 'A homeowner preparing for rare but long grid failures wants to size battery capacity and solar recharge to run a whole house for several days.',
        relatedCalculators: ['solar-battery-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Will a Battery Actually Save You Money on Time-of-Use Rates?',
        slug: 'battery-time-of-use-savings-math',
        primaryKeyword: 'will a battery save money on time-of-use rates',
        secondaryKeywords: ['battery peak off-peak price spread', 'time of use battery breakeven', 'battery rate arbitrage math'],
        searchIntent: 'A homeowner on a time-of-use plan wants to run the breakeven math on whether the peak-to-off-peak price spread covers the cost of cycling a battery every day.',
        relatedCalculators: ['solar-battery-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Why Home Batteries Age Even When You Barely Use Them',
        slug: 'battery-calendar-vs-cycle-aging',
        primaryKeyword: 'battery calendar aging vs cycle aging',
        secondaryKeywords: ['home battery calendar degradation', 'does a battery age when not used', 'battery aging factors'],
        searchIntent: 'A long-term owner wants to understand how calendar aging and cycle aging each eat into a home battery, and why a lightly used pack still loses capacity over the years.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Home Battery in a Hot Garage vs a Conditioned Room: Does It Matter?',
        slug: 'battery-hot-garage-vs-conditioned-space',
        primaryKeyword: 'solar battery in a hot garage',
        secondaryKeywords: ['battery temperature and lifespan', 'conditioned space for home battery', 'garage battery heat'],
        searchIntent: 'A homeowner deciding where to mount storage wants to know how the heat of an uninsulated garage compares with a conditioned space for battery output and lifespan.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Sizing a Battery Today for the Heat Pump and EV You Add Later',
        slug: 'future-proofing-battery-capacity',
        primaryKeyword: 'future-proofing home battery capacity',
        secondaryKeywords: ['battery sizing for future electrification', 'battery for heat pump and ev', 'plan battery capacity ahead'],
        searchIntent: 'A homeowner electrifying in stages wants to decide how much battery capacity to buy now so it still fits after a future heat pump and EV raise demand.',
        relatedCalculators: ['solar-battery-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'Frequent Short Outages or One Long One? Size the Battery Differently',
        slug: 'battery-frequent-short-vs-rare-long-outages',
        primaryKeyword: 'sizing a battery for frequent short outages',
        secondaryKeywords: ['battery for brief power flickers', 'short outages vs long outages battery', 'backup for unreliable grid'],
        searchIntent: 'A homeowner with a flickery grid wants to know why many brief outages call for a different battery strategy than a single rare multi-day failure.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Pairing a Battery With a Generator: How to Size a Smaller Pack',
        slug: 'battery-generator-hybrid-sizing',
        primaryKeyword: 'sizing a battery with a backup generator',
        secondaryKeywords: ['battery and generator hybrid backup', 'downsize battery with generator', 'generator battery combo sizing'],
        searchIntent: 'A homeowner who already owns or wants a generator wants to size a smaller battery that handles quiet overnight loads while the generator covers extended runtime.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'How Much Battery Does an All-Electric Home Really Need?',
        slug: 'battery-for-all-electric-home',
        primaryKeyword: 'home battery for an all-electric house',
        secondaryKeywords: ['battery for gas-free home', 'all electric home backup power', 'heat pump induction battery sizing'],
        searchIntent: 'An owner of a gas-free home with heat pumps and induction cooking wants to size storage that keeps electric heating and cooking loads running when the grid drops.',
        relatedCalculators: ['solar-battery-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'Adding a Battery to Solar That Is Already Ten Years Old',
        slug: 'adding-battery-to-old-solar',
        primaryKeyword: 'adding a battery to old solar panels',
        secondaryKeywords: ['retrofit battery aging solar array', 'battery for old string inverter', 'ac couple battery to old system'],
        searchIntent: 'An owner of an aging array wants to know how to add storage to an older system built around a legacy string inverter without ripping out what still works.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'How to Compare Home Batteries Without Getting Lost in Brand Names',
        slug: 'how-to-compare-home-batteries',
        primaryKeyword: 'how to compare home batteries',
        secondaryKeywords: ['home battery spec comparison', 'usable kwh vs rated kwh', 'compare battery power and warranty'],
        searchIntent: 'A shopper wants a brand-neutral checklist for lining up batteries on usable capacity, continuous power, efficiency, and warranty rather than marketing labels.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Permits and Inspections for Adding a Home Battery, Step by Step',
        slug: 'home-battery-permits-inspection',
        primaryKeyword: 'home battery permit and inspection process',
        secondaryKeywords: ['battery storage permit', 'energy storage inspection', 'adding battery interconnection'],
        searchIntent: 'A homeowner adding storage wants to know what permits, inspections, and utility sign-offs a battery install triggers and how long each step tends to take.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Financing a Home Battery: Loans, Interest, and the True Cost',
        slug: 'financing-a-home-battery',
        primaryKeyword: 'financing a home battery',
        secondaryKeywords: ['home battery loan', 'battery storage financing options', 'cost of financing a battery'],
        searchIntent: 'A buyer who cannot pay cash wants to understand how loan terms and interest change the real lifetime cost of a standalone home battery.',
        relatedCalculators: ['solar-loan-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Will You Ever Hit Your Battery Warranty Throughput Limit?',
        slug: 'battery-warranty-throughput-projection',
        primaryKeyword: 'how much battery throughput will i use',
        secondaryKeywords: ['battery throughput warranty limit', 'estimate battery cycles per year', 'battery energy throughput math'],
        searchIntent: 'A cautious buyer wants to project annual energy throughput against the warranty cap to see whether normal use would ever reach the guaranteed limit.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Putting a Dollar Value on Never Losing Power',
        slug: 'value-of-backup-power',
        primaryKeyword: 'dollar value of backup power',
        secondaryKeywords: ['what is backup power worth', 'cost of a power outage to a home', 'value of home battery backup'],
        searchIntent: 'A homeowner weighing a battery on more than payback wants a method to price spoiled food, hotel nights, and lost work into the value of backup power.',
        relatedCalculators: ['solar-battery-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'How Much Extra Battery to Buy for Winter and Years of Wear',
        slug: 'oversizing-battery-for-winter-and-degradation',
        primaryKeyword: 'how much extra battery capacity to buy',
        secondaryKeywords: ['oversize battery for degradation', 'battery capacity buffer winter', 'battery headroom sizing'],
        searchIntent: 'A buyer wants to know how much headroom to add to a battery so cold weather and years of capacity fade do not leave it short later on.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Battery Backup for Winter Storms: Cold, Heat Loads, and Runtime',
        slug: 'battery-for-winter-storm-outages',
        primaryKeyword: 'home battery for winter power outages',
        secondaryKeywords: ['battery in cold weather outage', 'backup heat during winter outage', 'winter storm battery runtime'],
        searchIntent: 'A homeowner in a cold region wants to size a battery for winter outages while accounting for reduced cold-weather capacity and the heavy loads of staying warm.',
        relatedCalculators: ['solar-battery-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'Keeping a Home Office Online: Battery Sizing for Remote Work',
        slug: 'battery-backup-for-home-office',
        primaryKeyword: 'battery backup for a home office',
        secondaryKeywords: ['keep working during power outage', 'battery for computer and internet', 'remote work backup power'],
        searchIntent: 'A remote worker wants to size a modest battery that keeps computers, monitors, and internet gear running through the outages that would otherwise stop the workday.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Using a Home Battery to Dodge Residential Demand Charges',
        slug: 'battery-for-demand-charges',
        primaryKeyword: 'home battery for demand charges',
        secondaryKeywords: ['residential demand charge battery', 'peak demand shaving home', 'battery to cut demand fees'],
        searchIntent: 'A homeowner billed on a residential demand charge wants to understand how a battery shaves the brief peaks that set those fees and whether it pays off.',
        relatedCalculators: ['solar-battery-calculator', 'electricity-bill-calculator'],
      },
    ],
  },
  {
    cluster: 'Inverters & components (expansion)',
    category: 'Inverters & Components',
    entries: [
      {
        title: 'The Right DC-to-AC Ratio Changes With Your Climate',
        slug: 'dc-ac-ratio-by-climate',
        primaryKeyword: 'best dc to ac ratio for hot climates',
        secondaryKeywords: ['dc ac ratio by climate', 'array oversizing hot weather', 'inverter loading ratio heat'],
        searchIntent: 'A homeowner comparing quotes wants to know why a hot, hazy climate justifies a different array-to-inverter ratio than a cool, sunny one.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Why Complex, Multi-Angle Roofs Often Point Toward Microinverters',
        slug: 'microinverters-for-complex-roofs',
        primaryKeyword: 'microinverters for a complex roof',
        secondaryKeywords: ['microinverters multiple roof planes', 'best inverter for cut-up roof', 'panel level power complex roof'],
        searchIntent: 'A homeowner with dormers, hips, and several small roof faces wants to understand why per-panel electronics simplify a cut-up layout.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Hybrid Inverter Now or a Separate Battery Inverter Later?',
        slug: 'hybrid-inverter-vs-battery-inverter-later',
        primaryKeyword: 'hybrid inverter or add a battery inverter later',
        secondaryKeywords: ['hybrid vs ac coupled battery cost', 'future battery inverter choice', 'storage ready inverter decision'],
        searchIntent: 'A buyer unsure about future storage wants to weigh paying for a hybrid inverter today against adding a separate battery inverter when the battery finally arrives.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'How Much Inverter Clipping Should You Actually Tolerate?',
        slug: 'how-much-clipping-is-acceptable',
        primaryKeyword: 'how much inverter clipping is acceptable',
        secondaryKeywords: ['acceptable clipping losses', 'clipping by climate and orientation', 'is inverter clipping bad'],
        searchIntent: 'A homeowner who sees a flat-topped production estimate wants a rule of thumb for how much clipping is fine given their climate and roof orientation.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'What a Solar Inverter Replacement Really Costs, Line by Line',
        slug: 'inverter-replacement-cost',
        primaryKeyword: 'solar inverter replacement cost',
        secondaryKeywords: ['cost to replace solar inverter', 'inverter swap labor cost', 'out of pocket inverter replacement'],
        searchIntent: 'An owner planning for the day an inverter dies wants a line-by-line look at hardware, labor, and permit costs and when a warranty covers them.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'What Those Current Transformer Clamps in Your Panel Are For',
        slug: 'consumption-monitoring-cts',
        primaryKeyword: 'solar consumption monitoring cts',
        secondaryKeywords: ['current transformer clamps solar', 'whole home consumption monitoring', 'ct clamps net metering data'],
        searchIntent: 'A new system owner wants to understand what the current transformer clamps do and why whole-home consumption data matters for self-use and battery planning.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Rapid Shutdown Rules by Code Year: What Applies to Your Install',
        slug: 'rapid-shutdown-nec-editions',
        primaryKeyword: 'rapid shutdown nec code editions',
        secondaryKeywords: ['module level rapid shutdown code', 'rapid shutdown by code year', 'electrical code solar shutdown history'],
        searchIntent: 'A homeowner wants to see how rapid shutdown requirements tightened across successive electrical code editions and which one their jurisdiction enforces.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How Many Panels Go on a String? Voltage Windows Made Simple',
        slug: 'solar-string-sizing-basics',
        primaryKeyword: 'how many panels per string',
        secondaryKeywords: ['solar string sizing', 'inverter voltage window', 'cold weather string voltage'],
        searchIntent: 'A curious homeowner wants a plain explanation of how installers decide the number of panels per string within an inverter voltage window.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Reading an Inverter Efficiency Curve, Not Just the Headline Number',
        slug: 'inverter-efficiency-curve',
        primaryKeyword: 'solar inverter efficiency curve',
        secondaryKeywords: ['inverter part load efficiency', 'efficiency vs load inverter', 'oversized inverter low output loss'],
        searchIntent: 'A spec-sheet reader wants to interpret how inverter efficiency shifts across the load range and why an oversized inverter loses ground at low output.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Grounding and Bonding a Solar System, Explained for Homeowners',
        slug: 'solar-system-grounding-bonding',
        primaryKeyword: 'solar panel grounding and bonding',
        secondaryKeywords: ['solar equipment grounding', 'array bonding lightning', 'grounding electrode solar'],
        searchIntent: 'A homeowner wants a clear picture of how a solar array is grounded and bonded and why it matters for safety and lightning protection.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Why You Should Never Put an Inverter in a Hot Attic',
        slug: 'inverter-heat-derating-placement',
        primaryKeyword: 'solar inverter heat derating',
        secondaryKeywords: ['inverter in hot attic', 'inverter shade placement', 'inverter temperature derating output'],
        searchIntent: 'A homeowner planning where hardware goes wants to know how attic heat derates inverter output and shortens life compared with a shaded exterior wall.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Do You Even Need Power Optimizers on an Unshaded Roof?',
        slug: 'power-optimizers-without-shade',
        primaryKeyword: 'do i need power optimizers without shade',
        secondaryKeywords: ['optimizers on unshaded roof', 'are power optimizers worth it', 'string vs optimizers no shade'],
        searchIntent: 'A homeowner with a clean, unshaded roof wants to decide whether per-panel optimizers add enough value to justify their cost and extra parts.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Will Your Electrical Service Handle Solar? Volts, Phases, and Amps',
        slug: 'inverter-electrical-service-compatibility',
        primaryKeyword: 'solar inverter and electrical service size',
        secondaryKeywords: ['240v split phase solar', 'inverter voltage compatibility home', 'service size for solar inverter'],
        searchIntent: 'A homeowner wants to know how their home voltage, phase, and service amperage shape which inverter fits and whether an upgrade is needed.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'The 120% Rule: When Solar Backfeed Forces a Panel Upgrade',
        slug: 'solar-120-percent-rule-busbar',
        primaryKeyword: 'solar 120 percent rule',
        secondaryKeywords: ['busbar rating solar backfeed', 'main panel upgrade for solar', 'line side tap vs load side'],
        searchIntent: 'A homeowner wants to understand the busbar backfeed rule that decides whether solar can connect to the existing panel or needs an upgrade or line-side tap.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Backup Gateways vs Transfer Switches: What Actually Islands a Home',
        slug: 'backup-gateway-transfer-switch',
        primaryKeyword: 'solar backup gateway vs transfer switch',
        secondaryKeywords: ['automatic transfer switch solar', 'backup gateway islanding', 'whole home backup switch'],
        searchIntent: 'A homeowner planning battery backup wants to know what a backup gateway or transfer switch does to safely disconnect from the grid and power the house.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Keeping Solar Monitoring Online: Wi-Fi, Ethernet, and Dead Spots',
        slug: 'solar-monitoring-connectivity',
        primaryKeyword: 'solar monitoring wifi connection',
        secondaryKeywords: ['solar monitoring offline fix', 'inverter ethernet vs wifi', 'monitoring gateway signal'],
        searchIntent: 'A system owner wants practical guidance on connecting inverter monitoring to the network and preventing the dropouts that hide production data.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'AC and DC Disconnects: The Switches That Make Solar Safe to Service',
        slug: 'solar-disconnect-switches',
        primaryKeyword: 'solar disconnect switches explained',
        secondaryKeywords: ['ac disconnect vs dc disconnect', 'solar service disconnect', 'utility disconnect solar'],
        searchIntent: 'A homeowner wants to understand the AC and DC disconnect switches on a solar install and why utilities and electricians require them.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Sizing an Inverter So You Can Add Panels Down the Road',
        slug: 'inverter-sizing-for-future-expansion',
        primaryKeyword: 'sizing an inverter for future panel expansion',
        secondaryKeywords: ['inverter headroom for more panels', 'expandable solar inverter', 'oversize inverter for expansion'],
        searchIntent: 'A homeowner who may add panels later wants to know how to leave inverter headroom now without wasting money on capacity that sits idle.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-panel-calculator'],
      },
    ],
  },
];
