// SEO topic plan — batch G (expansion 300 -> 500)
// SunMetricLab (sunmetriclab.com) — US-focused solar calculators + blog.
// Plan only: no articles are written here. Each entry defines a future post.
//
// Scope: deepen the money-focused clusters (Costs, Savings & ROI, Payback)
// with NEW long-tail angles that do not reuse any existing slug,
// primaryKeyword, or searchIntent from content-plan.json.
//
// Counts: Solar Costs 16, Savings & ROI 14, Payback 10 (total 40).
//
// Rules honored:
// - slugs kebab-case and unique; unique primaryKeyword + unique one-sentence
//   searchIntent per entry; 2-3 secondaryKeywords each.
// - relatedCalculators drawn only from the approved id list:
//   solar-panel-calculator, solar-panel-cost-calculator, solar-roi-calculator,
//   solar-battery-calculator, how-many-solar-panels-do-i-need,
//   solar-panel-size-calculator, solar-loan-calculator, solar-payback-calculator,
//   ev-charging-calculator, heat-pump-calculator, electricity-bill-calculator,
//   federal-tax-credit-calculator, solar-payment-comparison.
// - Angles are structural/financial, not tied to a specific current price or
//   program dollar value, so articles stay writable time-stably.

export const clusters = [
  {
    cluster: 'Costs (expansion)',
    category: 'Solar Costs',
    entries: [
      {
        title: 'What a Solar Dealer Fee Really Costs You on a Financed System',
        slug: 'solar-dealer-fee-explained',
        primaryKeyword: 'solar dealer fee',
        secondaryKeywords: ['solar loan dealer fee', 'hidden solar financing fee', 'why financed solar costs more'],
        searchIntent: 'Buyers offered a low-APR solar loan want to understand how the lender dealer fee is folded into the price and why the financed number tops a cash quote.',
        relatedCalculators: ['solar-loan-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Loan vs HELOC: Which Financing Costs Less Over Time?',
        slug: 'solar-loan-vs-heloc-cost',
        primaryKeyword: 'solar loan vs heloc',
        secondaryKeywords: ['home equity loan for solar', 'financing solar with heloc', 'cheapest way to finance solar'],
        searchIntent: 'Homeowners with equity want to compare the total interest and fees of a dedicated solar loan against tapping a home equity line to pay for panels.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payment-comparison'],
      },
      {
        title: 'Can You Refinance a Solar Loan, and Does It Actually Save Money?',
        slug: 'refinance-solar-loan',
        primaryKeyword: 'refinancing a solar loan',
        secondaryKeywords: ['refinance solar panel loan', 'lower solar loan interest', 'solar loan refinance options'],
        searchIntent: 'Owners stuck with a high-rate solar loan want to know whether refinancing into a cheaper product is possible and what fees eat into the savings.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payment-comparison'],
      },
      {
        title: "Paying Off a Solar Loan Early: What It Saves and What It Doesn't",
        slug: 'pay-off-solar-loan-early',
        primaryKeyword: 'paying off solar loan early',
        secondaryKeywords: ['solar loan prepayment', 'solar loan reamortization', 'prepay solar loan tax credit'],
        searchIntent: 'Borrowers planning to apply the federal credit as a lump sum want to see how prepaying a solar loan changes the payment and total interest and where reamortization matters.',
        relatedCalculators: ['solar-loan-calculator', 'federal-tax-credit-calculator'],
      },
      {
        title: "The 'No-Cost' Solar Loan: What's Really Baked Into the Price",
        slug: 'no-cost-solar-loan-reality',
        primaryKeyword: 'no cost solar loan',
        secondaryKeywords: ['zero out of pocket solar', 'solar loan buydown', 'no money down solar cost'],
        searchIntent: 'Shoppers hearing a no-cost or nothing-out-of-pocket pitch want to understand the rate buydown that quietly raises the cash-equivalent price of the system.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payment-comparison'],
      },
      {
        title: 'What It Costs to Add an EV Charger During a Solar Install',
        slug: 'ev-charger-install-cost-with-solar',
        primaryKeyword: 'ev charger installation cost',
        secondaryKeywords: ['level 2 charger install with solar', 'cost to add ev charger', 'ev charger wiring cost'],
        searchIntent: 'Homeowners bundling an EV charger with panels want a breakdown of the wiring, breaker, and labor costs and why doing it during the solar job can be cheaper.',
        relatedCalculators: ['ev-charging-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Main Panel Upgrade for Solar: What Actually Drives the Cost',
        slug: 'main-panel-upgrade-cost-drivers',
        primaryKeyword: 'main service panel upgrade cost',
        secondaryKeywords: ['200 amp panel upgrade for solar', 'service upgrade cost solar', 'why panel upgrade costs vary'],
        searchIntent: 'Buyers told they need a service upgrade want to know which factors, from amperage to meter relocation and utility rules, push the panel-upgrade price up or down.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How Much a Critical-Load Backup Panel Adds to Your Solar Bill',
        slug: 'critical-load-panel-cost',
        primaryKeyword: 'critical load panel cost',
        secondaryKeywords: ['backup subpanel cost', 'essential loads panel price', 'partial backup wiring cost'],
        searchIntent: 'Owners planning partial backup want to budget for the subpanel, wiring, and labor of separating critical loads rather than backing up the whole house.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: "What Solar Monitoring Add-Ons Cost and When They're Worth It",
        slug: 'solar-monitoring-add-on-cost',
        primaryKeyword: 'solar monitoring cost',
        secondaryKeywords: ['consumption monitoring add-on', 'panel-level monitoring price', 'solar monitoring hardware cost'],
        searchIntent: 'Shoppers reviewing quote line items want to know what consumption and panel-level monitoring hardware adds and whether the upgrade earns its price.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: '3kW Solar System Cost: Pricing a Small, Low-Usage Setup',
        slug: '3kw-solar-system-cost',
        primaryKeyword: '3kw solar system cost',
        secondaryKeywords: ['3 kw solar price', 'small solar system cost', 'cost of a 3kw system'],
        searchIntent: 'Owners of a small or low-usage home want the installed price range for a 3 kW array and why per-watt pricing runs higher at tiny sizes.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: '15kW Solar System Cost: What a Large Home Array Runs',
        slug: '15kw-solar-system-cost',
        primaryKeyword: '15kw solar system cost',
        secondaryKeywords: ['15 kw solar price', 'large solar system cost', 'cost of a 15kw system'],
        searchIntent: 'Owners of a big, high-consumption home want the installed cost of a 15 kW system and how economies of scale change the per-watt figure.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: '20kW Solar System Cost: Pricing a High-Usage Whole-Home Array',
        slug: '20kw-solar-system-cost',
        primaryKeyword: '20kw solar system cost',
        secondaryKeywords: ['20 kw solar price', 'very large residential solar cost', 'cost of a 20kw system'],
        searchIntent: 'Buyers with heavy electric heating, pools, or multiple EVs want the installed price of a 20 kW array and whether such a large residential system is worth building.',
        relatedCalculators: ['solar-panel-cost-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'What Solar Costs on a Mobile or Manufactured Home',
        slug: 'mobile-home-solar-cost',
        primaryKeyword: 'solar panels on a mobile home cost',
        secondaryKeywords: ['manufactured home solar price', 'solar for a double-wide', 'mobile home roof solar cost'],
        searchIntent: 'Manufactured-home owners want to know how roof structure, ground-mount options, and lot ownership change the cost of going solar on a mobile home.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Solar on New Construction: Bundled Cost vs a Later Retrofit',
        slug: 'new-construction-solar-cost',
        primaryKeyword: 'solar on new construction cost',
        secondaryKeywords: ['builder solar package cost', 'solar in a new build', 'new home solar vs retrofit price'],
        searchIntent: 'Buyers of a new build want to weigh the price of a builder-bundled solar package against adding panels themselves after closing.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar Interconnection Fees: The Utility Charges Quotes Skip',
        slug: 'solar-interconnection-fees',
        primaryKeyword: 'solar interconnection fees',
        secondaryKeywords: ['utility interconnection charges', 'solar application fee', 'net metering setup fee'],
        searchIntent: 'Homeowners comparing quotes want to understand the application, study, and metering charges a utility levies to connect a solar system to the grid.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Why the Same Solar System Costs More in Some States',
        slug: 'regional-solar-cost-differences',
        primaryKeyword: 'why does solar cost more in some states',
        secondaryKeywords: ['regional solar price differences', 'solar cost by region', 'what makes solar expensive locally'],
        searchIntent: 'Readers comparing national averages to local bids want to know how labor rates, permitting friction, and market competition create a wide geographic price spread.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
    ],
  },
  {
    cluster: 'Savings & ROI (expansion)',
    category: 'Savings & ROI',
    entries: [
      {
        title: 'How Much Solar Saves When You Run a Swimming Pool Pump',
        slug: 'solar-savings-with-pool',
        primaryKeyword: 'solar savings with a pool',
        secondaryKeywords: ['solar for pool electricity', 'pool pump solar savings', 'offset pool electric bill with solar'],
        searchIntent: 'Pool owners want to estimate how much of a pump and heater electric load home solar can offset and how it reshapes their annual savings.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar Savings When You Work From Home All Day',
        slug: 'solar-savings-working-from-home',
        primaryKeyword: 'solar savings working from home',
        secondaryKeywords: ['solar for remote workers', 'daytime electricity use solar', 'work from home solar benefit'],
        searchIntent: 'Remote workers want to know why running appliances and HVAC during daylight lets a home consume its own solar and boosts savings versus an empty daytime house.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Is 100% Offset the Goal? Picking an Offset That Saves the Most',
        slug: 'best-solar-offset-for-savings',
        primaryKeyword: 'best solar offset percentage',
        secondaryKeywords: ['ideal solar offset target', 'should i offset 100 percent', 'right size solar for savings'],
        searchIntent: 'Buyers deciding how big to build want to see why targeting slightly under full offset can maximize dollar savings where exports are paid below retail.',
        relatedCalculators: ['solar-roi-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Solar Savings for an All-Electric Home With No Gas Bill',
        slug: 'solar-savings-all-electric-home',
        primaryKeyword: 'solar savings all electric home',
        secondaryKeywords: ['all electric house solar', 'no gas home solar savings', 'solar for electric-only home'],
        searchIntent: 'Owners of a home that runs everything on electricity want to understand why their higher baseline load makes solar savings larger than a mixed gas-and-electric household.',
        relatedCalculators: ['heat-pump-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Will Your Solar Loan Payment Beat Your Monthly Savings?',
        slug: 'solar-loan-payment-vs-savings-cash-flow',
        primaryKeyword: 'solar loan payment vs savings',
        secondaryKeywords: ['solar cash flow positive', 'does solar loan payment exceed savings', 'monthly solar payment vs bill'],
        searchIntent: 'Financed buyers want to know whether the loan payment stays below their bill savings every month, including low-production winter months when cash flow can turn negative.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payment-comparison'],
      },
      {
        title: 'Solar Savings on an Electric or Heat-Pump Water Heater',
        slug: 'solar-savings-electric-water-heater',
        primaryKeyword: 'solar savings electric water heater',
        secondaryKeywords: ['solar for water heating', 'heat pump water heater solar', 'offset water heater with solar'],
        searchIntent: 'Owners with an electric or heat-pump water heater want to estimate how much of that steady load solar can cover and add to their yearly savings.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Does a Home Battery Add Resale Value the Way Panels Do?',
        slug: 'solar-battery-home-value',
        primaryKeyword: 'does a solar battery add home value',
        secondaryKeywords: ['battery resale value', 'home battery appraisal', 'does storage increase home value'],
        searchIntent: 'Owners weighing storage want to know whether a home battery lifts resale value and appraisal like panels or is treated as a depreciating appliance.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar vs the Stock Market: Comparing the Real Return',
        slug: 'solar-roi-vs-stock-market',
        primaryKeyword: 'solar vs stock market investment',
        secondaryKeywords: ['solar as an investment', 'solar return vs index fund', 'is solar a good investment return'],
        searchIntent: 'Finance-minded homeowners want to compare the effective, tax-free return of buying solar against putting the same cash into an index fund.',
        relatedCalculators: ['solar-roi-calculator', 'solar-payback-calculator'],
      },
      {
        title: 'How Much the Federal Tax Credit Improves Your Solar ROI',
        slug: 'tax-credit-effect-on-solar-roi',
        primaryKeyword: 'tax credit impact on solar roi',
        secondaryKeywords: ['tax credit and solar return', 'roi with and without tax credit', 'how much does the tax credit help'],
        searchIntent: 'Buyers want to quantify how claiming the federal credit lifts their return and payback versus running the numbers without any incentive.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar Savings When You Electrify Your Whole House',
        slug: 'solar-savings-home-electrification',
        primaryKeyword: 'solar savings with home electrification',
        secondaryKeywords: ['electrify everything solar', 'solar plus heat pump and ev', 'whole home electrification savings'],
        searchIntent: 'Owners replacing gas appliances with electric ones want to see how the growing electric load compounds solar savings across heating, hot water, and driving.',
        relatedCalculators: ['heat-pump-calculator', 'ev-charging-calculator'],
      },
      {
        title: 'Solar Savings for a Big Family in a High-Usage Home',
        slug: 'solar-savings-large-household',
        primaryKeyword: 'solar savings for a large family',
        secondaryKeywords: ['solar for high usage home', 'big household solar savings', 'solar for a family of five'],
        searchIntent: 'Large households want to understand why their above-average consumption lets solar erase a bigger share of the bill than a typical two-person home.',
        relatedCalculators: ['electricity-bill-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'How Much Solar Saves If You Run a Hot Tub Year-Round',
        slug: 'solar-savings-hot-tub',
        primaryKeyword: 'solar savings with a hot tub',
        secondaryKeywords: ['hot tub electricity cost solar', 'spa solar savings', 'offset hot tub with solar'],
        searchIntent: 'Hot tub and spa owners want to estimate the year-round electricity that solar can offset and how it changes their overall savings picture.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Savings When Your Utility Bills Demand Charges',
        slug: 'solar-savings-demand-charges',
        primaryKeyword: 'solar savings with demand charges',
        secondaryKeywords: ['residential demand charge solar', 'solar and peak demand fees', 'battery for demand charges'],
        searchIntent: 'Owners on a rate with residential demand charges want to understand why panels alone barely dent that fee and where a battery is needed to save.',
        relatedCalculators: ['solar-battery-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Solar Savings on Summer Air Conditioning Bills',
        slug: 'solar-savings-with-air-conditioning',
        primaryKeyword: 'solar savings on air conditioning',
        secondaryKeywords: ['solar to offset ac', 'summer cooling solar savings', 'air conditioning electric bill solar'],
        searchIntent: 'Owners with heavy summer cooling want to see how well midday solar production lines up with peak air-conditioning demand to cut their hottest bills.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-panel-calculator'],
      },
    ],
  },
  {
    cluster: 'Payback (expansion)',
    category: 'Payback',
    entries: [
      {
        title: 'Solar Payback When You Finance the System With a HELOC',
        slug: 'solar-payback-with-heloc',
        primaryKeyword: 'solar payback with heloc',
        secondaryKeywords: ['heloc solar payback period', 'home equity solar break even', 'financing solar with equity payback'],
        searchIntent: 'Owners paying for solar with a home equity line want to see how variable HELOC interest and interest-only draws reshape the break-even timeline.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payback-calculator'],
      },
      {
        title: 'How an Inverter Replacement Resets Your Solar Payback',
        slug: 'payback-after-inverter-replacement',
        primaryKeyword: 'solar payback after inverter replacement',
        secondaryKeywords: ['inverter replacement break even', 'mid-life inverter cost payback', 'solar payback with inverter swap'],
        searchIntent: 'Owners facing a mid-life inverter swap want to know how much that one-time cost pushes back the point where the system has fully paid for itself.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar Payback With Partial Shade on the Roof',
        slug: 'solar-payback-with-partial-shade',
        primaryKeyword: 'solar payback with shade',
        secondaryKeywords: ['shaded roof solar break even', 'partial shading payback period', 'trees and solar payback'],
        searchIntent: 'Buyers with a partly shaded roof want to see how lost production from shading stretches their payback and when the project stops making sense.',
        relatedCalculators: ['solar-payback-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Payback on a Vacation or Second Home',
        slug: 'solar-payback-second-home',
        primaryKeyword: 'solar payback on a second home',
        secondaryKeywords: ['vacation home solar payback', 'part-time home solar break even', 'second property solar returns'],
        searchIntent: 'Owners of a lightly occupied second home want to understand why low usage and part-time presence lengthen the payback compared with a primary residence.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Does Solar Still Pay Back If You Plan to Downsize?',
        slug: 'solar-payback-when-downsizing',
        primaryKeyword: 'solar payback when downsizing',
        secondaryKeywords: ['downsizing home solar', 'solar before moving to smaller home', 'shrinking usage solar payback'],
        searchIntent: 'Owners expecting to move to a smaller home or cut usage want to know whether solar can still break even before their electricity needs shrink.',
        relatedCalculators: ['solar-payback-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Which Input Moves Solar Payback the Most? A Sensitivity Check',
        slug: 'solar-payback-sensitivity-analysis',
        primaryKeyword: 'solar payback sensitivity',
        secondaryKeywords: ['what changes solar payback most', 'solar payback input ranking', 'solar break even sensitivity'],
        searchIntent: 'Analytical buyers want each payback input ranked by how many years it swings the break-even point, so they know which assumption to nail down first.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'How Adding a Battery Later Changes Your Solar Payback',
        slug: 'payback-adding-battery-later',
        primaryKeyword: 'payback adding a battery later',
        secondaryKeywords: ['battery retrofit payback', 'add storage years later break even', 'battery after solar payback'],
        searchIntent: 'Owners who went solar first want to see how bolting on a battery years later affects the combined payback versus buying storage upfront.',
        relatedCalculators: ['solar-battery-calculator', 'solar-payback-calculator'],
      },
      {
        title: 'How Much Your Loan APR Stretches Solar Payback',
        slug: 'solar-payback-by-loan-apr',
        primaryKeyword: 'solar payback by loan interest rate',
        secondaryKeywords: ['loan apr and solar break even', 'interest rate effect on payback', 'solar payback high interest loan'],
        searchIntent: 'Financed buyers want to see roughly how many extra years each point of loan APR adds to the time it takes solar to break even.',
        relatedCalculators: ['solar-loan-calculator', 'solar-payback-calculator'],
      },
      {
        title: 'Why Solar Payback Runs Long Where Electricity Is Cheap',
        slug: 'solar-payback-low-electricity-rates',
        primaryKeyword: 'solar payback with low electricity rates',
        secondaryKeywords: ['cheap electricity solar payback', 'low rate solar break even', 'is solar worth it low rates'],
        searchIntent: 'Buyers in low-rate utility territory want to understand why a cheap per-kWh price stretches payback and what would have to change to shorten it.',
        relatedCalculators: ['solar-payback-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Solar Payback on a West- or East-Facing Roof',
        slug: 'solar-payback-west-facing-roof',
        primaryKeyword: 'solar payback west facing roof',
        secondaryKeywords: ['east facing solar payback', 'roof orientation and payback', 'non-south roof solar break even'],
        searchIntent: 'Owners without a south-facing roof want to know how east or west orientation trims annual production and lengthens their payback period.',
        relatedCalculators: ['solar-payback-calculator', 'solar-panel-calculator'],
      },
    ],
  },
];
