// SEO topic plan — batch E
// SunMetricLab (sunmetriclab.com) — US-focused solar calculators + blog.
// Plan only: no articles are written here. Each entry defines a future post.
//
// Rules honored:
// - State Guides: 25 entries (1 pillar + 24 state guides with distinct angles)
// - Off-Grid & Mobile: 15 entries (1 pillar + 14 foundational -> advanced)
// - Myths & Comparisons: 10 entries (1 pillar + 9)
// - relatedCalculators only from the approved calculator ids.
// - No overlap with already-taken keywords (is solar worth it, average solar
//   panel cost, solar payback period, federal solar tax credit, is a solar
//   battery worth it, roof size solar panels, solar panel wattage, kWh-tier
//   panel-count articles).
// - No claims tied to specific current program dollar values; angles are
//   structural/climatic so articles stay time-stable.

export const clusters = [
  {
    cluster: 'State-focused solar guides',
    category: 'State Guides',
    entries: [
      {
        title: 'Why Solar Pays Off in Some States and Barely Breaks Even in Others',
        slug: 'solar-panels-by-state',
        primaryKeyword: 'solar by state',
        secondaryKeywords: ['best states for solar', 'solar savings by state', 'state solar incentives explained'],
        searchIntent: 'Understand which levers actually change solar economics from state to state: peak sun hours, retail electricity rates, how net metering is structured, and permitting friction.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
        pillar: true,
      },
      {
        title: 'Solar in California After the Net Metering Shake-Up',
        slug: 'solar-panels-in-california',
        primaryKeyword: 'solar panels in california',
        secondaryKeywords: ['california solar', 'nem 3 solar economics', 'california net billing'],
        searchIntent: 'Learn how California\'s shift from retail net metering to lower export credits changed system design, making self-consumption and battery pairing central to the math.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Home Solar in Texas: Making Sense of a Deregulated Grid',
        slug: 'solar-panels-in-texas',
        primaryKeyword: 'solar panels in texas',
        secondaryKeywords: ['texas solar', 'texas solar buyback plans'],
        searchIntent: 'Navigate Texas\'s deregulated retail market where there is no statewide net metering mandate and solar returns hinge on choosing a retailer with a fair buyback plan.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Going Solar in Florida: Big Sun, Weak Exports, Hurricane Rules',
        slug: 'solar-panels-in-florida',
        primaryKeyword: 'solar panels in florida',
        secondaryKeywords: ['florida solar', 'hurricane rated solar panels'],
        searchIntent: 'Weigh Florida\'s abundant sunshine against its shifting export-credit rules and the wind-load and attachment requirements that hurricane country imposes on rooftop arrays.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Arizona Solar: When Extreme Heat Works Against Your Panels',
        slug: 'solar-panels-in-arizona',
        primaryKeyword: 'solar panels in arizona',
        secondaryKeywords: ['arizona solar', 'solar panel heat losses'],
        searchIntent: 'See how Arizona\'s desert sun collides with heat-related efficiency losses and time-of-use export rates that pay less for midday production.',
        relatedCalculators: ['solar-panel-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Nevada Solar, Explained: Desert Sun Meets Tiered Export Credits',
        slug: 'solar-panels-in-nevada',
        primaryKeyword: 'solar panels in nevada',
        secondaryKeywords: ['nevada solar', 'nv energy net metering structure'],
        searchIntent: 'Understand how Nevada pairs some of the strongest sun in the country with an export-credit system that steps down over time, rewarding early and right-sized installs.',
        relatedCalculators: ['solar-roi-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'North Carolina: The Southeast\'s Quiet Solar Leader',
        slug: 'solar-panels-in-north-carolina',
        primaryKeyword: 'solar panels in north carolina',
        secondaryKeywords: ['north carolina solar', 'duke energy solar rules'],
        searchIntent: 'Learn why North Carolina leads its region on solar and how Duke Energy\'s transition from classic net metering to newer bridge-style tariffs shapes rooftop returns.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Does Solar Make Sense in New York? Incentives vs. Winter',
        slug: 'solar-panels-in-new-york',
        primaryKeyword: 'solar panels in new york',
        secondaryKeywords: ['new york solar', 'solar in snowy climates ny'],
        searchIntent: 'Weigh New York\'s layered incentive programs and high electricity rates against short winter days and snow-covered months to see how the annual math still works.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Massachusetts Solar and the Logic of Declining-Block Incentives',
        slug: 'solar-panels-in-massachusetts',
        primaryKeyword: 'solar panels in massachusetts',
        secondaryKeywords: ['massachusetts solar', 'smart solar program structure'],
        searchIntent: 'Understand how Massachusetts pays solar owners through capacity-based declining-block programs, and why high regional electricity rates offset its modest sun.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'New Jersey Solar: How Performance Certificates Change the Math',
        slug: 'solar-panels-in-new-jersey',
        primaryKeyword: 'solar panels in new jersey',
        secondaryKeywords: ['new jersey solar', 'srec income for homeowners'],
        searchIntent: 'See how New Jersey\'s certificate-based performance incentives add an income stream on top of bill savings, a structure few other states use.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Colorado Solar: High Altitude Helps, Hail Does Not',
        slug: 'solar-panels-in-colorado',
        primaryKeyword: 'solar panels in colorado',
        secondaryKeywords: ['colorado solar', 'hail proof solar panels'],
        searchIntent: 'Balance Colorado\'s altitude-boosted irradiance and cool temperatures against Front Range hail risk, impact ratings, and insurance considerations.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Is Solar Worth the Trouble in Cloudy, Cheap-Power Washington?',
        slug: 'solar-panels-in-washington',
        primaryKeyword: 'solar panels in washington state',
        secondaryKeywords: ['washington state solar', 'solar with low electricity rates'],
        searchIntent: 'Get an honest look at Washington, where cheap hydro electricity and persistent cloud cover stretch payback even though summers produce surprisingly well.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Oregon\'s Two Solar Climates: Gray Coast, Sunny High Desert',
        slug: 'solar-panels-in-oregon',
        primaryKeyword: 'solar panels in oregon',
        secondaryKeywords: ['oregon solar', 'portland vs bend solar production'],
        searchIntent: 'Compare solar production across Oregon\'s split personality, from the cloudy Willamette Valley to the high-desert east, and what that means for sizing.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Illinois Solar: Modest Sun, Unusually Strong Program Design',
        slug: 'solar-panels-in-illinois',
        primaryKeyword: 'solar panels in illinois',
        secondaryKeywords: ['illinois solar', 'illinois shines program structure'],
        searchIntent: 'Learn why Illinois punches above its sunshine thanks to state-administered renewable credit programs that pay based on expected production.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Panels in Ohio: A Case Study in Marginal Economics',
        slug: 'solar-panels-in-ohio',
        primaryKeyword: 'solar panels in ohio',
        secondaryKeywords: ['ohio solar', 'solar in low rate states'],
        searchIntent: 'Examine Ohio as the archetypal borderline market, where modest sun and lower electricity rates mean household usage patterns decide whether solar clears the bar.',
        relatedCalculators: ['solar-roi-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Pennsylvania Solar: What a Soft Certificate Market Means for You',
        slug: 'solar-panels-in-pennsylvania',
        primaryKeyword: 'solar panels in pennsylvania',
        secondaryKeywords: ['pennsylvania solar', 'pa solar renewable credits'],
        searchIntent: 'Understand Pennsylvania\'s solar picture, where a certificate market exists but trades soft, so bill offset and net metering carry most of the value.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Georgia Solar: Great Sun, Stingy Export Rules',
        slug: 'solar-panels-in-georgia',
        primaryKeyword: 'solar panels in georgia',
        secondaryKeywords: ['georgia solar', 'avoided cost solar exports'],
        searchIntent: 'See why Georgia\'s excellent sunshine is undercut by export compensation near wholesale avoided-cost levels, making self-consumption the key design goal.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Virginia\'s Solar Moment: Rising Demand, Capped Net Metering',
        slug: 'solar-panels-in-virginia',
        primaryKeyword: 'solar panels in virginia',
        secondaryKeywords: ['virginia solar', 'net metering caps virginia'],
        searchIntent: 'Explore Virginia\'s fast-growing market, where data-center-driven electricity demand pressures rates upward while net metering operates under program caps.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Michigan Solar: Snow Losses and the Inflow-Outflow Billing Model',
        slug: 'solar-panels-in-michigan',
        primaryKeyword: 'solar panels in michigan',
        secondaryKeywords: ['michigan solar', 'inflow outflow solar billing'],
        searchIntent: 'Learn how Michigan replaced classic net metering with inflow-outflow billing that credits exports below retail, and how lake-effect snow factors into production.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Minnesota Proves Cold Weather Is a Solar Feature, Not a Bug',
        slug: 'solar-panels-in-minnesota',
        primaryKeyword: 'solar panels in minnesota',
        secondaryKeywords: ['minnesota solar', 'value of solar tariff'],
        searchIntent: 'Discover why Minnesota\'s cold, clear winters boost panel efficiency and how the state pioneered value-of-solar pricing as an alternative to net metering.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Utah Solar: Dry Sun, Below-Retail Export Credits',
        slug: 'solar-panels-in-utah',
        primaryKeyword: 'solar panels in utah',
        secondaryKeywords: ['utah solar', 'rocky mountain power export credit'],
        searchIntent: 'Size a Utah system around excellent dry-climate sun and export credits set below retail, which reward matching production to daytime consumption.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'New Mexico: The Best Sun in America, and Smaller Systems to Match',
        slug: 'solar-panels-in-new-mexico',
        primaryKeyword: 'solar panels in new mexico',
        secondaryKeywords: ['new mexico solar', 'peak sun hours new mexico'],
        searchIntent: 'See how New Mexico\'s top-tier peak sun hours let homeowners hit the same output with noticeably fewer panels than nearly anywhere else in the country.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-size-calculator'],
      },
      {
        title: 'South Carolina Solar: Strong Sun in a Market Still Finding Its Rules',
        slug: 'solar-panels-in-south-carolina',
        primaryKeyword: 'solar panels in south carolina',
        secondaryKeywords: ['south carolina solar', 'sc net metering changes'],
        searchIntent: 'Track how South Carolina couples solid sunshine with a net metering framework that has been repeatedly renegotiated, and what that churn means for buyers.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Connecticut: Where Sky-High Electric Rates Do the Heavy Lifting',
        slug: 'solar-panels-in-connecticut',
        primaryKeyword: 'solar panels in connecticut',
        secondaryKeywords: ['connecticut solar', 'buy all vs netting tariff'],
        searchIntent: 'Understand why Connecticut\'s among-the-highest-in-the-nation electricity rates drive solar value, and how its buy-all versus netting tariff choice works.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Maryland Solar: A Mid-Atlantic Blend of Grants and Certificates',
        slug: 'solar-panels-in-maryland',
        primaryKeyword: 'solar panels in maryland',
        secondaryKeywords: ['maryland solar', 'maryland solar certificates'],
        searchIntent: 'Learn how Maryland stacks upfront grant-style support with an ongoing certificate market, a layered structure that changes how quickly systems recoup cost.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
    ],
  },
  {
    cluster: 'Off-grid, RV and tiny-home solar',
    category: 'Off-Grid & Mobile',
    entries: [
      {
        title: 'Grid-Tied vs. Off-Grid Solar: Two Very Different Machines',
        slug: 'grid-tied-vs-off-grid-solar',
        primaryKeyword: 'grid-tied vs off-grid solar',
        secondaryKeywords: ['off grid vs on grid solar', 'hybrid solar system explained'],
        searchIntent: 'Compare grid-tied, hybrid, and off-grid architectures to decide which model fits a home, cabin, or vehicle before sizing anything.',
        relatedCalculators: ['solar-panel-calculator', 'solar-battery-calculator'],
        pillar: true,
      },
      {
        title: 'Sizing an Off-Grid Solar System from Your Actual Load List',
        slug: 'off-grid-solar-system-sizing',
        primaryKeyword: 'off-grid solar system sizing',
        secondaryKeywords: ['off grid solar load calculation', 'how big should an off grid system be'],
        searchIntent: 'Build an off-grid system size from a written load list, daily watt-hours, and local sun hours instead of guessing from someone else\'s setup.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Battery Bank Sizing for Off-Grid Living: Days of Autonomy, Explained',
        slug: 'off-grid-battery-bank-sizing',
        primaryKeyword: 'off-grid battery bank sizing',
        secondaryKeywords: ['days of autonomy solar', 'battery bank capacity calculation'],
        searchIntent: 'Size an off-grid battery bank around days of autonomy, depth of discharge, and chemistry differences so cloudy stretches do not leave you dark.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Your First RV Solar Setup: How Much Is Actually Enough?',
        slug: 'rv-solar-starter-sizing',
        primaryKeyword: 'how much solar do i need for my rv',
        secondaryKeywords: ['rv solar system sizing', 'rv solar for beginners'],
        searchIntent: 'Size a first RV solar setup from real appliance draws and travel style rather than defaulting to whatever kit is on sale.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'RV Roof-Mounted vs. Portable Panels: Pick Your Trade-Off',
        slug: 'rv-roof-vs-portable-solar-panels',
        primaryKeyword: 'rv roof mounted vs portable solar panels',
        secondaryKeywords: ['fixed vs portable rv solar', 'suitcase solar panels for rv'],
        searchIntent: 'Decide between permanently roof-mounted RV panels and portable suitcase panels by weighing shade flexibility, setup effort, theft risk, and roof space.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Van Conversion Solar: Wiring a Tiny Power Plant on Wheels',
        slug: 'van-conversion-solar-basics',
        primaryKeyword: 'van conversion solar',
        secondaryKeywords: ['camper van solar setup', 'van life electrical system'],
        searchIntent: 'Plan a van build\'s electrical system end to end, from limited roof real estate and alternator charging to safe fusing and wire gauge.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Tiny Home Solar: Small Roof, Full-Size Expectations',
        slug: 'tiny-home-solar',
        primaryKeyword: 'tiny house solar',
        secondaryKeywords: ['tiny home solar system', 'solar for small dwellings'],
        searchIntent: 'Design solar for a tiny home where the roof is small but occupants still expect refrigeration, laundry, and heat, forcing careful load prioritization.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-battery-calculator'],
      },
      {
        title: 'Solar for a Seasonal Cabin: Power That Waits for You',
        slug: 'off-grid-cabin-solar',
        primaryKeyword: 'off grid cabin solar',
        secondaryKeywords: ['cabin solar system', 'seasonal solar setup'],
        searchIntent: 'Set up cabin solar for intermittent, seasonal use, covering battery storage during long absences, freeze protection, and modest weekend loads.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Generators vs. Building Your Own Panel-and-Battery System',
        slug: 'solar-generators-vs-panel-systems',
        primaryKeyword: 'solar generator vs solar panels',
        secondaryKeywords: ['all in one power station vs diy solar', 'portable power station comparison'],
        searchIntent: 'Compare all-in-one solar generators against component-built panel-plus-battery systems on cost per watt-hour, expandability, and repairability.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: '12V, 24V, or 48V? Choosing a System Voltage That Scales',
        slug: '12v-vs-24v-vs-48v-solar-systems',
        primaryKeyword: '12v vs 24v vs 48v solar',
        secondaryKeywords: ['solar system voltage selection', 'best voltage for off grid solar'],
        searchIntent: 'Choose a system voltage by understanding how higher voltage cuts current, wire cost, and losses, and where each tier stops making sense.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'PWM vs. MPPT Charge Controllers: When the Cheap One Is Fine',
        slug: 'pwm-vs-mppt-charge-controllers',
        primaryKeyword: 'pwm vs mppt charge controller',
        secondaryKeywords: ['mppt charge controller explained', 'solar charge controller types'],
        searchIntent: 'Understand what a charge controller actually does and when MPPT\'s harvest advantage justifies its price over a basic PWM unit.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Surviving Winter Off-Grid: Strategies for the Darkest Months',
        slug: 'off-grid-solar-winter-strategies',
        primaryKeyword: 'off grid solar in winter',
        secondaryKeywords: ['winter solar production off grid', 'steep tilt solar winter'],
        searchIntent: 'Get through the low-sun months off-grid using steeper tilt angles, oversized arrays, generator backup discipline, and load shedding.',
        relatedCalculators: ['solar-battery-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Shore Power Plus Solar: The Hybrid RV Setup Most People Want',
        slug: 'rv-shore-power-and-solar-hybrid',
        primaryKeyword: 'rv shore power and solar',
        secondaryKeywords: ['hybrid rv electrical setup', 'rv solar with hookups'],
        searchIntent: 'Combine campground shore power with rooftop solar so an RV charges opportunistically, prioritizes the right source, and stays flexible off hookups.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Portable Solar Panels for Camping: What Real-World Output Looks Like',
        slug: 'portable-solar-panels-for-camping',
        primaryKeyword: 'portable solar panels for camping',
        secondaryKeywords: ['folding solar panels camping', 'camping solar charger sizing'],
        searchIntent: 'Set realistic expectations for portable camping panels, whose rated watts rarely survive contact with haze, angle, and short charging windows.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Is Living Off-Grid Even Legal? Permits, Codes, and Gray Areas',
        slug: 'off-grid-solar-permitting-legality',
        primaryKeyword: 'is off grid solar legal',
        secondaryKeywords: ['off grid living laws', 'solar permitting requirements off grid'],
        searchIntent: 'Sort out where off-grid solar sits legally, from electrical code and permitting requirements to jurisdictions that mandate a utility connection.',
        relatedCalculators: ['solar-panel-calculator'],
      },
    ],
  },
  {
    cluster: 'Solar myths, comparisons and FAQs',
    category: 'Myths & Comparisons',
    entries: [
      {
        title: 'The Cloudy-Day Myth: What Solar Panels Really Do Without Direct Sun',
        slug: 'do-solar-panels-work-on-cloudy-days',
        primaryKeyword: 'do solar panels work on cloudy days',
        secondaryKeywords: ['solar panels in cloudy weather', 'solar output on overcast days'],
        searchIntent: 'Debunk the belief that clouds shut solar down by explaining diffuse-light production and what overcast output typically looks like as a share of peak.',
        relatedCalculators: ['solar-panel-calculator'],
        pillar: true,
      },
      {
        title: 'Solar Panels Sleep at Night. Your Lights Stay On Anyway. Here\'s How.',
        slug: 'do-solar-panels-work-at-night',
        primaryKeyword: 'do solar panels work at night',
        secondaryKeywords: ['how solar homes get power at night', 'solar at night explained'],
        searchIntent: 'Explain that panels produce nothing after dark and walk through how net metering credits and home batteries keep a solar home powered overnight.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Cold Climates Don\'t Kill Solar — They Quietly Help It',
        slug: 'solar-panels-in-cold-climates',
        primaryKeyword: 'solar panels in cold climates',
        secondaryKeywords: ['do solar panels work in winter', 'cold weather solar efficiency'],
        searchIntent: 'Bust the warm-states-only myth by showing how cold temperatures raise panel efficiency and why snow reflection can boost clear-day output.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Will Solar Panels Wreck Your Roof? The Evidence Says Otherwise',
        slug: 'does-solar-damage-your-roof',
        primaryKeyword: 'does solar damage your roof',
        secondaryKeywords: ['solar panel roof damage myth', 'solar panels protect roof'],
        searchIntent: 'Address the roof-damage fear by explaining flashed mounting, how panels shield shingles from weather, and when a roof genuinely should be replaced first.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Solar and Home Insurance: Separating Policy Facts from Forum Panic',
        slug: 'solar-panels-and-home-insurance',
        primaryKeyword: 'solar panels and home insurance',
        secondaryKeywords: ['does solar raise home insurance', 'insuring rooftop solar'],
        searchIntent: 'Clear up how rooftop solar is typically treated under homeowners policies, what to disclose, and which coverage myths circulate in owner forums.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Do Solar Panels Cause Fires? The Actual Risk, in Context',
        slug: 'do-solar-panels-cause-fires',
        primaryKeyword: 'do solar panels cause fires',
        secondaryKeywords: ['solar panel fire risk', 'rapid shutdown solar safety'],
        searchIntent: 'Put solar fire risk in statistical context, explain the failure modes that matter (connectors, DC arcing), and the code safeguards built against them.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Solar or a Generator for Outages? They Solve Different Problems',
        slug: 'solar-vs-generator-for-outages',
        primaryKeyword: 'solar vs generator for power outages',
        secondaryKeywords: ['solar battery backup vs generator', 'home backup power comparison'],
        searchIntent: 'Compare battery-backed solar against fuel generators for outage resilience on runtime, fuel logistics, noise, and everyday value between blackouts.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'DIY Solar Kits vs. Professional Installation: An Honest Ledger',
        slug: 'diy-solar-kits-vs-professional-installation',
        primaryKeyword: 'diy solar vs professional installation',
        secondaryKeywords: ['diy solar kit review considerations', 'self install solar risks'],
        searchIntent: 'Tally the true DIY-versus-pro trade, including permitting, interconnection paperwork, warranty coverage, and the labor share of installed cost.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Thin-Film vs. Crystalline Panels: Why Rooftops Picked a Winner',
        slug: 'thin-film-vs-crystalline-solar-panels',
        primaryKeyword: 'thin film vs crystalline solar panels',
        secondaryKeywords: ['thin film solar for homes', 'monocrystalline vs thin film'],
        searchIntent: 'Compare thin-film and crystalline technologies on efficiency, space needs, and degradation to show why crystalline dominates residential roofs.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Those "Free Solar Panels" Ads: What You\'re Actually Signing',
        slug: 'free-solar-panels-offers-debunked',
        primaryKeyword: 'free solar panels',
        secondaryKeywords: ['no cost solar program truth', 'solar lease vs ppa fine print'],
        searchIntent: 'Decode "free solar" marketing by showing how leases and power purchase agreements actually work, who owns the system, and where the catch lives.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
    ],
  },
];
