// SEO topic plan for SunMetricLab (sunmetriclab.com) — clusters A
// US homeowner audience. Topics only; no articles.

export const clusters = [
  {
    cluster: 'Solar panel costs',
    category: 'Solar Costs',
    entries: [
      {
        title: 'Where Your Solar Installation Money Actually Goes',
        slug: 'solar-installation-cost-breakdown',
        primaryKeyword: 'solar installation cost breakdown',
        secondaryKeywords: ['solar panel cost breakdown', 'what makes up solar cost', 'solar system price components'],
        searchIntent: 'Understand every component of a residential solar price, from hardware to overhead.',
        relatedCalculators: ['solar-panel-cost-calculator'],
        pillar: true,
      },
      {
        title: 'Cost per Watt: The Number That Makes Solar Quotes Comparable',
        slug: 'solar-cost-per-watt',
        primaryKeyword: 'solar cost per watt',
        secondaryKeywords: ['price per watt solar', 'cost per watt installed', 'dollars per watt solar'],
        searchIntent: 'Learn what cost per watt means and how to use it to compare solar quotes.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How Much Does a 4 kW Solar System Cost?',
        slug: '4kw-solar-system-cost',
        primaryKeyword: '4kw solar system cost',
        secondaryKeywords: ['4 kw solar price', '4kw solar panel system cost', 'cost of 4kw solar'],
        searchIntent: 'Find the typical installed price range for a 4 kW home solar system.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'What a 6 kW Solar System Really Costs a Typical Home',
        slug: '6kw-solar-system-cost',
        primaryKeyword: '6kw solar system cost',
        secondaryKeywords: ['6 kw solar price', '6kw solar panel system cost', 'cost of 6kw solar'],
        searchIntent: 'Find the typical installed price range for a 6 kW home solar system.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: '8 kW Solar Systems: Pricing for Larger Households',
        slug: '8kw-solar-system-cost',
        primaryKeyword: '8kw solar system cost',
        secondaryKeywords: ['8 kw solar price', '8kw solar panel system cost', 'cost of 8kw solar'],
        searchIntent: 'Find the typical installed price range for an 8 kW home solar system.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Is a 10 kW Solar System Overkill? What It Costs and Who Needs One',
        slug: '10kw-solar-system-cost',
        primaryKeyword: '10kw solar system cost',
        secondaryKeywords: ['10 kw solar price', '10kw solar panel system cost', 'cost of 10kw solar'],
        searchIntent: 'Find the typical installed price of a 10 kW system and whether that size fits their home.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: '12 kW Solar Systems: Big-Home Pricing Explained',
        slug: '12kw-solar-system-cost',
        primaryKeyword: '12kw solar system cost',
        secondaryKeywords: ['12 kw solar price', '12kw solar panel system cost', 'cost of 12kw solar'],
        searchIntent: 'Find the typical installed price range for a 12 kW home solar system.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: "Solar Installation Labor: What You're Paying the Crew For",
        slug: 'solar-installation-labor-cost',
        primaryKeyword: 'solar installation labor cost',
        secondaryKeywords: ['solar labor cost per watt', 'solar installer labor rates', 'labor share of solar cost'],
        searchIntent: 'See how much of a solar price is labor and what that work actually involves.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "Soft Costs: Why Half Your Solar Bill Isn't Hardware",
        slug: 'solar-soft-costs',
        primaryKeyword: 'solar soft costs',
        secondaryKeywords: ['solar soft costs explained', 'non hardware solar costs', 'solar overhead costs'],
        searchIntent: 'Understand the sales, permitting, and overhead expenses hidden inside a solar price.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Permit Fees and Paperwork Costs, Explained',
        slug: 'solar-permit-costs',
        primaryKeyword: 'solar permit cost',
        secondaryKeywords: ['solar permit fees', 'solar permitting costs', 'interconnection application fees'],
        searchIntent: 'Learn what permits a solar install requires and what those fees typically add.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'How Your Roof Type Changes What Solar Costs to Install',
        slug: 'solar-installation-cost-by-roof-type',
        primaryKeyword: 'solar installation cost by roof type',
        secondaryKeywords: ['solar cost metal roof vs shingle', 'tile roof solar installation cost', 'roof material solar price'],
        searchIntent: 'Compare how shingle, tile, metal, and flat roofs change installation pricing.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Why Solar Quotes for the Same House Can Differ by Thousands',
        slug: 'why-solar-quotes-vary',
        primaryKeyword: 'why solar quotes vary',
        secondaryKeywords: ['solar quote differences', 'comparing solar quotes', 'solar quote price gap'],
        searchIntent: 'Understand why installers quote such different prices for an identical project.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Reading a Solar Quote Line by Line',
        slug: 'how-to-read-a-solar-quote',
        primaryKeyword: 'how to read a solar quote',
        secondaryKeywords: ['solar proposal explained', 'understanding a solar quote', 'solar quote line items'],
        searchIntent: 'Decode each line item on a solar proposal before signing anything.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Hidden Solar Costs Your Installer Might Not Mention',
        slug: 'hidden-costs-of-solar-panels',
        primaryKeyword: 'hidden costs of solar panels',
        secondaryKeywords: ['unexpected solar costs', 'extra solar installation fees', 'solar cost surprises'],
        searchIntent: 'Spot the add-on expenses that quotes often leave out, like upgrades and adders.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "Can You Negotiate a Solar Quote? Yes — Here's How",
        slug: 'how-to-negotiate-solar-price',
        primaryKeyword: 'negotiate solar panel price',
        secondaryKeywords: ['negotiating solar quotes', 'lower solar installation price', 'solar price negotiation tips'],
        searchIntent: 'Get tactics for bargaining a solar quote down without sacrificing quality.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "What a Solar Loan Really Adds to Your System's Price",
        slug: 'solar-loan-true-cost',
        primaryKeyword: 'solar loan cost',
        secondaryKeywords: ['solar loan fees', 'solar financing dealer fees', 'true cost of financing solar'],
        searchIntent: 'See how interest and dealer fees inflate the total cost of a financed system.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Leasing vs Buying Solar Panels: The Cost Difference',
        slug: 'solar-lease-vs-buy-cost',
        primaryKeyword: 'solar lease vs buy',
        secondaryKeywords: ['leasing solar panels vs buying', 'solar lease cost comparison', 'buy or lease solar'],
        searchIntent: 'Compare the long-run cost of leasing panels against owning them outright.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Solar PPAs: Paying for Power Instead of Panels',
        slug: 'solar-ppa-costs-explained',
        primaryKeyword: 'solar ppa cost',
        secondaryKeywords: ['power purchase agreement solar', 'solar ppa rates', 'ppa vs owning solar'],
        searchIntent: 'Understand how a power purchase agreement prices electricity and escalates over time.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "DIY Solar: What You'd Actually Save on Installation",
        slug: 'diy-solar-cost-savings',
        primaryKeyword: 'diy solar cost',
        secondaryKeywords: ['diy solar panel installation cost', 'self install solar savings', 'diy vs professional solar cost'],
        searchIntent: 'Weigh the real dollar savings of a self-installed system against the risks.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: "Solar for Small Homes: Costs When You Don't Need Much",
        slug: 'solar-cost-small-house',
        primaryKeyword: 'solar cost for small house',
        secondaryKeywords: ['small home solar system price', 'solar panels for small house cost', 'small solar system cost'],
        searchIntent: 'Find out what a modest system costs when a small home has low usage.',
        relatedCalculators: ['solar-panel-cost-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Solar Cost per Square Foot Is a Misleading Metric — Use This Instead',
        slug: 'solar-cost-per-square-foot',
        primaryKeyword: 'solar panel cost per square foot',
        secondaryKeywords: ['solar cost by home size', 'solar price per square foot', 'solar cost 2000 sq ft home'],
        searchIntent: 'Translate a home\'s square footage into a realistic solar cost estimate.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Ground-Mounted Solar: Why It Costs More Than Rooftop',
        slug: 'ground-mount-solar-cost',
        primaryKeyword: 'ground mount solar cost',
        secondaryKeywords: ['ground mounted solar price', 'ground mount vs roof mount cost', 'ground mount racking cost'],
        searchIntent: 'Compare ground-mount pricing to rooftop and see what drives the premium.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Carports: Pricing a Panel-Topped Parking Spot',
        slug: 'solar-carport-cost',
        primaryKeyword: 'solar carport cost',
        secondaryKeywords: ['residential solar carport price', 'solar carport vs roof cost', 'solar pergola cost'],
        searchIntent: 'Learn what a residential solar carport structure adds over a standard install.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Shingles vs Panels: A Cost Comparison',
        slug: 'solar-shingles-vs-panels-cost',
        primaryKeyword: 'solar shingles cost',
        secondaryKeywords: ['solar roof shingles price', 'solar shingles vs solar panels cost', 'building integrated solar cost'],
        searchIntent: 'Compare solar shingle pricing to conventional panels and decide which fits.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Bifacial Panels: Is the Price Premium Worth It on a Home?',
        slug: 'bifacial-solar-panel-cost',
        primaryKeyword: 'bifacial solar panel cost',
        secondaryKeywords: ['bifacial vs monofacial cost', 'bifacial panel price premium', 'are bifacial panels worth it'],
        searchIntent: 'Judge whether bifacial panels justify their extra cost in residential setups.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Premium vs Budget Solar Panels: What the Price Gap Buys',
        slug: 'premium-vs-budget-solar-panels',
        primaryKeyword: 'premium vs budget solar panels',
        secondaryKeywords: ['cheap vs expensive solar panels', 'high end solar panel price difference', 'are premium solar panels worth it'],
        searchIntent: 'Decide whether higher-tier panels are worth paying more for than value brands.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Used Solar Panels: Bargain or False Economy?',
        slug: 'used-solar-panels-cost',
        primaryKeyword: 'used solar panels cost',
        secondaryKeywords: ['buying used solar panels', 'second hand solar panel prices', 'refurbished solar panels'],
        searchIntent: 'Evaluate the savings and pitfalls of buying secondhand panels.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'The Cost of Adding Panels to an Existing Solar System',
        slug: 'cost-to-add-solar-panels-existing-system',
        primaryKeyword: 'cost to add solar panels to existing system',
        secondaryKeywords: ['expanding solar system cost', 'adding more solar panels price', 'solar system expansion cost'],
        searchIntent: 'Learn what an expansion costs and why per-panel pricing is worse the second time.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Removing and Reinstalling Solar Panels for a New Roof',
        slug: 'solar-panel-removal-reinstallation-cost',
        primaryKeyword: 'solar panel removal and reinstallation cost',
        secondaryKeywords: ['remove solar panels for roof replacement', 'solar detach and reset cost', 'solar panel r&r cost'],
        searchIntent: 'Budget for taking panels off and putting them back during roof work.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Why Solar Keeps Getting Cheaper — and What Could Change That',
        slug: 'solar-panel-price-trends',
        primaryKeyword: 'solar panel price trends',
        secondaryKeywords: ['solar cost decline over time', 'will solar prices keep falling', 'solar price history'],
        searchIntent: 'Understand the long-term forces pushing solar prices down and possible reversals.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
    ],
  },
  {
    cluster: 'Solar savings and ROI',
    category: 'Savings & ROI',
    entries: [
      {
        title: 'How Much Do Solar Panels Actually Save You?',
        slug: 'how-much-do-solar-panels-save',
        primaryKeyword: 'how much do solar panels save',
        secondaryKeywords: ['solar panel savings per month', 'average solar savings', 'do solar panels save money'],
        searchIntent: 'Get a realistic picture of monthly and yearly savings from a home solar system.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
        pillar: true,
      },
      {
        title: 'Estimate Your Solar Savings in Five Steps',
        slug: 'estimate-solar-savings-step-by-step',
        primaryKeyword: 'how to estimate solar savings',
        secondaryKeywords: ['calculate solar savings', 'solar savings estimate method', 'diy solar savings estimate'],
        searchIntent: 'Follow a step-by-step method to estimate their own savings before getting quotes.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'What Solar Saves on a $100 Monthly Electric Bill',
        slug: 'solar-savings-100-dollar-bill',
        primaryKeyword: 'solar savings on 100 dollar electric bill',
        secondaryKeywords: ['is solar worth it with a low bill', 'solar for 100 a month electric bill', 'small electric bill solar'],
        searchIntent: 'See whether solar makes financial sense for a household with a low $100 bill.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar Savings When Your Electric Bill Runs $200 a Month',
        slug: 'solar-savings-200-dollar-bill',
        primaryKeyword: 'solar savings on 200 dollar electric bill',
        secondaryKeywords: ['solar for 200 a month electric bill', 'solar panels 200 monthly bill', 'average bill solar savings'],
        searchIntent: 'Estimate the savings a typical $200-a-month household can expect from solar.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'A $300 Electric Bill Is Where Solar Gets Interesting',
        slug: 'solar-savings-300-dollar-bill',
        primaryKeyword: 'solar savings on 300 dollar electric bill',
        secondaryKeywords: ['solar for 300 a month electric bill', 'high electric bill solar savings', 'solar panels 300 monthly bill'],
        searchIntent: 'Understand how much a high-usage $300-a-month home stands to save with solar.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: "Why Your Electric Bill Isn't $0 After Going Solar",
        slug: 'electric-bill-after-solar',
        primaryKeyword: 'electric bill after solar',
        secondaryKeywords: ['why do i still have an electric bill with solar', 'solar fixed charges', 'minimum bill with solar'],
        searchIntent: 'Learn which fixed charges and fees remain on the bill after panels are installed.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Net Metering, Explained for Homeowners',
        slug: 'net-metering-explained',
        primaryKeyword: 'what is net metering',
        secondaryKeywords: ['how net metering works', 'net metering credits', 'net metering for homeowners'],
        searchIntent: 'Understand how net metering credits work and how they shape solar savings.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Net Billing vs Net Metering: Why the Difference Matters',
        slug: 'net-billing-vs-net-metering',
        primaryKeyword: 'net billing vs net metering',
        secondaryKeywords: ['net billing explained', 'difference between net billing and net metering', 'net billing solar savings'],
        searchIntent: 'Compare the two compensation schemes and see how net billing shrinks savings.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar Export Rates: What Your Utility Pays for Extra Power',
        slug: 'solar-export-rates',
        primaryKeyword: 'solar export rates',
        secondaryKeywords: ['solar buyback rates', 'excess solar compensation', 'utility export credit'],
        searchIntent: 'Find out how utilities value exported solar power and why rates differ from retail.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Time-of-Use Rates and Solar: When You Use Power Is Money',
        slug: 'time-of-use-rates-solar',
        primaryKeyword: 'time of use rates and solar',
        secondaryKeywords: ['tou rates solar savings', 'solar on time of use plan', 'peak rates and solar'],
        searchIntent: 'Learn how time-of-use pricing changes solar savings and how to adapt usage.',
        relatedCalculators: ['solar-roi-calculator', 'solar-battery-calculator'],
      },
      {
        title: "The Annual True-Up Bill: Solar's Year-End Reckoning",
        slug: 'solar-true-up-bill',
        primaryKeyword: 'solar true up bill',
        secondaryKeywords: ['what is a true up statement', 'annual solar settlement bill', 'true up charges explained'],
        searchIntent: 'Understand why a year-end true-up statement arrives and how to avoid a surprise balance.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Net Metering Grandfathering: Locking In the Deal You Signed Up For',
        slug: 'net-metering-grandfathering',
        primaryKeyword: 'net metering grandfathering',
        secondaryKeywords: ['grandfathered solar rates', 'net metering policy changes', 'keeping old net metering terms'],
        searchIntent: 'Learn whether existing solar customers keep their terms when net metering rules change.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Can Solar Still Save Money Without Net Metering?',
        slug: 'solar-savings-without-net-metering',
        primaryKeyword: 'solar savings without net metering',
        secondaryKeywords: ['solar self consumption savings', 'no net metering is solar worth it', 'solar without export credits'],
        searchIntent: 'See how self-consumption alone drives savings where net metering is unavailable.',
        relatedCalculators: ['solar-roi-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Why Solar Savings Swing With the Seasons',
        slug: 'seasonal-solar-savings',
        primaryKeyword: 'solar savings by season',
        secondaryKeywords: ['solar production winter vs summer savings', 'seasonal solar bill changes', 'monthly solar savings variation'],
        searchIntent: 'Understand why solar bills fluctuate through the year and how annual banking evens it out.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Do Solar Panels Pay Off in Cloudy Climates?',
        slug: 'solar-savings-cloudy-climates',
        primaryKeyword: 'do solar panels save money in cloudy climates',
        secondaryKeywords: ['solar in cloudy areas worth it', 'solar savings low sun regions', 'overcast climate solar savings'],
        searchIntent: 'Judge whether solar remains financially sound in regions with limited sunshine.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Calculating Solar ROI Like an Investor',
        slug: 'how-to-calculate-solar-roi',
        primaryKeyword: 'how to calculate solar roi',
        secondaryKeywords: ['solar return on investment formula', 'solar roi percentage', 'solar investment return math'],
        searchIntent: 'Compute solar return on investment as an annualized rate they can compare to other investments.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Lifetime Solar Savings vs Monthly Savings: Two Ways to Count',
        slug: 'lifetime-vs-monthly-solar-savings',
        primaryKeyword: 'lifetime solar savings',
        secondaryKeywords: ['25 year solar savings', 'total solar savings over time', 'long term solar savings'],
        searchIntent: 'Reconcile modest monthly savings with the large lifetime figures installers advertise.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Panel Degradation Quietly Reshapes Your Savings — Here Is the Math',
        slug: 'solar-panel-degradation-savings',
        primaryKeyword: 'solar panel degradation and savings',
        secondaryKeywords: ['solar output loss over time', 'degradation rate savings impact', 'year 25 solar production'],
        searchIntent: 'Quantify how gradual output loss reduces savings across a system\'s life.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar as a Hedge Against Rising Electricity Rates',
        slug: 'solar-hedge-rising-electricity-rates',
        primaryKeyword: 'solar hedge against rising electricity rates',
        secondaryKeywords: ['electricity rate inflation and solar', 'locking in energy costs with solar', 'utility rate increases solar savings'],
        searchIntent: 'See how locking in solar production protects against future utility rate hikes.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'What Does a 100% Solar Offset Actually Mean for Your Bill?',
        slug: 'solar-offset-explained',
        primaryKeyword: 'solar offset meaning',
        secondaryKeywords: ['100 percent solar offset', 'solar offset percentage', 'usage offset vs bill offset'],
        searchIntent: 'Understand offset percentages in proposals and why 100% offset rarely means a zero bill.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'The Real Savings Math Behind $0-Down Solar Deals',
        slug: 'zero-down-solar-savings-math',
        primaryKeyword: 'zero down solar savings',
        secondaryKeywords: ['no money down solar worth it', '$0 down solar deals', 'zero down solar monthly savings'],
        searchIntent: 'Check whether a no-money-down offer truly leaves them ahead each month.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Charging an EV With Solar: What It Does to Your Savings',
        slug: 'ev-charging-solar-savings',
        primaryKeyword: 'ev charging with solar savings',
        secondaryKeywords: ['charge electric car with solar panels', 'solar ev charging cost', 'ev plus solar savings'],
        searchIntent: 'Estimate how home solar cuts the cost of charging an electric vehicle.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Heat Pumps and Solar: A Savings Multiplier for Electric Homes',
        slug: 'heat-pump-solar-savings',
        primaryKeyword: 'heat pump with solar panels savings',
        secondaryKeywords: ['solar powered heat pump savings', 'electrify heating with solar', 'heat pump plus solar combo'],
        searchIntent: 'See how pairing a heat pump with solar compounds savings on heating and cooling.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: "Do Solar Panels Raise Your Home's Value?",
        slug: 'solar-panels-home-value',
        primaryKeyword: 'solar panels home value',
        secondaryKeywords: ['do solar panels increase home value', 'solar home value premium', 'solar resale value'],
        searchIntent: 'Learn what research says about the resale premium solar adds to a house.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'How Appraisers Actually Value Solar Panels on a Home',
        slug: 'solar-panel-home-appraisal',
        primaryKeyword: 'solar panel home appraisal',
        secondaryKeywords: ['appraising a home with solar', 'solar appraisal value', 'pv value appraisal method'],
        searchIntent: 'Understand the appraisal process and how a solar system gets valued in it.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Selling a House With Solar Panels: What to Expect',
        slug: 'selling-house-with-solar-panels',
        primaryKeyword: 'selling a house with solar panels',
        secondaryKeywords: ['sell home with solar', 'solar panels when selling house', 'listing a solar home'],
        searchIntent: 'Prepare as a seller for how solar affects listing, negotiation, and closing.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Buying a Home That Already Has Solar Panels',
        slug: 'buying-house-with-solar-panels',
        primaryKeyword: 'buying a house with solar panels',
        secondaryKeywords: ['home with existing solar', 'questions to ask buying solar home', 'inherited solar system'],
        searchIntent: 'Know what to check as a buyer before purchasing a home with an existing system.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Owned vs Leased Solar: The Home Value Difference',
        slug: 'leased-solar-panels-home-value',
        primaryKeyword: 'leased solar panels and home value',
        secondaryKeywords: ['do leased solar panels add value', 'solar lease home sale problems', 'owned vs leased solar resale'],
        searchIntent: 'Learn why ownership status decides whether panels help or complicate a sale.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Community Solar: Savings Without Putting Anything on Your Roof',
        slug: 'community-solar-savings',
        primaryKeyword: 'community solar savings',
        secondaryKeywords: ['how much does community solar save', 'community solar subscription worth it', 'shared solar savings'],
        searchIntent: 'Find out how much a community solar subscription can trim from an electric bill.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar Savings for Renters: Your Real Options',
        slug: 'solar-savings-for-renters',
        primaryKeyword: 'solar for renters',
        secondaryKeywords: ['can renters get solar', 'renter solar options', 'apartment solar savings'],
        searchIntent: 'Discover the practical ways a renter can capture solar savings without owning a roof.',
        relatedCalculators: ['solar-roi-calculator'],
      },
    ],
  },
];
