// SEO topic plan — batch D
// Clusters: Installation (20), Maintenance & Lifespan (20), Incentives & Tax Credits (15)
// Note: incentive articles must be written time-stably; topics below avoid
// asserting any specific currently-active state program.

export const clusters = [
  {
    cluster: 'Installation and contractor selection',
    category: 'Installation',
    entries: [
      {
        title: "Choosing a Solar Installer: A Homeowner's Complete Vetting Guide",
        slug: 'choosing-a-solar-installer',
        primaryKeyword: 'how to choose a solar installer',
        secondaryKeywords: ['best solar installer near me', 'solar company vetting', 'picking a solar contractor'],
        searchIntent: 'A homeowner starting their solar journey wants a trustworthy framework for evaluating and selecting an installation company.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
        pillar: true,
      },
      {
        title: 'Comparing Solar Quotes Line by Line: What Actually Matters',
        slug: 'compare-solar-quotes',
        primaryKeyword: 'compare solar quotes',
        secondaryKeywords: ['solar quote comparison', 'how to read a solar proposal'],
        searchIntent: 'A shopper holding multiple solar proposals wants to know which line items and metrics to compare apples-to-apples.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Questions to Ask Solar Installers Before You Sign Anything',
        slug: 'questions-to-ask-solar-installers',
        primaryKeyword: 'questions to ask solar installers',
        secondaryKeywords: ['solar installer interview questions', 'what to ask a solar company'],
        searchIntent: 'A homeowner preparing for sales meetings wants a checklist of pointed questions that reveal installer quality.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'National Solar Companies vs Local Installers: Which Serves You Better?',
        slug: 'national-vs-local-solar-installers',
        primaryKeyword: 'national vs local solar companies',
        secondaryKeywords: ['big solar companies vs local installers', 'regional solar installer pros and cons'],
        searchIntent: 'A buyer torn between a big-brand solar company and a local contractor wants an honest trade-off comparison.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'The Solar Installation Timeline, From Signed Contract to Switch-On',
        slug: 'solar-installation-timeline',
        primaryKeyword: 'solar installation timeline',
        secondaryKeywords: ['how long does solar installation take', 'solar project timeline stages'],
        searchIntent: 'Someone who just signed a solar contract wants to know each stage ahead and how many weeks the whole process takes.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Solar Permits and Inspections: Who Handles What, and When',
        slug: 'solar-permits-and-inspections',
        primaryKeyword: 'solar panel permits and inspections',
        secondaryKeywords: ['solar permitting process', 'solar final inspection'],
        searchIntent: 'A homeowner wants to understand the permitting and inspection steps their installer manages and what could delay approval.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Grid Interconnection: The Utility Approval That Lets Your Panels Earn',
        slug: 'solar-interconnection-process',
        primaryKeyword: 'solar interconnection process',
        secondaryKeywords: ['permission to operate solar', 'utility interconnection application'],
        searchIntent: 'A new solar owner waiting on their utility wants to know how interconnection and permission to operate actually work.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar Installation Day: What Happens, Hour by Hour',
        slug: 'solar-installation-day',
        primaryKeyword: 'what happens on solar installation day',
        secondaryKeywords: ['solar panel install day', 'do I need to be home for solar installation'],
        searchIntent: 'A homeowner with an install date booked wants to know exactly what the crew will do and how to prepare their home.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'The Solar Site Survey: Why It Can Change Your Quote',
        slug: 'solar-site-survey',
        primaryKeyword: 'solar site survey',
        secondaryKeywords: ['solar site assessment', 'what happens during a solar survey'],
        searchIntent: 'A buyer scheduled for a site survey wants to know what surveyors check and why the final design or price may shift afterward.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Solar Sales Tactics That Should Make You Pause',
        slug: 'solar-sales-tactics-red-flags',
        primaryKeyword: 'solar sales tactics',
        secondaryKeywords: ['solar scams to avoid', 'high pressure solar sales red flags'],
        searchIntent: 'A homeowner fielding aggressive solar pitches wants to recognize manipulative sales techniques and misleading claims.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar Contract Terms to Read Twice Before Signing',
        slug: 'solar-contract-terms',
        primaryKeyword: 'solar contract terms to check',
        secondaryKeywords: ['solar agreement fine print', 'what to look for in a solar contract'],
        searchIntent: 'Someone about to sign a solar agreement wants a plain-English walkthrough of clauses that commonly cause disputes.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Workmanship vs Equipment Warranties: Who Fixes What on Your Roof',
        slug: 'solar-workmanship-vs-equipment-warranty',
        primaryKeyword: 'solar workmanship warranty',
        secondaryKeywords: ['solar equipment warranty explained', 'solar installer warranty coverage'],
        searchIntent: 'A buyer comparing proposals wants to understand the difference between installer workmanship and manufacturer equipment warranties.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'NABCEP Certification: Does It Matter Who Installs Your Panels?',
        slug: 'nabcep-certification-explained',
        primaryKeyword: 'NABCEP certified solar installer',
        secondaryKeywords: ['solar installer certifications', 'what is NABCEP'],
        searchIntent: 'A homeowner seeing NABCEP badges on installer websites wants to know what the certification proves and how much weight to give it.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'When Solar Companies Subcontract the Install: Risks and Questions',
        slug: 'solar-installer-subcontracting',
        primaryKeyword: 'solar installer subcontracting',
        secondaryKeywords: ['solar company uses subcontractors', 'in-house vs subcontracted solar crews'],
        searchIntent: 'A buyer who learned their installer outsources labor wants to understand the risks and how to hold the seller accountable.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Commissioning: The Final Checks Before Your System Goes Live',
        slug: 'solar-system-commissioning',
        primaryKeyword: 'solar system commissioning',
        secondaryKeywords: ['solar commissioning checklist', 'post-install solar testing'],
        searchIntent: 'A new owner nearing activation wants to know what commissioning tests verify and what documentation to collect.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Change Orders on a Solar Project: When Extra Costs Are Legitimate',
        slug: 'solar-change-orders',
        primaryKeyword: 'solar change orders',
        secondaryKeywords: ['solar installation unexpected costs', 'solar contract price changes'],
        searchIntent: 'A homeowner hit with a mid-project price change wants to judge whether the added charge is justified and how to respond.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Cancelling a Solar Contract: Your Rights and the Fine Print',
        slug: 'cancel-solar-contract',
        primaryKeyword: 'how to cancel a solar contract',
        secondaryKeywords: ['solar contract cancellation period', 'backing out of a solar agreement'],
        searchIntent: 'Someone with signer’s remorse wants to know their cancellation rights, deadlines, and potential penalties.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Reading Solar Installer Reviews Like a Pro (and Spotting Fakes)',
        slug: 'vetting-solar-installer-reviews',
        primaryKeyword: 'solar installer reviews',
        secondaryKeywords: ['how to vet a solar company', 'fake solar reviews'],
        searchIntent: 'A researcher drowning in star ratings wants techniques for verifying installer reputations across review platforms.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Will You Need an Electrical Panel Upgrade for Solar?',
        slug: 'electrical-panel-upgrade-for-solar',
        primaryKeyword: 'electrical panel upgrade for solar',
        secondaryKeywords: ['200 amp panel for solar', 'main panel upgrade cost solar'],
        searchIntent: 'A homeowner with an older breaker box wants to know whether solar requires a panel upgrade and what it adds to the project.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Roof Access, Scaffolding and Safety: The Overlooked Install Logistics',
        slug: 'solar-install-roof-access',
        primaryKeyword: 'solar installation roof access',
        secondaryKeywords: ['scaffolding for solar installation', 'solar install site logistics'],
        searchIntent: 'A homeowner with a tricky roof or tight lot wants to know how crews manage access, equipment staging, and safety on site.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
    ],
  },
  {
    cluster: 'Maintenance, cleaning and lifespan',
    category: 'Maintenance & Lifespan',
    entries: [
      {
        title: 'How Long Do Solar Panels Really Last? Lifespan, Explained',
        slug: 'how-long-do-solar-panels-last',
        primaryKeyword: 'how long do solar panels last',
        secondaryKeywords: ['solar panel lifespan', 'solar panel life expectancy'],
        searchIntent: 'A prospective buyer wants a realistic picture of how many decades panels produce useful power and what shortens that span.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
        pillar: true,
      },
      {
        title: 'Solar Panel Degradation: What Your System Loses Each Year',
        slug: 'solar-panel-degradation-rate',
        primaryKeyword: 'solar panel degradation rate',
        secondaryKeywords: ['solar panel efficiency loss over time', 'annual solar degradation'],
        searchIntent: 'An owner or shopper wants to understand typical yearly output decline and how degradation affects long-term savings.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: "Do Solar Panels Need Cleaning? When Rain Isn't Enough",
        slug: 'do-solar-panels-need-cleaning',
        primaryKeyword: 'do solar panels need cleaning',
        secondaryKeywords: ['does rain clean solar panels', 'how often to clean solar panels'],
        searchIntent: 'An owner wondering about dusty panels wants to know whether cleaning is worthwhile and how often it genuinely helps.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Cleaning Solar Panels Safely: A Step-by-Step Homeowner Method',
        slug: 'how-to-clean-solar-panels',
        primaryKeyword: 'how to clean solar panels',
        secondaryKeywords: ['cleaning solar panels from the ground', 'best way to wash solar panels'],
        searchIntent: 'A DIY-minded owner wants safe tools, techniques, and timing for washing rooftop panels without damage or injury.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Snow on Solar Panels: Remove It or Let It Slide?',
        slug: 'snow-on-solar-panels',
        primaryKeyword: 'snow on solar panels',
        secondaryKeywords: ['removing snow from solar panels', 'do solar panels work in snow'],
        searchIntent: 'A homeowner in a snowy state wants to know how snow affects production and whether clearing panels is safe or necessary.',
        relatedCalculators: ['how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Hail, Wind and Storms: How Tough Are Solar Panels, Really?',
        slug: 'solar-panel-hail-storm-damage',
        primaryKeyword: 'solar panel hail damage',
        secondaryKeywords: ['solar panels and hurricanes', 'storm damage to solar panels'],
        searchIntent: 'A homeowner in severe-weather territory wants to know what impact ratings mean and what to do after a damaging storm.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Reading Your Solar Monitoring App: Numbers That Signal Trouble',
        slug: 'solar-monitoring-warning-signs',
        primaryKeyword: 'solar panel monitoring',
        secondaryKeywords: ['solar monitoring app explained', 'solar production alerts'],
        searchIntent: 'An owner staring at their monitoring dashboard wants to know which metrics matter and which readings indicate a fault.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Common Solar Panel Problems and What Causes Them',
        slug: 'common-solar-panel-problems',
        primaryKeyword: 'common solar panel problems',
        secondaryKeywords: ['solar system faults', 'why is my solar system not working'],
        searchIntent: 'A troubled owner wants a rundown of the most frequent solar system failures, their symptoms, and who fixes each one.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Squirrels, Birds and Your Solar Array: Preventing Pest Damage',
        slug: 'solar-panel-pest-damage',
        primaryKeyword: 'squirrels chewing solar panel wires',
        secondaryKeywords: ['birds nesting under solar panels', 'critter guard for solar panels'],
        searchIntent: 'A homeowner hearing scratching under their panels wants to stop animals from nesting and chewing wiring.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: "The Inverter: Your Solar System's Most Likely First Failure",
        slug: 'solar-inverter-failure',
        primaryKeyword: 'solar inverter failure',
        secondaryKeywords: ['how long do solar inverters last', 'solar inverter replacement cost'],
        searchIntent: 'An owner wants to understand why inverters fail before panels do and what replacement typically involves.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Does Homeowners Insurance Cover Solar Panels?',
        slug: 'homeowners-insurance-solar-panels',
        primaryKeyword: 'does homeowners insurance cover solar panels',
        secondaryKeywords: ['solar panel insurance claim', 'adding solar to home insurance'],
        searchIntent: 'A policyholder wants to know how rooftop solar fits into homeowners coverage and when a claim would apply.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Extended Solar Warranties: Worth the Extra Cost?',
        slug: 'extended-solar-warranty',
        primaryKeyword: 'extended solar panel warranty',
        secondaryKeywords: ['solar warranty extension', 'third-party solar protection plans'],
        searchIntent: 'An owner offered a paid warranty extension wants an honest cost-benefit assessment before buying extra coverage.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Repair or Replace? Deciding When a Solar Panel Fails',
        slug: 'repair-or-replace-solar-panels',
        primaryKeyword: 'solar panel repair or replace',
        secondaryKeywords: ['broken solar panel options', 'replacing a single solar panel'],
        searchIntent: 'An owner with a failed or damaged panel wants a decision framework for repairing, swapping, or leaving it be.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Panel Recycling: What Happens at the End of the Line',
        slug: 'solar-panel-recycling',
        primaryKeyword: 'solar panel recycling',
        secondaryKeywords: ['how to dispose of solar panels', 'solar panel end of life'],
        searchIntent: 'An environmentally minded owner wants to know how old panels are recycled and what disposal options exist in the US.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Hotspots, Microcracks and PID: Solar Panel Defects Decoded',
        slug: 'solar-panel-defects',
        primaryKeyword: 'solar panel hotspots and microcracks',
        secondaryKeywords: ['potential induced degradation', 'solar panel defect signs'],
        searchIntent: 'A technically curious owner wants to understand the physical defects that quietly degrade panel output and how they are detected.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Troubleshooting a Sudden Drop in Solar Production',
        slug: 'solar-production-drop-troubleshooting',
        primaryKeyword: 'solar panels producing less than usual',
        secondaryKeywords: ['solar output dropped suddenly', 'low solar production causes'],
        searchIntent: 'An owner whose output has tanked wants a systematic checklist to isolate the cause before calling for service.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Solar Cleaning Services vs DIY: Costs, Safety and Results',
        slug: 'solar-cleaning-service-vs-diy',
        primaryKeyword: 'solar panel cleaning service cost',
        secondaryKeywords: ['professional solar cleaning vs DIY', 'is solar panel cleaning worth paying for'],
        searchIntent: 'An owner weighing a cleaning quote wants to compare professional service value against doing the job themselves.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Moss, Lichen, Dust or Pollen: Panel Grime by Climate',
        slug: 'solar-panel-dirt-by-climate',
        primaryKeyword: 'moss on solar panels',
        secondaryKeywords: ['lichen on solar panels', 'pollen and dust on solar panels'],
        searchIntent: 'A homeowner wants to know which kinds of buildup their regional climate produces and how each affects output and cleaning.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Upgrading an Aging Solar System: Add, Replace or Repower?',
        slug: 'upgrading-old-solar-panels',
        primaryKeyword: 'upgrading old solar panels',
        secondaryKeywords: ['adding panels to existing solar system', 'repowering a solar array'],
        searchIntent: 'An owner of a decade-old array wants to compare expanding, partially replacing, or fully repowering their system.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'The Annual Solar Checkup: A Simple Maintenance Routine',
        slug: 'annual-solar-maintenance-checklist',
        primaryKeyword: 'solar panel maintenance checklist',
        secondaryKeywords: ['yearly solar system inspection', 'solar maintenance routine'],
        searchIntent: 'A hands-on owner wants a once-a-year inspection routine that catches small issues before they cost real money.',
        relatedCalculators: ['solar-panel-calculator'],
      },
    ],
  },
  {
    cluster: 'Federal tax credits and incentives',
    category: 'Incentives & Tax Credits',
    entries: [
      {
        title: 'Stacking Solar Incentives: How Credits, Rebates and Exemptions Combine',
        slug: 'stacking-solar-incentives',
        primaryKeyword: 'solar incentive stacking',
        secondaryKeywords: ['combining solar rebates and tax credits', 'solar incentives order of operations'],
        searchIntent: 'A homeowner juggling multiple incentives wants to understand the order they apply in and how each affects the others.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
        pillar: true,
      },
      {
        title: 'Filing IRS Form 5695: Claiming Your Solar Credit Step by Step',
        slug: 'irs-form-5695-solar',
        primaryKeyword: 'IRS Form 5695 solar',
        secondaryKeywords: ['how to file for the solar tax credit', 'Form 5695 instructions solar'],
        searchIntent: 'A taxpayer who installed solar wants a procedural walkthrough of completing Form 5695 and attaching it to their return.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'The Federal Tax Credit for Home Batteries: Rules That Trip People Up',
        slug: 'battery-storage-tax-credit',
        primaryKeyword: 'battery storage tax credit',
        secondaryKeywords: ['home battery federal tax credit', 'does battery storage qualify for the solar credit'],
        searchIntent: 'A homeowner adding or retrofitting a battery wants to know the capacity and eligibility rules for claiming the credit on storage.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: "Re-Roofing With Solar: What the Tax Credit Does (and Doesn't) Cover",
        slug: 'roof-replacement-solar-tax-credit',
        primaryKeyword: 'does solar tax credit cover roof replacement',
        secondaryKeywords: ['new roof and solar tax credit', 'roof costs eligible for solar credit'],
        searchIntent: 'A homeowner replacing their roof alongside a solar install wants to know which project costs can legitimately be claimed.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Solar Tax Credit Carryover: Using Leftover Credit in Future Years',
        slug: 'solar-tax-credit-carryover',
        primaryKeyword: 'solar tax credit carryover',
        secondaryKeywords: ['unused solar tax credit rollover', 'carrying forward the solar credit'],
        searchIntent: 'A filer whose credit exceeds their tax bill wants to know how the unused portion carries forward to later returns.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: "No Tax Liability? Why Some Homeowners Can't Use the Solar Credit",
        slug: 'solar-tax-credit-tax-liability',
        primaryKeyword: 'solar tax credit tax liability',
        secondaryKeywords: ['solar credit for retirees', 'nonrefundable solar tax credit explained'],
        searchIntent: 'A retiree or low-income homeowner wants to know whether their tax situation lets them benefit from the nonrefundable credit.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Solar on New Construction: Timing the Credit Correctly',
        slug: 'solar-tax-credit-new-construction',
        primaryKeyword: 'solar tax credit new construction',
        secondaryKeywords: ['solar credit for newly built homes', 'when to claim solar credit on a new build'],
        searchIntent: 'A buyer of a new-build home with solar wants to know who claims the credit and in which tax year it applies.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Rentals, Vacation Homes and the Solar Credit: Where the Line Falls',
        slug: 'solar-tax-credit-rental-second-home',
        primaryKeyword: 'solar tax credit rental property',
        secondaryKeywords: ['solar credit for second home', 'vacation home solar tax credit rules'],
        searchIntent: 'An owner of a rental or second home wants to know which properties qualify for the residential credit and which do not.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Property Tax Exemptions for Solar: Why Your Assessment May Not Rise',
        slug: 'solar-property-tax-exemption',
        primaryKeyword: 'solar property tax exemption',
        secondaryKeywords: ['do solar panels raise property taxes', 'solar home value assessment'],
        searchIntent: 'A homeowner worried about a higher tax bill wants to understand how solar property-tax exemptions generally work across states.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Sales Tax Exemptions on Solar Equipment, Explained',
        slug: 'solar-sales-tax-exemption',
        primaryKeyword: 'solar sales tax exemption',
        secondaryKeywords: ['sales tax on solar panels', 'solar equipment tax exemption'],
        searchIntent: 'A shopper pricing a system wants to understand how state sales-tax exemptions on solar equipment typically reduce upfront cost.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'SRECs: Earning Certificates for the Power Your Panels Make',
        slug: 'srecs-explained',
        primaryKeyword: 'what are SRECs',
        secondaryKeywords: ['solar renewable energy certificates', 'how to sell SRECs'],
        searchIntent: 'An owner in an SREC market wants to understand how certificates are earned, priced, and sold for extra income.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Utility Solar Rebates: How They Work and How to Claim One',
        slug: 'utility-solar-rebates',
        primaryKeyword: 'utility solar rebates',
        secondaryKeywords: ['power company solar rebate', 'claiming a utility rebate for solar'],
        searchIntent: 'A homeowner wants to understand the typical mechanics of utility-run rebate programs and how installers process them.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'USDA REAP Grants: Solar Funding for Farms and Rural Businesses',
        slug: 'usda-reap-solar-grant',
        primaryKeyword: 'USDA REAP solar grant',
        secondaryKeywords: ['REAP grant solar eligibility', 'rural energy for america program solar'],
        searchIntent: 'A farm or rural small-business owner wants a brief overview of how REAP grants can help fund a solar project.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Solar Loans and the Tax Credit: How Financing Changes the Math',
        slug: 'solar-financing-tax-credit',
        primaryKeyword: 'solar loan tax credit',
        secondaryKeywords: ['solar loan re-amortization', 'financing solar with the federal credit'],
        searchIntent: 'A financed buyer wants to understand how loans structured around the tax credit work and what happens if they keep the refund.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Incentives Change: Protecting Your Solar Decision From Policy Shifts',
        slug: 'solar-incentive-policy-risk',
        primaryKeyword: 'will solar incentives expire',
        secondaryKeywords: ['solar incentive changes', 'planning solar around policy risk'],
        searchIntent: 'A cautious shopper wants a framework for making a sound solar decision despite the possibility that incentives shrink or end.',
        relatedCalculators: ['solar-roi-calculator'],
      },
    ],
  },
];
