// Topic plan expansion (cluster F): State Guides
// Expands the library from 300 to 500 articles. This file contributes 40
// State Guides entries: 27 remaining-state / jurisdiction guides plus 13
// regional/climate cross-state angles.
//
// Duplicate-avoidance: cross-checked against content-plan.json (300 entries).
// No slug, primaryKeyword, or searchIntent reuses an existing one. States
// already covered elsewhere (California, Texas, Florida, Arizona, Nevada,
// North Carolina, New York, Massachusetts, New Jersey, Colorado, Washington,
// Oregon, Illinois, Ohio, Pennsylvania, Georgia, Virginia, Michigan,
// Minnesota, Utah, New Mexico, South Carolina, Connecticut, Maryland) are NOT
// repeated here. Existing climate angles (solar-panels-in-cold-climates,
// solar-savings-cloudy-climates) are kept distinct from the regional angles
// below.

export const clusters = [
  {
    cluster: 'State guides (expansion)',
    category: 'State Guides',
    entries: [
      // ---- Remaining individual states (26) + Washington, D.C. ----
      {
        title: 'Solar in Alabama: Strong Sun, Steep Utility Fees on Rooftop Power',
        slug: 'solar-panels-in-alabama',
        primaryKeyword: 'solar panels in alabama',
        secondaryKeywords: ['alabama solar', 'alabama solar incentives', 'solar in alabama'],
        searchIntent: 'Alabama pairs some of the Deep South\'s strongest sunshine with utility fees and weak export credits that blunt rooftop returns, so system design leans toward maximizing self-consumption.',
        relatedCalculators: ['solar-roi-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Solar in Alaska: Midnight-Sun Summers and Long, Dark Winters',
        slug: 'solar-panels-in-alaska',
        primaryKeyword: 'solar panels in alaska',
        secondaryKeywords: ['alaska solar', 'solar panels alaska', 'solar in alaska'],
        searchIntent: 'Alaska\'s extreme high latitude swings from near-endless summer daylight to dark winters while remote-community rates rank among the nation\'s highest, reshaping how owners size and value an array.',
        relatedCalculators: ['solar-panel-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Arkansas Solar: A Young Market Reworking Its Net-Metering Rules',
        slug: 'solar-panels-in-arkansas',
        primaryKeyword: 'solar panels in arkansas',
        secondaryKeywords: ['arkansas solar', 'arkansas net metering', 'solar in arkansas'],
        searchIntent: 'Arkansas is a young solar market where recently expanded leasing and evolving net-metering rules are opening access even though low retail rates keep paybacks longer.',
        relatedCalculators: ['solar-roi-calculator', 'solar-payback-calculator'],
      },
      {
        title: 'Delaware Solar and the SREC Market That Sweetens the Math',
        slug: 'solar-panels-in-delaware',
        primaryKeyword: 'solar panels in delaware',
        secondaryKeywords: ['delaware solar', 'delaware srec', 'solar in delaware'],
        searchIntent: 'Delaware\'s compact mid-Atlantic grid pairs moderate-to-high rates with an SREC market whose tradable credits add a second revenue stream on top of bill savings.',
        relatedCalculators: ['solar-roi-calculator', 'federal-tax-credit-calculator'],
      },
      {
        title: 'Hawaii Solar: The Highest Rates in America Meet a Saturated Grid',
        slug: 'solar-panels-in-hawaii',
        primaryKeyword: 'solar panels in hawaii',
        secondaryKeywords: ['hawaii solar', 'hawaii electricity rates', 'solar in hawaii'],
        searchIntent: 'Hawaii\'s nation-topping electricity rates make solar compelling, but saturated island grids have replaced standard net metering with self-supply programs that make a battery essential to capture value.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Idaho Solar: Great Sun Fighting Some of the Cheapest Hydropower',
        slug: 'solar-panels-in-idaho',
        primaryKeyword: 'solar panels in idaho',
        secondaryKeywords: ['idaho solar', 'idaho net metering', 'solar in idaho'],
        searchIntent: 'Idaho enjoys strong intermountain summer sun yet leans on inexpensive hydropower, so low retail rates stretch payback and make utility-specific net-metering terms decisive.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Indiana Solar After Net Metering: Why Self-Use Now Rules the Math',
        slug: 'solar-panels-in-indiana',
        primaryKeyword: 'solar panels in indiana',
        secondaryKeywords: ['indiana solar', 'indiana net metering', 'solar in indiana'],
        searchIntent: 'Indiana has phased out full-retail net metering in favor of lower instantaneous-netting credits, pushing homeowners toward self-consumption and storage to protect the economics.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Iowa Solar: Farm-Country Ground Mounts and Steady Net Metering',
        slug: 'solar-panels-in-iowa',
        primaryKeyword: 'solar panels in iowa',
        secondaryKeywords: ['iowa solar', 'iowa net metering', 'farm solar iowa'],
        searchIntent: 'Iowa combines retained net metering with abundant rural land, making farm-scale ground-mounted arrays a distinctive path alongside cold-winter production planning.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Kansas Solar: Big Plains Sun Versus Demand Charges on Rooftops',
        slug: 'solar-panels-in-kansas',
        primaryKeyword: 'solar panels in kansas',
        secondaryKeywords: ['kansas solar', 'kansas demand charges', 'solar in kansas'],
        searchIntent: 'Kansas offers powerful Great Plains sun, but demand charges and the absence of a strong net-metering mandate mean bill structure matters as much as sunshine to the payoff.',
        relatedCalculators: ['electricity-bill-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Kentucky Solar: Coal-Cheap Power and Shrinking Export Credits',
        slug: 'solar-panels-in-kentucky',
        primaryKeyword: 'solar panels in kentucky',
        secondaryKeywords: ['kentucky solar', 'kentucky net metering', 'solar in kentucky'],
        searchIntent: 'Kentucky\'s coal-heavy grid keeps retail rates low, and its shift from retail net metering to avoided-cost export credits makes right-sizing to on-site use critical.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Louisiana Solar: Hurricane-Ready Panels in a Low-Rate Market',
        slug: 'solar-panels-in-louisiana',
        primaryKeyword: 'solar panels in louisiana',
        secondaryKeywords: ['louisiana solar', 'hurricane rated solar', 'solar in louisiana'],
        searchIntent: 'Louisiana\'s hot, hurricane-exposed Gulf climate demands wind-rated mounting while its low rates and avoided-cost buyback push owners to value resilience and self-use over exports.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Maine Solar: High Rates and Heat Pumps Make Cold-Climate Sense',
        slug: 'solar-panels-in-maine',
        primaryKeyword: 'solar panels in maine',
        secondaryKeywords: ['maine solar', 'maine net energy billing', 'solar in maine'],
        searchIntent: 'Maine\'s high electricity rates, favorable net energy billing, and rapid heat-pump adoption combine to make solar surprisingly strong despite short, snowy winters.',
        relatedCalculators: ['heat-pump-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Mississippi Solar: Deep-South Sun in an Emerging Rooftop Market',
        slug: 'solar-panels-in-mississippi',
        primaryKeyword: 'solar panels in mississippi',
        secondaryKeywords: ['mississippi solar', 'mississippi net metering', 'solar in mississippi'],
        searchIntent: 'Mississippi is an emerging Deep-South market with abundant sun but modest bill-credit compensation, so the economics hinge on covering heavy summer cooling loads directly.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Missouri Solar: Utility Rebates and Four-Season Production Swings',
        slug: 'solar-panels-in-missouri',
        primaryKeyword: 'solar panels in missouri',
        secondaryKeywords: ['missouri solar', 'missouri solar rebates', 'solar in missouri'],
        searchIntent: 'Missouri\'s solar uptake has leaned on utility rebate programs, and its four-season climate produces pronounced summer-to-winter output swings owners must plan around.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Montana Solar: High-Altitude Sun and a Huge Seasonal Daylight Swing',
        slug: 'solar-panels-in-montana',
        primaryKeyword: 'solar panels in montana',
        secondaryKeywords: ['montana solar', 'montana net metering', 'solar in montana'],
        searchIntent: 'Montana blends high-altitude, high-clarity sun with one of the country\'s largest seasonal daylight swings, while retained net metering supports banking summer surplus for winter.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Nebraska Solar: How an All-Public-Power State Shapes the Rules',
        slug: 'solar-panels-in-nebraska',
        primaryKeyword: 'solar panels in nebraska',
        secondaryKeywords: ['nebraska solar', 'public power solar', 'solar in nebraska'],
        searchIntent: 'Nebraska is unique as an all-public-power state, so its municipal and public-district utilities, not a statewide mandate, set the net-metering and interconnection terms that drive returns.',
        relatedCalculators: ['solar-roi-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'New Hampshire Solar: High Rates and No Sales Tax on Your System',
        slug: 'solar-panels-in-new-hampshire',
        primaryKeyword: 'solar panels in new hampshire',
        secondaryKeywords: ['new hampshire solar', 'nh solar', 'solar in new hampshire'],
        searchIntent: 'New Hampshire\'s high rates and absence of a state sales tax lower the net installed cost, helping cold-climate arrays pencil out despite winter production dips.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'North Dakota Solar: Strong Summer Sun Against Rock-Bottom Rates',
        slug: 'solar-panels-in-north-dakota',
        primaryKeyword: 'solar panels in north dakota',
        secondaryKeywords: ['north dakota solar', 'north dakota electricity rates', 'solar in north dakota'],
        searchIntent: 'North Dakota gets strong summer sun but sits on some of the nation\'s cheapest coal-and-wind power, so extremely low rates are the main hurdle to a fast payback.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Oklahoma Solar: Plains Sun, Severe Storms, and Weak Net Metering',
        slug: 'solar-panels-in-oklahoma',
        primaryKeyword: 'solar panels in oklahoma',
        secondaryKeywords: ['oklahoma solar', 'oklahoma net metering', 'solar in oklahoma'],
        searchIntent: 'Oklahoma\'s Southern Plains deliver strong sun and wind alongside severe-storm and hail exposure, while weak net-metering rules make on-site usage the core of the savings case.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Rhode Island Solar: High Rates and a Strong State Growth Program',
        slug: 'solar-panels-in-rhode-island',
        primaryKeyword: 'solar panels in rhode island',
        secondaryKeywords: ['rhode island solar', 'rhode island renewable energy growth', 'solar in rhode island'],
        searchIntent: 'Rhode Island couples some of New England\'s highest rates with a robust state renewable-growth tariff, making dense coastal rooftops worth developing despite limited roof space.',
        relatedCalculators: ['solar-roi-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'South Dakota Solar: No Net-Metering Mandate, So Self-Use Wins',
        slug: 'solar-panels-in-south-dakota',
        primaryKeyword: 'solar panels in south dakota',
        secondaryKeywords: ['south dakota solar', 'south dakota net metering', 'solar in south dakota'],
        searchIntent: 'South Dakota has no statewide net-metering mandate, so cold-climate owners must design around self-consumption and storage rather than counting on generous export credits.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Tennessee Solar: How the TVA Grid Shapes Rooftop Payback',
        slug: 'solar-panels-in-tennessee',
        primaryKeyword: 'solar panels in tennessee',
        secondaryKeywords: ['tennessee solar', 'tva solar', 'solar in tennessee'],
        searchIntent: 'Tennessee sits inside the Tennessee Valley Authority grid, where TVA and local power companies, not a conventional state commission, shape the connection and compensation rules for rooftop solar.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Vermont Solar: Strong Net Metering Offsets Short Winter Days',
        slug: 'solar-panels-in-vermont',
        primaryKeyword: 'solar panels in vermont',
        secondaryKeywords: ['vermont solar', 'vermont net metering', 'solar in vermont'],
        searchIntent: 'Vermont\'s strong net-metering program and location adders help offset short, snowy winter days, making solar viable in a cold, high-rate, renewables-friendly state.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'West Virginia Solar: Cheap Coal Power and Ridgeline Shade',
        slug: 'solar-panels-in-west-virginia',
        primaryKeyword: 'solar panels in west virginia',
        secondaryKeywords: ['west virginia solar', 'wv solar', 'solar in west virginia'],
        searchIntent: 'West Virginia\'s cheap coal-based power and heavily forested, mountainous terrain create shading and payback challenges even though the state retains net metering.',
        relatedCalculators: ['solar-payback-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Wisconsin Solar: A Utility-by-Utility Buyback Patchwork',
        slug: 'solar-panels-in-wisconsin',
        primaryKeyword: 'solar panels in wisconsin',
        secondaryKeywords: ['wisconsin solar', 'wisconsin net metering', 'solar in wisconsin'],
        searchIntent: 'Wisconsin\'s solar economics vary utility by utility because buyback rates are set locally, and its Great Lakes climate brings lake-effect clouds and heavy winter snow.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Wyoming Solar: High-Altitude Sun Versus the Cheapest Coal Power',
        slug: 'solar-panels-in-wyoming',
        primaryKeyword: 'solar panels in wyoming',
        secondaryKeywords: ['wyoming solar', 'wyoming net metering', 'solar in wyoming'],
        searchIntent: 'Wyoming\'s high-altitude plains get abundant sun and wind, but the nation\'s cheapest coal power and a net-metering system cap combine to lengthen the road to payback.',
        relatedCalculators: ['solar-payback-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Washington, D.C. Solar: A Top SREC Market on City Rooftops',
        slug: 'solar-panels-in-washington-dc',
        primaryKeyword: 'solar panels in washington dc',
        secondaryKeywords: ['washington dc solar', 'dc srec', 'solar in washington dc'],
        searchIntent: 'Washington, D.C. runs one of the country\'s most valuable SREC markets, rewarding even small rowhouse rooftops, though dense urban roofs and historic districts complicate layout and permitting.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-roi-calculator'],
      },

      // ---- Regional / climate cross-state angles (13) ----
      {
        title: 'Solar in the Pacific Northwest: Bright Summers, Dark Wet Winters',
        slug: 'solar-in-the-pacific-northwest',
        primaryKeyword: 'solar in the pacific northwest',
        secondaryKeywords: ['pacific northwest solar', 'solar in washington and oregon', 'pnw solar production'],
        searchIntent: 'The Pacific Northwest offsets its dark, wet winters with long, bright summer days, so annual production hinges on banking a big summer surplus against a deep seasonal trough.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Desert Southwest Solar: Managing Heat, Dust, and Monsoon Season',
        slug: 'solar-in-the-desert-southwest',
        primaryKeyword: 'solar in the desert southwest',
        secondaryKeywords: ['desert solar', 'solar in hot climates', 'southwest solar heat'],
        searchIntent: 'Solar in the desert Southwest must be engineered for extreme heat that derates panels, blowing dust that soils glass, and monsoon storms, all of which shave output from otherwise elite sun.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Solar in Hurricane-Prone Gulf States: Wind Codes and Salt Air',
        slug: 'solar-in-hurricane-prone-gulf-states',
        primaryKeyword: 'solar in gulf coast hurricane states',
        secondaryKeywords: ['gulf coast solar', 'hurricane solar panels', 'coastal wind rated solar'],
        searchIntent: 'Solar across the hurricane-prone Gulf states lives or dies on wind-uplift-rated mounting, stricter coastal building codes, salt-air corrosion, and insurance considerations unique to storm country.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'High-Altitude Solar in the Mountain West: Thin Air, Intense UV',
        slug: 'high-altitude-solar-mountain-west',
        primaryKeyword: 'high altitude solar in the mountain west',
        secondaryKeywords: ['high altitude solar', 'rocky mountain solar', 'mountain west solar'],
        searchIntent: 'High-altitude Mountain West arrays receive intense, thin-air sunlight and elevated UV that boost output, but must also handle deep cold, heavy snow, and wide daily temperature swings.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Solar in the Cold, Snowy North: Snow Load and Winter Output',
        slug: 'solar-in-cold-snowy-northern-states',
        primaryKeyword: 'solar in cold snowy northern states',
        secondaryKeywords: ['northern states solar', 'snow load solar panels', 'winter solar production'],
        searchIntent: 'Solar in the cold, snowy northern states is shaped by roof snow load, winter production shortfalls, and the reflected-light bonus that fresh snow can add on clear days.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'solar-panel-calculator'],
      },
      {
        title: 'Solar in the Humid Southeast: Heavy AC Loads and Storm Season',
        slug: 'solar-in-the-humid-southeast',
        primaryKeyword: 'solar in the humid southeast',
        secondaryKeywords: ['southeast solar', 'humid climate solar', 'solar for air conditioning load'],
        searchIntent: 'Solar in the humid Southeast is sized around heavy air-conditioning loads, frequent thunderstorms, and haze, with abundant cooling-season sun aligning production to peak demand.',
        relatedCalculators: ['solar-panel-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Solar in New England: High Rates, Old Roofs, and Real Winters',
        slug: 'solar-in-new-england',
        primaryKeyword: 'solar in new england',
        secondaryKeywords: ['new england solar', 'northeast solar', 'solar in high rate states'],
        searchIntent: 'Solar in New England contends with high electricity rates, older and complex roofs, and genuine winters, a mix that rewards careful roof assessment and often pairs well with heat pumps.',
        relatedCalculators: ['solar-roi-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'Solar on the Great Plains: Wind, Hail Country, and Open Land',
        slug: 'solar-on-the-great-plains',
        primaryKeyword: 'solar on the great plains',
        secondaryKeywords: ['great plains solar', 'ground mount solar plains', 'tornado alley solar'],
        searchIntent: 'Solar on the Great Plains must be sited for relentless wind and hail-belt storms, and the region\'s wide-open land makes ground-mounted arrays an especially attractive option.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar in the Great Lakes Region: Lake-Effect Clouds and Snow',
        slug: 'solar-in-the-great-lakes-region',
        primaryKeyword: 'solar in the great lakes region',
        secondaryKeywords: ['great lakes solar', 'midwest solar', 'lake effect clouds solar'],
        searchIntent: 'Solar in the Great Lakes region works around persistent lake-effect cloud cover and heavy snow, so accurate production modeling and winter planning are central to sizing.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Coastal Solar: Beating Salt-Air Corrosion Near the Ocean',
        slug: 'solar-in-coastal-salt-air-climates',
        primaryKeyword: 'coastal solar salt air corrosion',
        secondaryKeywords: ['coastal solar panels', 'salt air corrosion solar', 'marine grade solar racking'],
        searchIntent: 'Solar installed near the coast faces salt-air corrosion that attacks racking and connectors, making marine-grade hardware and corrosion-resistant mounting the deciding design factors.',
        relatedCalculators: ['solar-panel-cost-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar in Wildfire Country: Smoke Haze and Backup When Grids Cut',
        slug: 'solar-in-wildfire-smoke-prone-regions',
        primaryKeyword: 'solar in wildfire prone regions',
        secondaryKeywords: ['wildfire smoke solar', 'solar during power shutoffs', 'smoke haze solar output'],
        searchIntent: 'Solar in wildfire-prone Western regions must account for smoke haze that temporarily cuts output and for public-safety power shutoffs, where paired storage restores resilience.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-calculator'],
      },
      {
        title: 'Solar in Mountainous, Forested Terrain: Ridgelines and Shade',
        slug: 'solar-in-mountainous-forested-terrain',
        primaryKeyword: 'solar in mountainous forested terrain',
        secondaryKeywords: ['mountain terrain solar', 'tree shading solar', 'ridgeline shading solar'],
        searchIntent: 'Solar in mountainous, forested terrain battles ridgeline horizon shading and tree cover, so sun-path and shade analysis often matter more than raw regional sun figures.',
        relatedCalculators: ['solar-panel-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Matching Solar Design to Your Climate Zone: A Regional Guide',
        slug: 'solar-panel-design-by-climate-zone',
        primaryKeyword: 'solar panel design by climate zone',
        secondaryKeywords: ['solar by climate', 'regional solar design', 'climate zone solar planning'],
        searchIntent: 'This guide maps the major US climate zones to the design choices that matter most in each, from heat derating and snow load to wind rating and corrosion protection.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
    ],
  },
];
