// SEO topic plan — batch J (expansion 300 -> 500)
// SunMetricLab (sunmetriclab.com) — US-focused solar calculators + blog.
// Plan only: no articles are written here. Each entry defines a future post.
//
// Rules honored:
// - Incentives & Tax Credits: 10 new long-tail angles (Form 5695 nuances,
//   eligible costs, claim timing, co-owned homes, SREC selling, rebate
//   mechanics, basis reduction, lease eligibility, state credits, itemizing).
// - Off-Grid & Mobile: 10 new angles (boat/marine, well pumps, off-grid
//   inverters, charge-controller sizing, RV lithium, off-grid fridge, RV
//   solar generators, wire sizing, alternator charging, RV A/C).
// - Electricity Usage (electrification): 8 new angles (induction, heat-pump
//   water heaters, all-electric homes, electrification roadmap, heat-pump
//   bill impact, sizing solar for a future EV / full electrification, electric
//   vs gas running cost).
// - Myths & Comparisons: 12 new angles (extreme heat, rain, roof leaks,
//   property taxes, "is solar a scam", solar vs utility, leasing, mono vs
//   poly, direct sunlight, wind vs solar, health/EMF, battery vs standby gen).
// - relatedCalculators only from the approved calculator ids.
// - No overlap with existing slugs, primaryKeywords, or searchIntents.
// - No claims tied to specific current program dollar values; angles are
//   procedural/structural/physical so articles stay time-stable.

export const clusters = [
  {
    cluster: 'Incentives (expansion)',
    category: 'Incentives & Tax Credits',
    entries: [
      {
        title: 'Which Solar Project Costs Actually Qualify for the Federal Credit',
        slug: 'solar-tax-credit-eligible-costs',
        primaryKeyword: 'what costs qualify for the solar tax credit',
        secondaryKeywords: ['solar tax credit eligible expenses', 'what does the solar tax credit cover', 'labor and wiring solar credit'],
        searchIntent: 'A homeowner filing for the credit wants a clear list of which line items on their solar invoice — equipment, wiring, labor, permitting, sales tax — count toward the qualifying cost.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'When Can You Claim the Solar Tax Credit? Timing Rules Explained',
        slug: 'when-to-claim-solar-tax-credit',
        primaryKeyword: 'when can you claim the solar tax credit',
        secondaryKeywords: ['what tax year for solar credit', 'placed in service date solar', 'claim solar credit paid vs installed'],
        searchIntent: 'Someone whose install and payment straddle two tax years wants to know which year the credit belongs to and what the placed-in-service date really means.',
        relatedCalculators: ['federal-tax-credit-calculator'],
      },
      {
        title: 'Claiming the Solar Tax Credit on a Co-Owned Home',
        slug: 'solar-tax-credit-co-owned-home',
        primaryKeyword: 'solar tax credit for a co-owned home',
        secondaryKeywords: ['split solar tax credit between owners', 'unmarried co-owners solar credit', 'solar credit shared ownership'],
        searchIntent: 'Two unmarried co-owners who paid for one solar system want to know how the credit is divided between their separate tax returns.',
        relatedCalculators: ['federal-tax-credit-calculator'],
      },
      {
        title: 'Are Solar Rebates Taxable Income? What the IRS Expects',
        slug: 'are-solar-rebates-taxable',
        primaryKeyword: 'are solar rebates taxable income',
        secondaryKeywords: ['is a solar rebate taxable', 'do you report solar rebates on taxes', 'utility rebate tax treatment'],
        searchIntent: 'A homeowner who received a utility or state rebate wants to know whether that money counts as taxable income when they file.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'How to Actually Sell Your SRECs: Brokers, Markets, and Contracts',
        slug: 'how-to-sell-srecs',
        primaryKeyword: 'how to sell srecs',
        secondaryKeywords: ['srec broker vs aggregator', 'srec spot vs long term contract', 'register solar for srecs'],
        searchIntent: 'An owner in an SREC state wants the step-by-step mechanics of registering their system and choosing between spot sales, brokers, and long-term contracts.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Performance-Based Solar Incentives vs Upfront Rebates',
        slug: 'performance-based-solar-incentives',
        primaryKeyword: 'performance based solar incentives',
        secondaryKeywords: ['production based incentive solar', 'pbi vs rebate solar', 'how pbi payments work'],
        searchIntent: 'A shopper comparing incentive programs wants to understand how production-based payments are metered and paid out versus a one-time upfront rebate.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Does a Utility Rebate Shrink Your Federal Solar Tax Credit?',
        slug: 'rebate-reduces-solar-tax-credit-basis',
        primaryKeyword: 'does a utility rebate reduce the solar tax credit',
        secondaryKeywords: ['rebate reduces solar credit basis', 'subtract rebate before solar credit', 'incentive order of operations tax credit'],
        searchIntent: 'A homeowner who got both a rebate and the federal credit wants to know whether the rebate must be subtracted from cost before the credit is calculated.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Do You Get the Solar Tax Credit If You Lease Your Panels?',
        slug: 'own-vs-lease-solar-tax-credit',
        primaryKeyword: 'solar tax credit for leased panels',
        secondaryKeywords: ['do leased solar panels qualify for tax credit', 'who claims the credit on a solar lease', 'ppa solar tax credit eligibility'],
        searchIntent: 'A homeowner weighing a lease or PPA wants to know why the ownership requirement means the third party, not them, claims the federal credit.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-payment-comparison'],
      },
      {
        title: 'State Solar Tax Credits: How They Stack on the Federal One',
        slug: 'state-solar-tax-credits',
        primaryKeyword: 'state solar tax credits',
        secondaryKeywords: ['states with a solar tax credit', 'state vs federal solar credit', 'how state solar credits work'],
        searchIntent: 'A homeowner wants to understand how a separate state income-tax credit for solar is claimed and how it interacts with the federal credit.',
        relatedCalculators: ['federal-tax-credit-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Do You Have to Itemize to Claim the Solar Tax Credit?',
        slug: 'itemize-for-solar-tax-credit',
        primaryKeyword: 'do you have to itemize for the solar tax credit',
        secondaryKeywords: ['solar tax credit standard deduction', 'itemize or standard deduction solar', 'claim solar credit without itemizing'],
        searchIntent: 'A taxpayer who takes the standard deduction wants reassurance about whether they can still claim the residential clean energy credit for solar.',
        relatedCalculators: ['federal-tax-credit-calculator'],
      },
    ],
  },
  {
    cluster: 'Off-grid & mobile (expansion)',
    category: 'Off-Grid & Mobile',
    entries: [
      {
        title: 'Marine Solar: Sizing and Wiring Panels for a Boat',
        slug: 'marine-solar-panel-setup',
        primaryKeyword: 'solar panels for a boat',
        secondaryKeywords: ['marine solar system sizing', 'sailboat solar setup', 'boat house battery solar charging'],
        searchIntent: 'A boat owner wants a marine-specific framework for sizing panels, protecting gear from salt and motion, and keeping the house battery topped up at anchor.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'Running an Off-Grid Well Pump on Solar Power',
        slug: 'solar-well-pump-off-grid',
        primaryKeyword: 'solar powered well pump off grid',
        secondaryKeywords: ['solar water pump sizing', 'off grid water pumping solar', 'dc submersible pump solar'],
        searchIntent: 'A rural property owner wants to size a solar array and controller to pump water from a well without grid power or a large battery bank.',
        relatedCalculators: ['solar-panel-size-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Choosing an Off-Grid Inverter: Sine Wave, Surge, and Charging',
        slug: 'off-grid-inverter-selection',
        primaryKeyword: 'how to choose an off grid inverter',
        secondaryKeywords: ['pure sine wave vs modified sine', 'inverter charger off grid', 'off grid inverter surge rating'],
        searchIntent: 'Someone building an off-grid system wants to know how to match inverter wattage, surge capacity, and waveform to their loads and battery voltage.',
        relatedCalculators: ['solar-panel-calculator', 'solar-battery-calculator'],
      },
      {
        title: 'How to Size a Solar Charge Controller for Amps and Volts',
        slug: 'solar-charge-controller-sizing',
        primaryKeyword: 'how to size a solar charge controller',
        secondaryKeywords: ['charge controller amp rating', 'mppt controller sizing formula', 'what size charge controller do i need'],
        searchIntent: 'A DIY builder wants a simple method to calculate the amp rating and voltage window a charge controller needs for their panel array and battery bank.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Upgrading Your RV to a Lithium Battery for Solar',
        slug: 'rv-lithium-battery-solar',
        primaryKeyword: 'rv lithium battery for solar',
        secondaryKeywords: ['rv lead acid to lithium upgrade', 'lifepo4 for rv solar', 'rv battery upgrade considerations'],
        searchIntent: 'An RVer with lead-acid batteries wants to know what changes when switching to lithium for solar — capacity, charging profile, and converter compatibility.',
        relatedCalculators: ['solar-battery-calculator'],
      },
      {
        title: 'Powering a Refrigerator Off-Grid Without Draining the Bank',
        slug: 'off-grid-refrigerator-power',
        primaryKeyword: 'powering a refrigerator off grid',
        secondaryKeywords: ['off grid fridge solar sizing', 'dc compressor fridge solar', 'how much solar to run a fridge off grid'],
        searchIntent: 'An off-grid resident wants to size solar and storage to run a refrigerator continuously, and to compare a DC compressor fridge against an AC unit.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Solar Generators for RV and Camping: What Size You Need',
        slug: 'solar-generator-for-rv-camping',
        primaryKeyword: 'solar generator for rv camping',
        secondaryKeywords: ['portable power station for rv', 'solar generator sizing camping', 'best solar generator size boondocking'],
        searchIntent: 'A camper deciding on an all-in-one solar generator wants to match its watt-hour capacity and input to the loads and days between charges on a trip.',
        relatedCalculators: ['solar-battery-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Off-Grid Solar Wire Gauge: Sizing Cable for 12V and 24V',
        slug: 'off-grid-solar-wire-sizing',
        primaryKeyword: 'off grid solar wire gauge',
        secondaryKeywords: ['solar cable size calculator off grid', 'wire size for 12v solar', 'voltage drop off grid wiring'],
        searchIntent: 'A DIY installer wants to choose wire gauge for panel, battery, and inverter runs so voltage drop stays low and the wiring stays safe at low-voltage current.',
        relatedCalculators: ['solar-panel-size-calculator'],
      },
      {
        title: 'Does RV Rooftop Solar Charge While You Drive?',
        slug: 'rv-solar-charging-while-driving',
        primaryKeyword: 'does rv solar charge while driving',
        secondaryKeywords: ['rv solar vs alternator charging', 'solar and dc-dc charger rv', 'charging rv batteries on the road'],
        searchIntent: 'An RVer wants to know whether rooftop solar keeps charging in motion and how it works alongside the vehicle alternator and a DC-DC charger.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'How Much Solar It Takes to Run an RV Air Conditioner Off-Grid',
        slug: 'solar-to-run-rv-air-conditioner',
        primaryKeyword: 'solar panels to run rv air conditioner off grid',
        secondaryKeywords: ['solar for rv ac boondocking', 'run rv air conditioner on battery', 'soft start rv ac solar'],
        searchIntent: 'A boondocker wants a realistic picture of the panels, battery, and inverter needed to run an RV air conditioner off-grid, and why a soft start helps.',
        relatedCalculators: ['solar-panel-size-calculator', 'solar-battery-calculator'],
      },
    ],
  },
  {
    cluster: 'Electrification (expansion)',
    category: 'Electricity Usage',
    entries: [
      {
        title: 'How Much Electricity an Induction Stove Really Uses',
        slug: 'induction-stove-electricity-usage',
        primaryKeyword: 'induction stove electricity usage',
        secondaryKeywords: ['induction cooktop kwh per month', 'induction vs gas energy use', 'how many watts induction range'],
        searchIntent: 'A homeowner switching from gas to induction wants to know how many kWh a cooktop adds each month and what it means for their bill.',
        relatedCalculators: ['electricity-bill-calculator'],
      },
      {
        title: 'Heat Pump Water Heater Electricity Use vs Electric Resistance',
        slug: 'heat-pump-water-heater-usage',
        primaryKeyword: 'heat pump water heater electricity usage',
        secondaryKeywords: ['heat pump water heater kwh', 'hpwh vs electric resistance cost', 'hybrid water heater energy use'],
        searchIntent: 'A homeowner replacing a water heater wants to compare the annual kWh of a heat-pump model against a standard electric-resistance tank.',
        relatedCalculators: ['electricity-bill-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'What It Costs to Run an All-Electric Home Each Month',
        slug: 'all-electric-home-running-cost',
        primaryKeyword: 'all electric home running cost',
        secondaryKeywords: ['cost to run a fully electric house', 'electric only home utility cost', 'all electric home monthly bill'],
        searchIntent: 'A homeowner going all-electric wants a realistic monthly running-cost estimate once heating, hot water, cooking, and driving all run on electricity.',
        relatedCalculators: ['electricity-bill-calculator', 'heat-pump-calculator'],
      },
      {
        title: 'A Home Electrification Roadmap: What Order to Electrify In',
        slug: 'home-electrification-roadmap',
        primaryKeyword: 'home electrification roadmap',
        secondaryKeywords: ['order to electrify your home', 'electrification plan homeowner', 'when to replace gas appliances'],
        searchIntent: 'A homeowner planning to ditch fossil fuels wants a sensible sequence for replacing furnace, water heater, stove, and car without overloading their panel or budget.',
        relatedCalculators: ['heat-pump-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'How Much Does a Heat Pump Add to Your Electric Bill?',
        slug: 'heat-pump-electric-bill-increase',
        primaryKeyword: 'how much does a heat pump add to your electric bill',
        secondaryKeywords: ['heat pump monthly electricity cost', 'heat pump kwh usage winter', 'electric bill after heat pump'],
        searchIntent: 'A homeowner replacing gas or oil heat with a heat pump wants to estimate the added kWh and dollar impact on their electric bill through the seasons.',
        relatedCalculators: ['heat-pump-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'How Many Extra Solar Panels Does an EV Need?',
        slug: 'extra-solar-panels-for-ev',
        primaryKeyword: 'extra solar panels for an ev',
        secondaryKeywords: ['panels needed per ev mile', 'solar array size for electric car', 'add panels for ev charging'],
        searchIntent: 'A homeowner wants to know how many additional panels their yearly EV mileage adds to a solar array.',
        relatedCalculators: ['ev-charging-calculator', 'how-many-solar-panels-do-i-need'],
      },
      {
        title: 'Sizing Solar for a Fully Electrified Home: EV, Heat Pump, Induction',
        slug: 'sizing-solar-for-electrification',
        primaryKeyword: 'sizing solar for home electrification',
        secondaryKeywords: ['solar for all electric home', 'how many panels for electrified home', 'solar plus heat pump plus ev sizing'],
        searchIntent: 'A homeowner electrifying heat, hot water, cooking, and driving wants to size a solar array against the much larger combined electric load.',
        relatedCalculators: ['how-many-solar-panels-do-i-need', 'heat-pump-calculator'],
      },
      {
        title: 'Electric vs Gas Appliances: Which Costs More to Run?',
        slug: 'electric-vs-gas-appliance-cost',
        primaryKeyword: 'electric vs gas appliance running cost',
        secondaryKeywords: ['gas vs electric operating cost', 'cost to run electric vs gas dryer', 'compare fuel cost home appliances'],
        searchIntent: 'A homeowner weighing electric against gas versions of a dryer, stove, or water heater wants a method to compare their real running costs on local rates.',
        relatedCalculators: ['electricity-bill-calculator'],
      },
    ],
  },
  {
    cluster: 'Myths & comparisons (expansion)',
    category: 'Myths & Comparisons',
    entries: [
      {
        title: 'Do Solar Panels Work Better in Extreme Heat? Not Quite',
        slug: 'do-solar-panels-work-in-extreme-heat',
        primaryKeyword: 'do solar panels work in extreme heat',
        secondaryKeywords: ['solar panels hot weather efficiency', 'temperature coefficient solar', 'does heat reduce solar output'],
        searchIntent: 'This piece corrects the assumption that more sun heat means more power by explaining how high cell temperatures actually cut a panel voltage and output.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Do Solar Panels Work in the Rain? What Really Happens',
        slug: 'do-solar-panels-work-in-rain',
        primaryKeyword: 'do solar panels work in the rain',
        secondaryKeywords: ['solar panels rainy day output', 'do solar panels charge when raining', 'rain and solar production'],
        searchIntent: 'The article explains that panels keep producing reduced power in rain from diffuse light and that the rinse can actually help output afterward.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Do Solar Panels Cause Roof Leaks? Separating Myth From Risk',
        slug: 'do-solar-panels-cause-roof-leaks',
        primaryKeyword: 'do solar panels cause roof leaks',
        secondaryKeywords: ['solar panel roof penetration leaks', 'do roof mounts leak', 'flashing solar panel leaks'],
        searchIntent: 'This explainer states up front that properly flashed mounts rarely leak, then details what actually causes leaks and how to prevent them.',
        relatedCalculators: ['solar-panel-cost-calculator'],
      },
      {
        title: 'Do Solar Panels Raise Your Property Taxes?',
        slug: 'do-solar-panels-raise-property-taxes',
        primaryKeyword: 'do solar panels raise property taxes',
        secondaryKeywords: ['solar added home value property tax', 'does solar increase assessment', 'property tax after solar install'],
        searchIntent: 'This article leads with the fact that many states exempt the added value, then explains how assessments and exemptions actually treat a solar system.',
        relatedCalculators: ['solar-roi-calculator'],
      },
      {
        title: 'Is Solar a Scam? Sorting the Real Risks From the Hype',
        slug: 'is-solar-a-scam',
        primaryKeyword: 'is solar a scam',
        secondaryKeywords: ['are solar panels a scam', 'solar sales scam warning signs', 'is going solar worth the risk'],
        searchIntent: 'This piece states that solar itself is legitimate, then separates the genuine physics and savings from the misleading sales pitches that give it a bad name.',
        relatedCalculators: ['solar-roi-calculator', 'solar-panel-cost-calculator'],
      },
      {
        title: 'Is Solar Cheaper Than Just Paying the Electric Company?',
        slug: 'solar-vs-paying-utility',
        primaryKeyword: 'is solar cheaper than paying the electric company',
        secondaryKeywords: ['solar vs staying on the grid cost', 'buy solar or keep paying utility', 'lifetime cost solar vs utility'],
        searchIntent: 'This comparison frames solar as a prepaid decades of electricity and shows when its lifetime cost beats a rising utility bill and when it does not.',
        relatedCalculators: ['solar-roi-calculator', 'electricity-bill-calculator'],
      },
      {
        title: 'Is Leasing Solar a Bad Idea? An Honest Look',
        slug: 'is-leasing-solar-a-bad-idea',
        primaryKeyword: 'is leasing solar worth it',
        secondaryKeywords: ['solar lease pros and cons', 'downsides of leasing solar panels', 'should i lease or buy solar'],
        searchIntent: 'This article explains that a lease is not automatically bad but trades the tax credit and best savings for zero upfront cost, and shows who each path suits.',
        relatedCalculators: ['solar-payment-comparison', 'solar-roi-calculator'],
      },
      {
        title: 'Monocrystalline vs Polycrystalline Panels: Does It Matter?',
        slug: 'monocrystalline-vs-polycrystalline-panels',
        primaryKeyword: 'monocrystalline vs polycrystalline solar panels',
        secondaryKeywords: ['mono vs poly solar panels', 'are monocrystalline panels better', 'poly panel efficiency vs mono'],
        searchIntent: 'This comparison states that mono panels now dominate for good reason, then details the real efficiency, space, and cost differences for a home buyer.',
        relatedCalculators: ['solar-panel-calculator', 'solar-panel-size-calculator'],
      },
      {
        title: 'Do Solar Panels Need Direct Sunlight to Work?',
        slug: 'do-solar-panels-need-direct-sunlight',
        primaryKeyword: 'do solar panels need direct sunlight',
        secondaryKeywords: ['solar panels indirect light', 'do panels work in shade', 'diffuse light solar production'],
        searchIntent: 'This explainer states up front that panels produce from diffuse light too, then quantifies how much less indirect and partial-shade conditions yield.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Home Wind Turbine vs Solar Panels: Which Makes Sense?',
        slug: 'home-wind-turbine-vs-solar',
        primaryKeyword: 'home wind turbine vs solar panels',
        secondaryKeywords: ['residential wind vs solar', 'small wind turbine for home', 'wind or solar for a house'],
        searchIntent: 'This comparison explains why rooftop solar beats a small wind turbine for most homes and the rare siting conditions where residential wind competes.',
        relatedCalculators: ['solar-panel-calculator', 'solar-roi-calculator'],
      },
      {
        title: 'Do Solar Panels Cause Health Problems? The EMF Myth',
        slug: 'solar-panel-health-myths',
        primaryKeyword: 'do solar panels cause health problems',
        secondaryKeywords: ['solar panel emf safety', 'are solar panels dangerous to health', 'solar inverter emf myth'],
        searchIntent: 'This article states plainly that home solar poses no established health risk, then addresses EMF, toxicity, and fire fears with what the evidence shows.',
        relatedCalculators: ['solar-panel-calculator'],
      },
      {
        title: 'Solar Battery vs a Whole-House Standby Generator',
        slug: 'solar-battery-vs-standby-generator',
        primaryKeyword: 'solar battery vs whole house generator',
        secondaryKeywords: ['home battery vs standby generator', 'solar backup vs natural gas generator', 'battery or generator for whole house'],
        searchIntent: 'This comparison contrasts a solar battery with a permanently installed standby generator on runtime, fuel, maintenance, and long-term ownership cost.',
        relatedCalculators: ['solar-battery-calculator', 'solar-roi-calculator'],
      },
    ],
  },
];
