import { describe, expect, it } from 'vitest';
import {
  buildRoutePaths,
  buildRssItems,
  getRelatedArticles,
  isPublished,
  prevNext,
  type ArticleLike,
} from '../src/lib/publishing';

const NOW = new Date('2026-07-12T12:00:00Z');

function article(overrides: Partial<ArticleLike['data']> & { id: string }): ArticleLike {
  const { id, ...data } = overrides;
  return {
    id,
    data: {
      title: id,
      description: `${id} description`,
      publishDate: new Date('2026-01-01T08:00:00Z'),
      draft: false,
      category: 'Solar Costs',
      tags: [],
      primaryKeyword: id,
      secondaryKeywords: [],
      relatedCalculators: [],
      relatedArticles: [],
      featured: false,
      author: 'Test',
      ...data,
    },
  };
}

describe('isPublished', () => {
  it('hides drafts regardless of date', () => {
    expect(isPublished(article({ id: 'a', draft: true, publishDate: new Date('2020-01-01T00:00:00Z') }), NOW)).toBe(false);
  });

  it('hides future articles', () => {
    expect(isPublished(article({ id: 'a', publishDate: new Date('2030-01-01T00:00:00Z') }), NOW)).toBe(false);
  });

  it('publishes past articles', () => {
    expect(isPublished(article({ id: 'a', publishDate: new Date('2026-01-01T00:00:00Z') }), NOW)).toBe(true);
  });

  it('includes an article published exactly at the cutoff', () => {
    expect(isPublished(article({ id: 'a', publishDate: NOW }), NOW)).toBe(true);
  });
});

describe('buildRoutePaths', () => {
  it('does not generate a route for future content', () => {
    const paths = buildRoutePaths(
      [
        article({ id: 'past' }),
        article({ id: 'future', publishDate: new Date('2030-01-01T00:00:00Z') }),
        article({ id: 'draft', draft: true }),
      ],
      NOW,
    );
    expect(paths.map((p) => p.params.slug)).toEqual(['past']);
  });

  it('uses the explicit frontmatter slug when present', () => {
    const paths = buildRoutePaths([article({ id: 'file-name', slug: 'custom-slug' })], NOW);
    expect(paths[0].params.slug).toBe('custom-slug');
  });
});

describe('buildRssItems (feed + sitemap source)', () => {
  it('omits scheduled articles from RSS', () => {
    const items = buildRssItems(
      [article({ id: 'past' }), article({ id: 'future', publishDate: new Date('2030-01-01T00:00:00Z') })],
      NOW,
    );
    expect(items).toHaveLength(1);
    expect(items[0].link).toBe('/blog/past/');
  });
  // The sitemap is generated by @astrojs/sitemap from built routes; since
  // buildRoutePaths (tested above) never emits future routes, a scheduled
  // article cannot appear in the sitemap either.
});

describe('getRelatedArticles', () => {
  it('returns only published entries and drops future/missing/self explicit refs', () => {
    const current = article({
      id: 'current',
      relatedArticles: ['future', 'missing', 'current', 'ok'],
      category: 'Payback',
    });
    const related = getRelatedArticles(
      current,
      [
        current,
        article({ id: 'ok', category: 'Payback' }),
        article({ id: 'future', category: 'Payback', publishDate: new Date('2030-01-01T00:00:00Z') }),
        article({ id: 'draft', category: 'Payback', draft: true }),
        article({ id: 'scored', category: 'Payback' }),
      ],
      NOW,
    );
    const slugs = related.map((entry) => entry.id);
    expect(slugs).toContain('ok');
    expect(slugs).toContain('scored');
    expect(slugs).not.toContain('future');
    expect(slugs).not.toContain('draft');
    expect(slugs).not.toContain('current');
    expect(slugs).not.toContain('missing');
  });

  it('explicit refs come first, then scored fill-up, capped at max', () => {
    const current = article({ id: 'current', relatedArticles: ['explicit'], category: 'Payback' });
    const pool = [
      current,
      article({ id: 'explicit', category: 'Solar Costs' }),
      ...Array.from({ length: 8 }, (_, i) => article({ id: `same-cat-${i}`, category: 'Payback' })),
    ];
    const related = getRelatedArticles(current, pool, NOW, 6);
    expect(related[0].id).toBe('explicit');
    expect(related).toHaveLength(6);
  });
});

describe('prevNext', () => {
  it('navigates chronologically within published set, never revealing scheduled posts', () => {
    const a = article({ id: 'a', publishDate: new Date('2026-01-01T00:00:00Z') });
    const b = article({ id: 'b', publishDate: new Date('2026-02-01T00:00:00Z') });
    const future = article({ id: 'future', publishDate: new Date('2030-01-01T00:00:00Z') });
    const { prev, next } = prevNext([a, b, future], b, NOW);
    expect(prev?.id).toBe('a');
    expect(next).toBeNull();
  });
});
